// B1 — Unidades 5, 6, 7, 8
export const B1_U5_U8 = [
  {
    id: "B1-U5",
    title: "Narrativa avançada e literatura",
    description: "Contar histórias com riqueza, profundidade e estilo",
    lessons: [
      {
        id: "B1-U5-L1",
        title: "Narrar com profundidade — técnicas de storytelling",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Me conta uma história que te marcou profundamente.\n— Bem... era uma tarde de domingo quando tudo mudou.\n— Como assim?\n— Eu estava na casa da minha avó quando ela me chamou para conversar.\n— E o que ela disse?\n— Ela me contou algo que nunca tinha revelado a ninguém. Uma história da família.\n— Que momento especial. Como você se sentiu?\n— Mal conseguia processar. Era como se o chão tivesse saído de baixo dos meus pés.\n— Essa expressão é perfeita. O passado que emerge sempre muda o presente.\n— Exatamente. Nunca mais fui a mesma pessoa depois daquele dia.",
        memoryPhrases: [
          "Era uma tarde quando...",
          "Como se o chão saísse...",
          "Nunca tinha revelado.",
          "Mal conseguia processar.",
          "Nunca mais fui o mesmo."
        ],
        oralProduction: "SITUAÇÃO ORAL: Conte uma história que te marcou usando técnicas de storytelling: contexto, tensão crescente, clímax e transformação pessoal. Use todos os tempos verbais. Mínimo 10 frases.",
        content: "# Narrar com Profundidade\n\n## Estrutura de uma boa história\n1. GANCHO: Captura a atenção no início\n2. CONTEXTO: Quando, onde, quem\n3. CONFLITO/TENSÃO: O problema ou desafio\n4. CLÍMAX: O momento decisivo\n5. RESOLUÇÃO: O que aconteceu\n6. TRANSFORMAÇÃO: Como você mudou\n\n## Ganchos narrativos\nEra uma noite de... quando...\nNunca vou esquecer o dia em que...\nSe alguém me dissesse que... nunca acreditaria.\nHavia algo diferente naquele dia.\nTudo começou com uma simples decisão.\n\n## Construindo tensão\nMal sabia eu que... · Sem perceber...\nAo dobrar a esquina, vi que...\nEm questão de segundos, tudo mudou.\nFoi então que... · De repente...\nComo se o tempo tivesse parado...\n\n## Linguagem sensorial\nVia que... · Ouvia... · Sentia o cheiro de...\nA sensação era de... · Era como se...\nO coração acelerou quando...\n\n## Clímax e resolução\nNaquele momento percebi que...\nFoi a maior lição da minha vida.\nNunca mais fui o mesmo/a.\nAlgo dentro de mim mudou definitivamente.",
        exercises: [
          {id:"B1-U5-L1-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase crea el mejor 'gancho' narrativo?",options:["Vou contar uma história agora.","Ontem aconteceu algo.","Nunca vou esquecer a noite em que tudo mudou.","Quero falar sobre um evento passado."],answer:2,explanation:"'Nunca vou esquecer a noite em que tudo mudou' = gancho poderoso. Crea expectativa y misterio.",hint:"El gancho debe crear expectativa e intriga inmediata"},
          {id:"B1-U5-L1-E2",type:"fill_blank",skill:"grammar",question:"'___ sabia eu que aquela seria a última vez que a veria.' (yo que no sabía — narrativa)",answer:["mal"],hint:"MAL sabia eu = yo que no sabía. Estrutura narrativa para revelar ironia",explanation:"MAL sabia eu que... = Yo que no sabía que... Crea ironía dramática en la narrativa."},
          {id:"B1-U5-L1-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase describe mejor el CLÍMAX de una historia?",options:["E então voltei para casa.","Naquele momento percebi que nada seria mais como antes.","Depois fui dormir.","A história terminou bem."],answer:1,explanation:"'Naquele momento percebi que nada seria mais como antes' = clímax/transformación. El punto de quiebre.",hint:"El clímax muestra la transformación o revelación central"},
          {id:"B1-U5-L1-E4",type:"translation",skill:"writing",question:"Traduce creando un párrafo narrativo: 'Nunca olvidaré la tarde en que mi abuela me llamó. Apenas entré, supe que algo había cambiado. El silencio lo decía todo.'",answer:["nunca vou esquecer a tarde em que minha avó me chamou","mal entrei soube que algo tinha mudado","o silêncio dizia tudo"],hint:"nunca vou esquecer · mal entrei · soube que tinha mudado · o silêncio dizia tudo",explanation:"Nunca vou esquecer a tarde em que minha avó me chamou. Mal entrei, soube que algo tinha mudado. O silêncio dizia tudo."},
          {id:"B1-U5-L1-E5",type:"free_writing",skill:"writing",question:"Escreva uma história completa de um evento que te marcou usando todas as técnicas: gancho, contexto, tensão, clímax e transformação. Use linguagem sensorial e tempos verbais variados. Mínimo 14 orações.",prompt:"GANCHO: Nunca vou esquecer... / CONTEXTO: Era... quando... / TENSÃO: De repente... Mal sabia que... / CLÍMAX: Naquele momento... / TRANSFORMAÇÃO: Desde então...",hint:"gancho · imperfeito (contexto) · perfeito (ações) · mais-que-perfeito (antes) · linguagem sensorial"}
        ]
      },
      {
        id: "B1-U5-L2",
        title: "Análise literária — lendo e interpretando",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você leu algum trecho de Clarice Lispector?\n— Li! Fiquei impressionada com a densidade psicológica.\n— O que você quis dizer?\n— Ela mergulha na mente da personagem de uma forma que poucos escritores conseguem.\n— Qual obra você leu?\n— A Hora da Estrela. O narrador masculino que conta a história de uma mulher nordestina.\n— Uma escolha narrativa muito interessante, né?\n— Muito! E a linguagem... É ao mesmo tempo simples e profundíssima.\n— Clarice é isso. Você sai diferente depois de ler.\n— É exatamente assim. Parece que ela escreve sobre a sua própria vida.",
        memoryPhrases: [
          "A densidade psicológica é...",
          "O narrador mergulha em...",
          "A linguagem é ao mesmo tempo...",
          "A obra retrata...",
          "Você sai diferente depois."
        ],
        oralProduction: "SITUAÇÃO ORAL: Analise um livro, filme ou série que você leu/viu recentemente. Fale sobre: narrador, personagens, temas, linguagem e impacto pessoal. Mínimo 8 frases.",
        content: "# Análise Literária\n\n## Elementos narrativos\nNarrador = narrador\nOnisciente = sabe tudo (3ª pessoa)\nOnisciente parcial = sabe de alguns\nEm 1ª pessoa = o personagem conta\nNarrador não confiável = mente ou se engana\n\nPersonagens:\nProtagonista · Antagonista · Personagem secundário\nPersonagem plano (sem evolução) vs. redondo (evolui)\n\nEnredo = trama · Plot twist = reviravolta\nFlashback · Flash-forward\nTempo cronológico vs. psicológico\n\n## Temas e símbolos\nTema principal = tema central\nTema secundário · Simbolismo · Metáfora\nAlegoria · Ironia · Paradoxo\n\n## Estilo e linguagem\nProsa poética = prosa lírica · Realismo\nModernismo · Literatura marginal\nDensidade psicológica · Fluxo de consciência\nDialetos e registros · Ritmo narrativo\n\n## Vocabulário de análise\nretrata = retrata · reflete = refleja\nmergulha em = se sumerge en\ndenuncia = denuncia · critica = critica\nexplora = explora · questiona = cuestiona\nsimboliza = simboliza · representa",
        exercises: [
          {id:"B1-U5-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo se llama el narrador que sabe los pensamientos de TODOS los personajes?",options:["Narrador em 1ª pessoa","Narrador onisciente","Narrador parcial","Narrador personagem"],answer:1,explanation:"Narrador onisciente = el que sabe todo, incluyendo los pensamientos de todos los personajes.",hint:"El narrador que lo sabe todo"},
          {id:"B1-U5-L2-E2",type:"fill_blank",skill:"vocabulary",question:"A obra de Clarice Lispector é famosa pela sua ___ psicológica, explorando o interior das personagens.",answer:["densidade"],hint:"La profundidad del análisis psicológico en la literatura",explanation:"Densidade psicológica = profundidad psicológica. Característica principal de la obra de Clarice."},
          {id:"B1-U5-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué es un 'plot twist' o 'reviravolta' en una narrativa?",options:["El final feliz","Un giro inesperado que cambia todo","El clímax de la historia","Una metáfora literaria"],answer:1,explanation:"Reviravolta / Plot twist = giro inesperado que cambia completamente la dirección o comprensión de la historia.",hint:"Un giro inesperado que cambia la historia"},
          {id:"B1-U5-L2-E4",type:"translation",skill:"writing",question:"Traduce en lenguaje de análisis literario: 'La novela retrata la soledad urbana a través de una protagonista nordestina. El narrador masculino crea una distancia interesante con el relato.'",answer:["a novela retrata a solidão urbana através de uma protagonista nordestina","o narrador masculino cria uma distância interessante com o relato"],hint:"retrata · solidão urbana · através de · protagonista nordestina · narrador masculino · distância",explanation:"A novela retrata a solidão urbana através de uma protagonista nordestina. O narrador masculino cria uma distância interessante com o relato."},
          {id:"B1-U5-L2-E5",type:"free_writing",skill:"writing",question:"Escreva uma análise literária de um livro, filme ou série que você conhece bem. Analise: narrador, personagens, temas principais, linguagem e impacto cultural. Mínimo 10 orações.",prompt:"A obra [título] retrata... / O narrador... / A personagem principal é... / Os temas centrais são... / A linguagem... / O impacto cultural...",hint:"narrador · personagens · temas · linguagem · simbolismo · retrata · critica · explora · questiona"}
        ]
      },
      {
        id: "B1-U5-L3",
        title: "Poesia e expressão lírica",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você gosta de poesia em português?\n— Adoro! Drummond me conquistou completamente.\n— O que você mais admira nele?\n— A forma como ele une o cotidiano com o filosófico.\n— Exato! 'No meio do caminho tinha uma pedra'... uma imagem tão simples e tão densa.\n— Isso. E a ironia dele! Lê palavras simples, mas o sentido é profundo.\n— A poesia brasileira tem muita riqueza.\n— Tem! Vinicius de Moraes também é incrível. Poesia e música juntas.\n— A bossa nova nasceu dessa fusão.\n— Que herança cultural linda o Brasil tem.",
        memoryPhrases: [
          "A poesia me conquista.",
          "O cotidiano vira filosofia.",
          "Palavras simples, sentido profundo.",
          "A ironia é muito rica.",
          "Que herança cultural linda!"
        ],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre sua relação com a poesia ou música lírica. O que te toca? Qual poeta ou letra de música em português você aprecia? Por quê? Mínimo 7 frases.",
        content: "# Poesia e Expressão Lírica\n\n## Poetas brasileiros essenciais\nCarlos Drummond de Andrade (1902-1987)\n'No meio do caminho tinha uma pedra' — metáfora dos obstáculos\n'E agora, José?' — angústia existencial\nEstilo: ironia, cotidiano, profundidade filosófica\n\nVinicius de Moraes (1913-1980)\nPoeta e músico — bossa nova\nLetra de 'Garota de Ipanema', 'A Felicidade'\nEstilo: amor, beleza, melancolia\n\nCora Coralina (1889-1985) — poetisa de Goiás\nPoesia do povo simples, das mulheres, da terra\nFrase famosa: 'Feliz aquele que transfere o que sabe e aprende o que ensina.'\n\nFerreira Gullar (1930-2016)\nPoesia engajada socialmente\n\n## Recursos poéticos\nMetáfora = comparação implícita\nSímile = comparação com 'como': Ela é como...\nAliteração = repetição de sons\nRima = rima · Verso livre = verso libre\nImagem = imagen poética · Símbolo\n\n## Música como poesia\nChico Buarque · Milton Nascimento · Caetano Veloso\nLetras com profundidade literária\nMPB = tradição de letra como poesia\n\n## Vocabulário de análise poética\nverso = verso · estrofe = estrofa\nrima = rima · ritmo = ritmo\nmetáfora · símbolo · imagem",
        exercises: [
          {id:"B1-U5-L3-E1",type:"multiple_choice",skill:"culture",question:"¿Cuál poeta brasileño es famoso por unir poesía y música en la bossa nova?",options:["Drummond","Cora Coralina","Vinicius de Moraes","Ferreira Gullar"],answer:2,explanation:"Vinicius de Moraes fue poeta Y músico. Escribió las letras de Garota de Ipanema y fundó la bossa nova con Tom Jobim.",hint:"El poeta que también creó la bossa nova"},
          {id:"B1-U5-L3-E2",type:"fill_blank",skill:"vocabulary",question:"A figura de linguagem que faz uma comparação implícita sem 'como' se chama ___.",answer:["metáfora"],hint:"Comparação implícita sem 'como' ou 'igual a'",explanation:"Metáfora = comparación implícita. 'A vida é um rio' (sin 'como'). Símile usa 'como': 'A vida é COMO um rio'."},
          {id:"B1-U5-L3-E3",type:"multiple_choice",skill:"culture",question:"Carlos Drummond de Andrade é famoso por usar ¿qué elementos en su poesía?",options:["Solo temas amorosos","La naturaleza amazónica","El cotidiano con profundidad filosófica e ironía","La política sin ironía"],answer:2,explanation:"Drummond es famoso por transformar situaciones cotidianas en reflexiones filosóficas con mucha ironía.",hint:"Lo cotidiano transformado en filosofía con ironía"},
          {id:"B1-U5-L3-E4",type:"translation",skill:"writing",question:"Traduce en lenguaje poético/literario: 'La vida es una piedra en el camino. A veces tan pequeña, a veces tan grande que no se puede pasar.'",answer:["a vida é uma pedra no caminho","às vezes tão pequena","às vezes tão grande que não se consegue passar"],hint:"pedra no caminho · às vezes · tão pequena · tão grande que",explanation:"A vida é uma pedra no caminho. Às vezes tão pequena, às vezes tão grande que não se consegue passar."},
          {id:"B1-U5-L3-E5",type:"free_writing",skill:"writing",question:"Escreva um poema curto (8-12 versos) em português sobre um sentimento ou tema que te toca. Pode ser verso livre (sem rima obrigatória). Depois explique as metáforas que usou.",prompt:"[POEMA LIVRE]\nExplicação: Na estrofe 1, usei a metáfora de... que representa... / A imagem de... simboliza...",hint:"verso livre · metáforas · imagens · sentimentos · não precisa rimar · seja autêntico"}
        ]
      },
      {
        id: "B1-U5-L4",
        title: "Escrevendo ficção — contos e crônicas",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você já tentou escrever um conto em português?\n— Tentei! É muito diferente de escrever em outros idiomas.\n— O que você sentiu de diferente?\n— A língua tem um ritmo próprio. Certas palavras pedem uma música específica.\n— Exato! O português brasileiro é muito musical.\n— Você escreve contos?\n— Escrevo crônicas. É um gênero muito brasileiro.\n— Ah, a crônica do Rubem Braga! É quase jornalismo literário.\n— Exatamente. Curta, cotidiana, mas com muito estilo.\n— É o gênero ideal para praticar a escrita em português.",
        memoryPhrases: [
          "A língua tem ritmo próprio.",
          "A crônica é muito brasileira.",
          "Curta, cotidiana, com estilo.",
          "O conto precisa de tensão.",
          "Cada palavra é uma escolha."
        ],
        oralProduction: "SITUAÇÃO ORAL: Crie oralmente o início de um conto ou crônica em português. Estabeleça personagens, contexto e um conflito inicial. Mínimo 8 frases narrativas.",
        content: "# Escrevendo Ficção — Contos e Crônicas\n\n## O conto\nNarrativa curta de ficção\nUm único conflito central\nPersonagens poucos mas marcantes\nFim surpreendente ou reflexivo\nMestres: Machado de Assis, Dalton Trevisan, Lygia Fagundes Telles\n\n## A crônica\nGênero tipicamente brasileiro!\nMix de jornalismo + literatura\nTema do cotidiano tratado com estilo\nTom: irônico, lírico, reflexivo, bem-humorado\nCronicistas famosos: Rubem Braga, Paulo Mendes Campos, Martha Medeiros, Luís Fernando Veríssimo\n\n## Elementos do conto\nPersonagem: quem é, o que quer, o que teme\nCenário: onde e quando de forma evocativa\nConflito: o problema ou tensão central\nClímax: momento de maior tensão\nDesfecho: resolução (pode ser aberto)\n\n## Técnicas de escrita criativa\nIn medias res = começar no meio da ação\nDiálogo que caracteriza (sem 'disse lentamente')\nDetalhe específico que generaliza\nFinais em aberto ou reveladores\nPonto de vista incomum\n\n## Vocabulário de ficção\nconto = cuento corto · crônica = crónica\nenredo = argumento · desfecho = desenlace\npersonagem = personaje · narrador = narrador\ncenário = escenario · diálogo = diálogo",
        exercises: [
          {id:"B1-U5-L4-E1",type:"multiple_choice",skill:"culture",question:"¿Cuál es la característica principal de la 'crônica' como género literario brasileño?",options:["Es una novela larga y compleja","Es un mix de jornalismo y literatura sobre temas cotidianos","Es solo poesía en prosa","Es exclusivamente cómica"],answer:1,explanation:"Crônica = género brasileño que mezcla jornalismo y literatura. Tema cotidiano con estilo literario.",hint:"El género literario tipicamente brasileño"},
          {id:"B1-U5-L4-E2",type:"fill_blank",skill:"vocabulary",question:"Começar uma narrativa no meio da ação, sem introdução, se chama começar '___ medias res'.",answer:["in"],hint:"Expressão latina usada em narrativa",explanation:"In medias res = comenzar en medio de la acción. Técnica narrativa que crea inmersión inmediata."},
          {id:"B1-U5-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué es el 'desfecho' de un conto?",options:["El inicio de la historia","El conflito principal","El desenlace/final","El personaje principal"],answer:2,explanation:"Desfecho = desenlace/final. O desfecho do conto pode ser aberto ou surpreendente.",hint:"La parte final de la narrativa"},
          {id:"B1-U5-L4-E4",type:"translation",skill:"writing",question:"Traduce como inicio de un cuento: 'Fue una mañana de martes que todo cambió. Cuando Joana abrió el diario de su abuela, encontró algo que nunca esperaba ver.'",answer:["foi numa manhã de terça-feira que tudo mudou","quando joana abriu o diário de sua avó encontrou algo que nunca esperava ver"],hint:"foi numa manhã que tudo mudou · quando abriu · diário · encontrou · nunca esperava ver",explanation:"Foi numa manhã de terça-feira que tudo mudou. Quando Joana abriu o diário de sua avó, encontrou algo que nunca esperava ver."},
          {id:"B1-U5-L4-E5",type:"free_writing",skill:"writing",question:"Escreva um conto curto ou crônica completa em português (início, conflito, clímax e desfecho). Use as técnicas aprendidas: in medias res, diálogo que caracteriza, detalhes específicos. Mínimo 14 orações.",prompt:"IN MEDIAS RES: Quando [personagem] [ação no momento], [situação]... / CONTEXTO: Era... Ela/Ele... / CONFLITO: De repente... / CLÍMAX: Foi então que... / DESFECHO: Nunca mais...",hint:"não comece com 'Era uma vez'. Vá direto à ação. Use detalhes específicos e diálogos vivos."}
        ]
      },
      {
        id: "B1-U5-L5",
        title: "Oralidade avançada — fluência e naturalidade",
        shadowing: "Lê 3 vezes em voz alta — mais rápido que antes!\n\n— Cara, você viu que o time perdeu ontem?\n— Que situação hein! Tava horrível o segundo tempo.\n— Pois é. Nem sei o que aconteceu com eles.\n— Acredito não. Tavam jogando tão bem no primeiro.\n— Às vezes é assim. Time bom tem esses altos e baixos.\n— É verdade. Mas que sufoco, né? Quase passou do limite.\n— Pior foi o juiz! Deu um pênalti que não era.\n— Ah isso sim foi uma sacanagem. Mas o jogo é assim.\n— Tá bom. Semana que vem tem revancha.\n— Tomara! Aí sim a gente fica quieto.",
        memoryPhrases: [
          "Que situação, hein!",
          "Acredito não!",
          "Pois é...",
          "Que sufoco!",
          "Tomara que..."
        ],
        oralProduction: "SITUAÇÃO ORAL: Tenha uma conversa completamente informal sobre qualquer assunto do dia a dia. Use gírias, contrações, expressões coloquiais e o ritmo real do português brasileiro. Mínimo 12 falas naturais.",
        content: "# Oralidade Avançada — Fala Natural\n\n## Contrações e reduções do PB oral\nestou → tô/tou · está → tá\npara → pra · você → cê/vc\nestamos → tamo · estão → tão\nnão → num (antes de vogal informal)\nmuito → muinto/muito (varia)\nverdade → sabe? / né? / hein?\n\n## Expressões de reação rápida\nQue situação, hein! = ¡Qué situación!\nAcredito não! = ¡No lo creo! (informal de 'não acredito')\nPois é... = Sí, es verdad... (concordância)\nQue sufoco! = ¡Qué agobio!\nNem me fala! = ¡No me hablés!\nMenos mal! = ¡Menos mal!\nUai! / Eita! / Nossa! → variações regionais\n\n## Marcadores discursivos orais\nSabe? / Entendeu? = ¿Entendés?\nTá ligado? = ¿Captás? (informal)\nDaí... = Y entonces...\nAí... = Y ahí...\nBom... = Bueno...\nOlha... / Olha só... = Mira...\n\n## Elipses na fala\nVou indo. = Me voy.\nVem cá. = Vení acá.\nQue foi? = ¿Qué pasó?\nFala. = Hablá. (atender teléfono)\n\n## Ritmo e entonação\nBrasileiro sobe o tom no final de perguntas sim/não\nNo Nordeste o ritmo é mais aberto\nEm SP o ritmo é mais fechado e rápido",
        exercises: [
          {id:"B1-U5-L5-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la contracción de 'para' más usada en el PB oral?",options:["po","pa","pra","pr"],answer:2,explanation:"PRA = para. Vou pra casa = Voy para casa. La forma más común en el habla brasileña informal.",hint:"La reducción de PARA en el habla brasileña informal"},
          {id:"B1-U5-L5-E2",type:"fill_blank",skill:"vocabulary",question:"'___ é. Eu falei a mesma coisa.' (concordância informal)",answer:["pois"],hint:"Expresión de concordancia/confirmación muy brasileña",explanation:"POIS É = Sí, es verdad / Exacto. Marcador de concordância muito usado no PB oral."},
          {id:"B1-U5-L5-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué significa 'Nem me fala!' en uma conversa casual?",options:["Háblame de eso","No me hablés / ¡No me digas más!","No sé nada","Que bien"],answer:1,explanation:"Nem me fala! = ¡No me hablés! / ¡No me digas! Para situaciones malas o incómodas.",hint:"Expresión para situaciones muy malas o incómodas"},
          {id:"B1-U5-L5-E4",type:"translation",skill:"writing",question:"Traduce de forma INFORMAL coloquial: 'Che, ¿viste lo que pasó? No lo puedo creer. Qué situación. Y yo que pensaba que iba a salir bien.'",answer:["cara viu o que aconteceu","acredito não","que situação","e eu que pensava que ia dar certo"],hint:"cara · viu o que aconteceu · acredito não · que situação · eu que pensava · ia dar certo",explanation:"Cara, viu o que aconteceu? Acredito não! Que situação. E eu que pensava que ia dar certo."},
          {id:"B1-U5-L5-E5",type:"free_writing",skill:"writing",question:"Escreva um diálogo completamente informal entre dois amigos brasileiros sobre um assunto qualquer. Use contrações, gírias, marcadores discursivos e o ritmo real do PB. Mínimo 14 falas.",prompt:"— Cara, você tá bem? / — Tô sim! E cê? / — Tô na correria, sabe? / — Pois é, hein. Me conta... / — Então, aconteceu que...",hint:"tô/tá/pra/cê · né? hein? sabe? tá ligado? · pois é · que situação · acredito não · daí · então"}
        ]
      }
    ]
  },
  {
    id: "B1-U6",
    title: "Mundo do trabalho e vida profissional avançada",
    description: "Comunicar-se com excelência no ambiente profissional",
    lessons: [
      {
        id: "B1-U6-L1",
        title: "Entrevista de emprego em português",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Bom dia! Por favor, fique à vontade. Pode se apresentar?\n— Bom dia! Claro. Meu nome é Ana. Tenho cinco anos de experiência em marketing digital.\n— Ótimo! Por que se interessou por esta vaga?\n— Porque a missão da empresa alinha perfeitamente com meus valores.\n— E quais são seus pontos fortes?\n— Sou muito analítica e trabalho bem sob pressão. Além disso, tenho facilidade para trabalhar em equipe.\n— E algum ponto a melhorar?\n— Às vezes sou excessivamente detalhista. Estou trabalhando nisso para equilibrar qualidade com agilidade.\n— Interessante! Onde você se vê em cinco anos?\n— Liderando uma equipe de marketing e contribuindo estrategicamente para o crescimento da empresa.",
        memoryPhrases: [
          "Tenho X anos de experiência em...",
          "Alinha com meus valores.",
          "Sou analítico/a e comunicativo/a.",
          "Estou trabalhando nisso.",
          "Me vejo liderando..."
        ],
        oralProduction: "SITUAÇÃO ORAL: Simule uma entrevista de emprego completa em português. Apresente-se, responda 5 perguntas clássicas e faça 2 perguntas ao entrevistador. Mínimo 10 falas.",
        content: "# Entrevista de Emprego\n\n## Perguntas clássicas e respostas\n\n'Pode se apresentar?'\n→ Meu nome é... Tenho X anos de experiência em...\nFormei-me em... Atualmente trabalho como...\n\n'Por que esta vaga/empresa?'\n→ Me identifico com a missão/valores da empresa.\nAcredito que posso contribuir com...\n\n'Quais são seus pontos fortes?'\n→ Sou [adjetivo], tenho facilidade para...\nAlém disso, tenho experiência em...\n\n'E pontos a melhorar?'\n→ Às vezes sou [característica]. Estou trabalhando para...\n(Escolha algo real mas que não desqualifique)\n\n'Onde você se vê em 5 anos?'\n→ Me vejo em posição de liderança em...\nGostaria de ter crescido e contribuído para...\n\n## Vocabulário de entrevista\nCurrículo = CV/currículum\nExperiência profissional · Formação acadêmica\nHabilidades técnicas = hard skills\nCompetências comportamentais = soft skills\nPretensão salarial = pretensión salarial\nDisponibilidade = disponibilidad\nPrazo para decisão = plazo para decidir\n\n## Perguntas para fazer ao entrevistador\nComo é a cultura da empresa?\nQuais são os maiores desafios da vaga?\nComo seria meu primeiro mês?",
        exercises: [
          {id:"B1-U6-L1-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo respondés 'por que se interessou por esta vaga?' de forma profesional?",options:["Porque preciso de dinheiro.","Me identifico com a missão da empresa e acredito que posso contribuir.","Porque é perto de casa.","Porque vi o anúncio."],answer:1,explanation:"Respuesta profesional: alinear valores personales con la misión de la empresa y mencionar contribución.",hint:"La respuesta debe mencionar valores, missão y sua contribuição"},
          {id:"B1-U6-L1-E2",type:"fill_blank",skill:"vocabulary",question:"'Minha ___ salarial é de X reais por mês.' (pretensión salarial)",answer:["pretensão"],hint:"El valor que esperas ganar en el trabajo",explanation:"Pretensão salarial = pretensión salarial. Lo que esperas recibir de salario."},
          {id:"B1-U6-L1-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál punto a mejorar es más apropiado para una entrevista?",options:["Sou muito preguiçoso.","Às vezes sou detalhista demais e estou trabalhando para equilibrar qualidade e agilidade.","Não gosto de trabalhar em equipe.","Tenho dificuldade com prazos."],answer:1,explanation:"La respuesta B transforma un defecto en algo que ya estás trabajando activamente. Honesta pero positiva.",hint:"Un punto real pero que muestra autoconsciencia y mejora activa"},
          {id:"B1-U6-L1-E4",type:"translation",skill:"writing",question:"Traduce esta respuesta de entrevista: 'Tengo 5 años de experiencia en marketing. Me formé en Comunicación y actualmente lidero un equipo de 4 personas.'",answer:["tenho cinco anos de experiência em marketing","me formei em comunicação","e atualmente lidero uma equipe de quatro pessoas"],hint:"tenho cinco anos de experiência · me formei em · atualmente lidero",explanation:"Tenho cinco anos de experiência em marketing. Me formei em Comunicação e atualmente lidero uma equipe de quatro pessoas."},
          {id:"B1-U6-L1-E5",type:"free_writing",skill:"writing",question:"Escreva suas respostas completas para as 5 perguntas clássicas de entrevista. Seja específico/a com exemplos reais da sua área. Mínimo 12 orações no total.",prompt:"1. Apresentação: Meu nome é... / 2. Por que a vaga: Me identifico... / 3. Pontos fortes: Sou... / 4. Ponto a melhorar: Às vezes... / 5. 5 anos: Me vejo...",hint:"específico · exemplos reais · linguagem formal · pontos fortes com evidência · ponto a melhorar com ação"}
        ]
      },
      {
        id: "B1-U6-L2",
        title: "Negociação e persuasão profissional",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Gostaria de discutir meu salário após 18 meses na empresa.\n— Claro. Pode apresentar sua proposta?\n— Com base no meu desempenho e nas responsabilidades assumidas, proponho um ajuste de 20%.\n— É uma solicitação significativa. Pode justificar com dados?\n— Claro. Entreguei todos os projetos dentro do prazo. Aumentei a carteira em 35%.\n— Esses números são impressionantes. No entanto, o orçamento é limitado.\n— Entendo a restrição. Poderia considerar 15% com revisão em seis meses?\n— Isso parece mais viável. Posso levar à diretoria.\n— Agradeço a abertura para o diálogo. Fico aguardando.",
        memoryPhrases: [
          "Com base no meu desempenho...",
          "Proponho um ajuste de...",
          "Pode justificar com dados?",
          "Poderia considerar...?",
          "Fico aguardando sua resposta."
        ],
        oralProduction: "SITUAÇÃO ORAL: Negocie um aumento de salário ou uma melhoria nas condições de trabalho. Use dados, seja firme mas flexível, e chegue a um acordo. Mínimo 10 falas.",
        content: "# Negociação Profissional\n\n## Princípios da boa negociação\n1. Preparação: Tenha dados concretos\n2. Ancoragem: Comece com valor mais alto\n3. Justificativa: Sempre explique sua proposta\n4. Flexibilidade: Tenha um plano B\n5. ZOPA: Zona de possível acordo\n\n## Apresentar proposta\nCom base em... · Considerando que...\nDada a minha contribuição para...\nProponho que... · Gostaria de negociar...\nMinha proposta é de...\n\n## Justificar com dados\nNos últimos X meses, entreguei...\nResultados concretos: crescimento de X%...\nFui responsável por...\nContribuí para...\n\n## Lidar com objeções\nEntendo a restrição, no entanto...\nPoderia considerar uma alternativa?\nE se fizéssemos...?\nQue tal...?\n\n## Fechar o acordo\nParece justo para ambos os lados?\nPodemos formalizar em...?\nFico aguardando a confirmação.\nAgradecido/a pela abertura ao diálogo.\n\n## Vocabulário de negociação\nproposta = propuesta · contraproposta = contrapropuesta\nconcessão = concesión · impasse = impasse\nakordo = acuerdo · cláusula = cláusula\nnegociar de boa-fé = negociar de buena fe",
        exercises: [
          {id:"B1-U6-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la forma más profesional de introducir una propuesta de aumento?",options:["Quero ganhar mais.","Com base no meu desempenho e nas responsabilidades assumidas, proponho...","Me dê um aumento ou saio.","Faz tempo que não ganho mais."],answer:1,explanation:"COM BASE EM + datos + PROPONHO = forma profesional. Justificación + propuesta concreta.",hint:"Justificación datos + propuesta formal"},
          {id:"B1-U6-L2-E2",type:"fill_blank",skill:"vocabulary",question:"'Entendo a restrição orçamentária. ___ considerar um ajuste menor com revisão em seis meses?' (Podría — alternativa flexible)",answer:["poderia","você poderia"],hint:"Alternativa flexible: PODERIA + infinitivo",explanation:"PODERIA CONSIDERAR = ¿Podría considerar? Alternativa flexible usando el condicional."},
          {id:"B1-U6-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué significa 'ancoragem' en el contexto de negociación?",options:["Fijar el barco","Comenzar con un valor más alto para tener margen de negociación","Cerrar el trato rápido","Aceptar la primera propuesta"],answer:1,explanation:"Ancoragem = ancla en negociación. Comenzar con valor más alto para tener margen de concesión.",hint:"La estrategia de comenzar alto para bajar"},
          {id:"B1-U6-L2-E4",type:"translation",skill:"writing",question:"Traduce profesionalmente: 'En base a los resultados del último año, donde incrementé las ventas en un 35%, propongo un ajuste salarial del 20%.'",answer:["com base nos resultados do último ano onde aumentei as vendas em trinta e cinco por cento","proponho um ajuste salarial de vinte por cento"],hint:"com base nos resultados · onde aumentei as vendas · proponho um ajuste salarial de",explanation:"Com base nos resultados do último ano, onde aumentei as vendas em 35%, proponho um ajuste salarial de 20%."},
          {id:"B1-U6-L2-E5",type:"free_writing",skill:"writing",question:"Escreva um diálogo de negociação salarial completo: proposta inicial, objeção, contraproposta e fechamento de acordo. Use dados inventados mas plausíveis. Mínimo 12 falas.",prompt:"A: Gostaria de discutir... / B: Claro. Pode apresentar? / A: Com base em... / B: Entendo, no entanto... / A: Poderia considerar...? / B: Parece razoável...",hint:"dados concretos · proposta inicial alta · justificativa · objeção do outro · flexibilidade · fechamento"}
        ]
      },
      {
        id: "B1-U6-L3",
        title: "Feedback e avaliação profissional",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Tenho um feedback para compartilhar com você.\n— Pode falar, estou aberto.\n— No geral, seu desempenho foi excelente este trimestre.\n— Que bom! Fico feliz em saber disso.\n— Há um ponto, no entanto, que gostaria de abordar.\n— Diga. Estou aberto a críticas construtivas.\n— Percebi que às vezes você deixa reuniões sem um plano de ação claro.\n— Entendo. É uma área que posso melhorar definitivamente.\n— O que você poderia fazer diferente nas próximas reuniões?\n— Poderia sistematizar um resumo com ações e responsáveis ao final de cada encontro.",
        memoryPhrases: [
          "Tenho um feedback para...",
          "Estou aberto a críticas.",
          "É uma área para melhorar.",
          "Percebi que às vezes...",
          "O que você poderia fazer?"
        ],
        oralProduction: "SITUAÇÃO ORAL: Dê e receba feedback profissional. Primeiro dê um feedback positivo e depois um construtivo. Depois troque os papéis. Use linguagem não violenta. Mínimo 10 falas.",
        content: "# Feedback Profissional\n\n## Modelo SBI de feedback\nS = Situation (Situação): Quando/no momento em que...\nB = Behavior (Comportamento): Você fez/disse...\nI = Impact (Impacto): O efeito foi...\n\nExemplo:\n'Na reunião de segunda (S), quando você apresentou os dados sem contexto (B), a equipe ficou confusa (I).'\n\n## Feedback positivo\nQuero destacar seu desempenho em...\nFicou muito bem feito...\nA forma como você tratou... foi exemplar.\nVocê demonstrou grande habilidade em...\n\n## Feedback construtivo\nHá um ponto que gostaria de abordar...\nPercebi que... O impacto foi...\nO que você poderia fazer diferente?\nComo você vê isso?\n\n## Receber feedback\nAgradeço o feedback.\nPode me dar um exemplo concreto?\nEntendo. Como posso melhorar?\nO que você sugere especificamente?\n\n## Vocabulário\nDesempenho = desempeño · Avaliação = evaluación\nMeta = meta · KPI = indicador clave\nMelhoria contínua · Plano de ação\nForças e oportunidades = fortalezas y oportunidades",
        exercises: [
          {id:"B1-U6-L3-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es el modelo de feedback que usa Situação, Comportamento e Impacto?",options:["CNV","SMART","SBI","SWOT"],answer:2,explanation:"SBI = Situação + Comportamento + Impacto. Modelo para dar feedback claro y objetivo.",hint:"Las iniciales de Situação, Comportamento e Impacto"},
          {id:"B1-U6-L3-E2",type:"fill_blank",skill:"vocabulary",question:"'Na reunião de ontem (situação), quando você falou mais alto que todos (comportamento), a equipe ficou desconfortável (___).'",answer:["impacto"],hint:"O resultado do comportamento nas outras pessoas",explanation:"Impacto = el efecto del comportamiento en el equipo. El tercer componente del modelo SBI."},
          {id:"B1-U6-L3-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la mejor forma de RECIBIR feedback construtivo?",options:["Defender-se imediatamente.","Culpar a outra pessoa.","Agradecer e pedir um exemplo concreto para entender melhor.","Ignorar o que foi dito."],answer:2,explanation:"AGRADECER + PEDIR EXEMPLO = forma ideal de receber feedback. Abre o diálogo sin defensividade.",hint:"Receber bem = agradecer + entender + pedir exemplo"},
          {id:"B1-U6-L3-E4",type:"translation",skill:"writing",question:"Traduce usando modelo SBI: 'En la presentación del martes, cuando no tenías los datos actualizados, el cliente perdió la confianza en el proyecto.'",answer:["na apresentação de terça-feira quando você não tinha os dados atualizados o cliente perdeu a confiança no projeto"],hint:"na apresentação de terça · quando não tinha os dados atualizados · o cliente perdeu a confiança",explanation:"Na apresentação de terça-feira (S), quando você não tinha os dados atualizados (B), o cliente perdeu a confiança no projeto (I)."},
          {id:"B1-U6-L3-E5",type:"free_writing",skill:"writing",question:"Escreva dois feedbacks completos usando o modelo SBI: um positivo e um construtivo para um colega de trabalho imaginário. Depois escreva como esse colega deveria responder. Mínimo 10 orações.",prompt:"POSITIVO: Na reunião de... / Quando você... / O impacto foi... / CONSTRUTIVO: Percebi que... / O que aconteceu foi... / Como você poderia...?",hint:"SBI: situação + comportamento + impacto · positivo genuíno · construtivo sem julgar · resposta aberta"}
        ]
      },
      {
        id: "B1-U6-L4",
        title: "Redes profissionais e LinkedIn em português",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você tem LinkedIn em português?\n— Tenho! Mas não sei se está tão bem escrito quanto o inglês.\n— O LinkedIn em português pode abrir muitas portas no Brasil.\n— Você tem razão. Mas como adaptar o perfil?\n— Comece pelo resumo. Precisa ser impactante nas primeiras linhas.\n— E o headline?\n— Seja específico: cargo + especialidade + diferencial.\n— Tipo: 'Especialista em Marketing Digital | Growth Hacking | Resultados com Dados'?\n— Perfeito! E solicite recomendações de colegas e líderes.\n— Ótima dica. Isso passa mais credibilidade.",
        memoryPhrases: [
          "Meu perfil no LinkedIn...",
          "Sou especialista em...",
          "Tenho experiência comprovada em...",
          "Busco oportunidades em...",
          "Possuo habilidades em..."
        ],
        oralProduction: "SITUAÇÃO ORAL: Apresente seu perfil profissional como se fosse o seu summary do LinkedIn. Seja impactante, específico e inclua: área, experiência, habilidades e objetivo. Mínimo 6 frases.",
        content: "# LinkedIn e Networking Profissional\n\n## Headline (título do perfil)\nCargo + Área + Diferencial\nEx: Analista de Dados | Python & BI | Transformando dados em decisões\n\n## Summary (resumo) — estrutura\n1. Quem você é e o que faz (1 frase impactante)\n2. Sua experiência e especializações\n3. Conquistas concretas com números\n4. O que você busca / oferece\n5. CTA: Entre em contato para...\n\n## Vocabulário do LinkedIn\nConexão = conexión · Rede = red\nEndosso = recomendación de habilidad\nRecomendação = carta de recomendación\nVaga = vacante/posición\nRecrutador = reclutador\nAplicar para uma vaga = postularse\n\n## Mensagem de conexão profissional\n'Olá [nome], vi seu perfil e me identifiquei muito com sua trajetória em [área]. Gostaria de conectar para trocar experiências. [Seu nome]'\n\n## Mensagem de networking\n'Trabalho na área de [área] e estaria interessado/a em uma conversa rápida para conhecer mais sobre sua experiência em [empresa/área]. Teria disponibilidade?'\n\n## Habilidades em português\nHabilidades técnicas = hard skills\nCompetências comportamentais = soft skills\nLiderança · Comunicação · Análise\nCriatividade · Resolução de problemas",
        exercises: [
          {id:"B1-U6-L4-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál headline de LinkedIn es más profesional y específico?",options:["Trabalho com marketing","Profissional de marketing","Especialista em Marketing Digital | Growth | ROI com dados","Marketing é minha paixão"],answer:2,explanation:"Cargo específico + área + diferencial con palabras clave = headline profesional y búsqueda efectiva.",hint:"Headline: cargo específico + área + diferencial"},
          {id:"B1-U6-L4-E2",type:"fill_blank",skill:"vocabulary",question:"No LinkedIn, quando um colega confirma que você tem uma habilidade, isso se chama um '___ de competência'.",answer:["endosso"],hint:"La confirmación de habilidades en el LinkedIn se llama...",explanation:"Endosso = recomendación/endorsement de habilidad. Diferente de Recomendação (texto escrito)."},
          {id:"B1-U6-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál mensaje de conexión es más apropiado en LinkedIn?",options:["Oi, me adiciona.","Quero aumentar minha rede.","Olá! Vi seu perfil e me identifiquei com sua trajetória em [área]. Gostaria de conectar.","Adicione-me, por favor."],answer:2,explanation:"Mensagem personalizada com referência específica ao perfil = mais professional e com maior aceite.",hint:"Mensagem personalizada sempre tem melhor resultado"},
          {id:"B1-U6-L4-E4",type:"translation",skill:"writing",question:"Traduce este headline de LinkedIn: 'Especialista en Recursos Humanos | Gestión del Talento | Diversidad e Inclusión'",answer:["especialista em recursos humanos","gestão de talentos","diversidade e inclusão"],hint:"especialista em · recursos humanos · gestão de talentos · diversidade e inclusão",explanation:"Especialista em Recursos Humanos | Gestão de Talentos | Diversidade e Inclusão"},
          {id:"B1-U6-L4-E5",type:"free_writing",skill:"writing",question:"Escreva seu perfil completo do LinkedIn em português: headline, summary (5 frases) e uma mensagem de networking para alguém da sua área. Seja específico com sua área real.",prompt:"HEADLINE: [Cargo] | [Área] | [Diferencial]\nSUMMARY: Sou... / Tenho X anos de experiência em... / Conquistei... / Busco...\nNETWORKING: Olá [nome], vi seu perfil e...",hint:"headline específico · summary impactante com números · mensagem personalizada de networking"}
        ]
      },
      {
        id: "B1-U6-L5",
        title: "Revisão B1 — Unidades 5 e 6",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você se sente preparado para trabalhar em português?\n— Me sinto bem mais confiante. Posso me comunicar em várias situações.\n— E entrevista de emprego? Já simulou?\n— Já sim! Preparei meu discurso e pratiquei as perguntas clássicas.\n— E a escrita? Você consegue escrever formalmente?\n— Consigo! Aprendi as estruturas de email, relatório e feedback.\n— Impressionante! Quanto você evoluiu.\n— O mérito é da prática constante. Escrever todo dia faz diferença.\n— E o que ainda quer melhorar?\n— Minha oralidade informal. Ainda penso demais antes de falar.",
        memoryPhrases: [
          "Me sinto mais confiante.",
          "Consigo me comunicar.",
          "Preparei meu discurso.",
          "A prática faz diferença.",
          "Ainda quero melhorar..."
        ],
        oralProduction: "SITUAÇÃO ORAL: Faça uma autopresentação profissional completa em português como se fosse uma entrevista de emprego real. Use tudo que aprendeu nas U5-U6. Mínimo 10 frases.",
        content: "# Revisão B1 — Unidades 5 e 6\n\n## Narrativa avançada\n✅ Técnicas de storytelling: gancho, tensão, clímax, transformação\n✅ Análise literária: narrador, personagens, temas, simbolismo\n✅ Poesia e expressão lírica: metáfora, ritmo, imagem\n✅ Crônica e conto: gêneros literários brasileiros\n✅ Oralidade: contrações, marcadores, ritmo real\n\n## Vida profissional\n✅ Entrevista de emprego: perguntas clássicas e respostas\n✅ Negociação: proposta, justificativa, concessão, fechamento\n✅ Feedback SBI: situação, comportamento, impacto\n✅ LinkedIn: headline, summary, networking\n✅ Comunicação formal e informal adequada ao contexto\n\n## Integração linguística B1\n✅ Subjuntivo em todos os contextos\n✅ Voz passiva (todos os tempos)\n✅ Discurso indireto com mudanças\n✅ Verbos com preposição\n✅ Gerúndio + infinitivo pessoal\n✅ Debate e argumentação estruturada\n✅ Registros formal e informal",
        exercises: [
          {id:"B1-U6-L5-E1",type:"multiple_choice",skill:"grammar",question:"REVISÃO — ¿Cuál usa subjuntivo IMPERFEITO correctamente?",options:["Se eu tiver dinheiro, viajarei.","Se eu tivesse dinheiro, viajaria.","Se eu tinha dinheiro, viajaria.","Se eu terei dinheiro, viajo."],answer:1,explanation:"Hipótese irreal: SE + imperfeito do subjuntivo TIVESSE + condicional VIAJARIA.",hint:"Hipótese irreal: SE + subj imperfeito + condicional"},
          {id:"B1-U6-L5-E2",type:"fill_blank",skill:"grammar",question:"REVISÃO DISCURSO INDIRETO: 'Vou terminar isso hoje.' → Ele disse que ___ terminar isso naquele dia.",answer:["ia","iria"],hint:"Futuro (vou) → condicional (ia/iria) no discurso indireto",explanation:"'Vou' → ia/iria no discurso indireto. 'Hoje' → naquele dia."},
          {id:"B1-U6-L5-E3",type:"multiple_choice",skill:"vocabulary",question:"REVISÃO — ¿Cuál describe mejor el modelo SBI de feedback?",options:["Salário, Benefícios, Incentivo","Situação, Comportamento, Impacto","Strengths, Behaviors, Improvements","Sistema, Base, Implementação"],answer:1,explanation:"SBI = Situação + Comportamento + Impacto. Modelo para dar feedback claro y específico.",hint:"SBI: as três palavras que compõem o modelo"},
          {id:"B1-U6-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'Si tuviera más experiencia, aplicaría para esa posición. Aunque no sea lo ideal, voy a intentarlo igual.'",answer:["se eu tivesse mais experiência aplicaria para essa vaga","embora não seja o ideal vou tentar mesmo assim"],hint:"se tivesse (subj imperf) · aplicaria (condicional) · embora não seja (subj pres) · mesmo assim",explanation:"Se eu tivesse mais experiência, aplicaria para essa vaga. Embora não seja o ideal, vou tentar mesmo assim."},
          {id:"B1-U6-L5-E5",type:"free_writing",skill:"writing",question:"TEXTO INTEGRADO FINAL B1: Escreva uma carta de apresentação profissional completa para uma vaga dos sonhos. Use: registro formal, subjuntivo, voz passiva, argumentação e vocabulário profissional. Mínimo 14 orações.",prompt:"Prezado/a [nome],\nVenho por meio desta apresentar minha candidatura... / Tenho X anos de experiência... / Os resultados que obtive... / Acredito que posso contribuir... / Espero que minha candidatura seja considerada...\nAtenciosamente, [nome]",hint:"formal · voz passiva · subjuntivo · dados concretos · argumentação · encerramento adequado"}
        ]
      }
    ]
  },
  {
    id: "B1-U7",
    title: "Português do Brasil — variações e riqueza",
    description: "Dominar as variedades do português e o Brasil em profundidade",
    lessons: [
      {
        id: "B1-U7-L1",
        title: "Vocabulário temático avançado — natureza e ecologia",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você sabia que o Brasil tem 6 biomas diferentes?\n— Sei! A Amazônia é o mais famoso, mas o Cerrado é igualmente importante.\n— E a Caatinga? Muita gente esquece dela.\n— É verdade. A Caatinga é o único bioma exclusivamente brasileiro.\n— E está muito ameaçado pelo desmatamento e pela seca.\n— Exatamente. As mudanças climáticas afetam a Caatinga de forma brutal.\n— E o Pantanal? Vejo muito na mídia internacional.\n— O Pantanal é a maior área úmida do mundo. Em 2020, queimou muito.\n— Que tragédia! Precisamos de ações urgentes de preservação.",
        memoryPhrases: [
          "O Brasil tem 6 biomas.",
          "A Amazônia é o pulmão.",
          "A Caatinga é exclusiva do Brasil.",
          "O Pantanal é área úmida.",
          "Precisamos preservar urgente."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique para alguém os biomas brasileiros e a importância ecológica de cada um. Mencione ameaças e propostas de conservação. Mínimo 8 frases.",
        content: "# Os Biomas Brasileiros\n\n## Os 6 biomas do Brasil\n1. AMAZÔNIA: 49% do Brasil. Maior floresta tropical do mundo.\n   biodiversidade · rios · povos indígenas · desmatamento\n\n2. CERRADO: 21% do Brasil. 'Savana brasileira'.\n   Nascentes de rios importantes · berço das águas\n   Muito ameaçado pela agropecuária\n\n3. MATA ATLÂNTICA: 15% original, hoje só 12-15% restante!\n   Costa brasileira · alta biodiversidade · muito fragmentada\n\n4. CAATINGA: Único bioma 100% brasileiro!\n   Semiárido nordestino · adaptação à seca\n   Cactáceas · mandacaru · imbu\n\n5. PANTANAL: Maior área úmida do mundo\n   Mato Grosso e MS · onças pintadas · tuiuiú\n   Queimadas de 2020 destruíram 26% do bioma\n\n6. PAMPA: Sul do Brasil · campos gaúchos\n   Biodiversidade de gramíneas · pecuária\n\n## Vocabulário ambiental avançado\nBiodiversidade = biodiversidad · Ecossistema\nEspécie endêmica = especie endémica (só existe aqui)\nFauna = fauna · Flora = flora · Habitat\nDesflorestamento · Queimada · Erosão\nReflorestamento · Área de preservação permanente (APP)\nDesertificação · Salinização do solo",
        exercises: [
          {id:"B1-U7-L1-E1",type:"multiple_choice",skill:"culture",question:"¿Cuál es el único bioma 100% exclusivo del Brasil?",options:["Amazônia","Cerrado","Caatinga","Pampa"],answer:2,explanation:"A Caatinga é o único bioma exclusivamente brasileiro. Semiárido nordestino com fauna e flora únicas.",hint:"El bioma que solo existe en Brasil"},
          {id:"B1-U7-L1-E2",type:"fill_blank",skill:"vocabulary",question:"O Pantanal é considerado a maior área ___ do mundo, lar de onças pintadas e tuiuiús.",answer:["úmida"],hint:"Área de muita água e charcos",explanation:"Área úmida = humedal. O Pantanal é a maior área úmida do planeta."},
          {id:"B1-U7-L1-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo se llama una especie que SOLO existe en un lugar determinado?",options:["Migratória","Invasora","Endêmica","Extinta"],answer:2,explanation:"Espécie endêmica = espécie que SOLO existe en ese lugar. Muchas endêmicas en la Amazônia.",hint:"Espécie que só existe num lugar específico"},
          {id:"B1-U7-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'El Cerrado es conocido como la cuna de las aguas de Brasil. Sus nacientes alimentan los principales ríos del país. Está muy amenazado por la agricultura.'",answer:["o cerrado é conhecido como o berço das águas do brasil","suas nascentes alimentam os principais rios do país","está muito ameaçado pela agropecuária"],hint:"berço das águas · nascentes · alimentam os rios · ameaçado pela agropecuária",explanation:"O Cerrado é conhecido como o berço das águas do Brasil. Suas nascentes alimentam os principais rios do país. Está muito ameaçado pela agropecuária."},
          {id:"B1-U7-L1-E5",type:"free_writing",skill:"writing",question:"Escreva um texto argumentativo sobre a importância de preservar um bioma brasileiro específico. Inclua: características, importância, ameaças e propostas de solução. Mínimo 10 orações.",prompt:"O bioma que escolho é... / Suas características são... / A importância ecológica é... / As principais ameaças são... / Para preservá-lo, é essencial que...",hint:"bioma escolhido · características · importância · ameaças · soluções com subjuntivo"}
        ]
      },
      {
        id: "B1-U7-L2",
        title: "Gastronomia e culinária — vocabulário avançado",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você já fez algum prato brasileiro do zero?\n— Fiz! Tentei fazer moqueca. Foi uma aventura.\n— E como ficou?\n— Ficou bem, mas o azeite de dendê foi difícil de encontrar aqui fora.\n— Substitui por quê?\n— Por azeite comum. Mas perdeu muito o sabor original.\n— Faz sentido. O dendê é insubstituível na moqueca baiana.\n— Aprendi isso na prática! E você cozinha muito?\n— Cozinho bastante. Adoro fazer comida mineira.\n— Que inveja! Um feijão tropeiro bem feito é imbatível.",
        memoryPhrases: [
          "Fiz do zero!",
          "Foi uma aventura culinária.",
          "Perdeu o sabor original.",
          "É insubstituível na receita.",
          "Um prato bem feito é imbatível."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique como se faz um prato típico (brasileiro ou do seu país) com detalhes de ingredientes, modo de preparo e dicas. Use vocabulário culinário. Mínimo 8 frases.",
        content: "# Culinária Avançada — Vocabulário\n\n## Técnicas culinárias\nrefogar = sofreír · fritar = freír · grelhar = asar a la plancha\nassar = hornear/asar · cozinhar = cocer · ferver = hervir\nmarinár = marinar · temperar = condimentar\nchamuscar = quemar superficialmente\npicár = picar · fatiár = cortar en láminas · ralar = rallar\npeneirar = tamizar · bater = batir · misturar = mezclar\n\n## Equipamentos\npanela = olla · frigideira = sartén\nforma = molde/bandeja de horno\nescorredor = escurridor · tábua de corte = tabla de cortar\nconcha = cucharón · espátula = espátula\nforno = horno · fogão = cocina/estufa\n\n## Ingredientes específicos\nazeite de dendê = aceite de palma (para moqueca baiana)\nleite de coco = leche de coco · cebola = cebolla\nalho = ajo · coentro = cilantro\npimentão = pimiento/morron · cheiro-verde = cilantro+cebolinha\nfarofa = harina de mandioca tostada (acompaña feijoada)\nbrigadeiro = bombón de chocolate condensado (postre)\n\n## Receita — estrutura\nIngredientes: + lista\nModo de preparo: imperativos (refogue, adicione, misture)\nDica: + consejo\nRende: X porções",
        exercises: [
          {id:"B1-U7-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Qué técnica culinaria significa 'cocinar suavemente en aceite con cebolla y ajo'?",options:["Ferver","Refogar","Assar","Grelhar"],answer:1,explanation:"REFOGAR = sofreír. La técnica base de la mayoría de los pratos brasileños.",hint:"La técnica con aceite, cebola e alho no começo da maioria das receitas"},
          {id:"B1-U7-L2-E2",type:"fill_blank",skill:"vocabulary",question:"'A farofa acompanha a feijoada. É feita com farinha de ___ tostada na manteiga.'",answer:["mandioca"],hint:"O tubérculo mais importante da culinária brasileira",explanation:"Farinha de mandioca = harina de yuca. La farofa es el acompañamiento clásico de la feijoada."},
          {id:"B1-U7-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué es un 'brigadeiro'?",options:["Un condimento picante","Un tipo de cachaça","Un bombón de chocolate condensado típico brasileiro","Un prato de carne"],answer:2,explanation:"Brigadeiro = bombón de leche condensada con chocolate. EL postre más amado de Brasil.",hint:"El dulce de fiesta de cumpleaños más famoso do Brasil"},
          {id:"B1-U7-L2-E4",type:"translation",skill:"writing",question:"Traduce esta instrucción de receta: 'Primero, sofreí la cebolla y el ajo. Después, agregá el tomate y el pimiento. Dejá hervir por 15 minutos.'",answer:["primeiro refogue a cebola e o alho","depois adicione o tomate e o pimentão","deixe ferver por quinze minutos"],hint:"refogue · adicione · o tomate e o pimentão · deixe ferver por · minutos",explanation:"Primeiro, refogue a cebola e o alho. Depois, adicione o tomate e o pimentão. Deixe ferver por 15 minutos."},
          {id:"B1-U7-L2-E5",type:"free_writing",skill:"writing",question:"Escreva uma receita completa de um prato que você sabe fazer: ingredientes, modo de preparo passo a passo, dica especial e para quantas pessoas rende. Mínimo 10 orações.",prompt:"INGREDIENTES: ... / MODO DE PREPARO: Primeiro, refogue... / Em seguida... / Adicione... / Deixe... / DICA: ... / Rende: X porções",hint:"refogue · adicione · misture · deixe ferver · tempere · ingredientes específicos com quantidades"}
        ]
      },
      {
        id: "B1-U7-L3",
        title: "Festividades e celebrações brasileiras",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você já participou de alguma festa brasileira?\n— Ainda não! Mas estou planejando ir ao Brasil no Carnaval.\n— Vai ser uma experiência inesquecível!\n— Qual é o melhor lugar para o Carnaval?\n— Depende do que você quer. Rio é o mais famoso, mas Salvador tem um espírito diferente.\n— Como assim?\n— No Rio, o mais icônico são os desfiles das escolas de samba no Sambódromo.\n— E em Salvador?\n— É a micareta! Axé e trios elétricos pelas ruas. Muito mais democrático e participativo.\n— Que difícil escolher! E a Festa Junina?\n— Completamente diferente do Carnaval. Mais familiar, comida típica, forró, quadrilha.",
        memoryPhrases: [
          "O Carnaval é inesquecível!",
          "O Sambódromo é icônico.",
          "A micareta é democrática.",
          "A Festa Junina tem forró.",
          "Cada festa tem seu espírito."
        ],
        oralProduction: "SITUAÇÃO ORAL: Descreva uma festa ou celebração que você conhece (brasileira ou do seu país) para alguém que nunca foi. Descreva o ambiente, as tradições, a comida e o que o torna especial. Mínimo 8 frases.",
        content: "# Festividades Brasileiras\n\n## Carnaval\nPeríodo: fevereiro/março (antes da Quaresma)\nRio de Janeiro: Sambódromo + blocos de rua\nSalvador: Micareta com trios elétricos (axé)\nRecife/Olinda: Frevo, bonecos gigantes, maracatu\nSão Paulo: Cada vez maior, sambódromo do Anhembi\nMatas Gerais: Carnaval das ruas em BH e Ouro Preto\n\n## Festa Junina (Junho)\nSanto Antônio, São João, São Pedro\nForró e quadrilha (dança típica)\nComida típica: pamonha, canjica, milho, pé-de-moleque\nRoupa típica: xadrez, chapéu de palha, vestido rodado\nMais forte no Nordeste (Campina Grande = maior do mundo)\n\n## Outras festas importantes\nSemana Santa = Semana Santa\nFesta do Divino = tradição colonial\nBoi-Bumbá = Parintins (Amazonas), junho\nFesta da Uva = Caxias do Sul (RS), influência italiana\nCarnapauxis = Fiestas menores por el Brasil\n\n## Vocabulário de festas\nbloco = agrupación de carnaval · trio elétrico = camión con música\nquadrilha = danza típica junina · frevo = danza pernambucana\nescola de samba · samba-enredo · bateria\nfantasia = disfraz · serpentina = serpentina\nalegoria = carroza · desfile = desfile",
        exercises: [
          {id:"B1-U7-L3-E1",type:"multiple_choice",skill:"culture",question:"¿Qué es la 'micareta' en el contexto del Carnaval de Salvador?",options:["El desfile de escolas de samba","El carnaval con tríos eléctricos y axé por las calles","Las competencias de frevo","El Carnaval de Recife"],answer:1,explanation:"Micareta = el Carnaval de Salvador con tríos eléctricos y axé. Más democrático y participativo que el Sambódromo.",hint:"El Carnaval de Salvador con tríos elétricos"},
          {id:"B1-U7-L3-E2",type:"fill_blank",skill:"culture",question:"A maior Festa Junina do mundo acontece em Campina Grande, no estado da ___.",answer:["paraíba","Paraíba"],hint:"O estado nordestino famoso pela Festa Junina",explanation:"Campina Grande, Paraíba = sede da maior Festa Junina do mundo."},
          {id:"B1-U7-L3-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo se llama el disfraz en el contexto del Carnaval brasileño?",options:["Fantasia","Roupa","Vestimenta","Máscara"],answer:0,explanation:"FANTASIA = disfraz en Brasil. No es lo mismo que fantasía (imaginación).",hint:"El traje/disfraz del carnaval en português"},
          {id:"B1-U7-L3-E4",type:"translation",skill:"writing",question:"Traduce: 'El Carnaval de Rio de Janeiro es famoso en todo el mundo. Los desfiles de las escuelas de samba en el Sambódromo son un espectáculo increíble.'",answer:["o carnaval do rio de janeiro é famoso no mundo todo","os desfiles das escolas de samba no sambódromo são um espetáculo incrível"],hint:"famoso no mundo todo · desfiles das escolas de samba · sambódromo · espetáculo incrível",explanation:"O Carnaval do Rio de Janeiro é famoso no mundo todo. Os desfiles das escolas de samba no Sambódromo são um espetáculo incrível."},
          {id:"B1-U7-L3-E5",type:"free_writing",skill:"writing",question:"Compare o Carnaval brasileiro com uma festa do seu país. Descreva: origens, tradições, comida, música, o que é diferente e o que é parecido. Dê sua opinião. Mínimo 10 orações.",prompt:"No Brasil o Carnaval... / No meu país... / A diferença principal é... / O que os dois têm em comum é... / Na minha opinião...",hint:"carnaval · comparação · tradições · comida · música · diferenças · semelhanças · opinião pessoal"}
        ]
      },
      {
        id: "B1-U7-L4",
        title: "Saúde mental e bem-estar integral",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Como você cuida da sua saúde mental?\n— Faço terapia há dois anos. Foi uma das melhores decisões da minha vida.\n— Que ótimo! No Brasil a terapia está mais acessível agora?\n— Um pouco. O CFP regulamentou o atendimento online, o que ajudou muito.\n— E fora da terapia?\n— Medito, faço exercício e cuido da minha alimentação.\n— Muito bem! O burnout é real, né?\n— Muito real. A pandemia mostrou como a saúde mental importa.\n— E o estigma? As pessoas falam mais abertamente agora?\n— Falam sim! A geração Z e os millennials normalizaram buscar ajuda.\n— É uma mudança cultural importante.",
        memoryPhrases: [
          "Faço terapia há dois anos.",
          "O burnout é real.",
          "Cuido da minha saúde mental.",
          "Normalizamos buscar ajuda.",
          "A saúde mental importa."
        ],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre como você cuida da sua saúde mental. O que funciona para você? O que Brasil aprendeu sobre o tema? Mínimo 7 frases.",
        content: "# Saúde Mental e Bem-Estar\n\n## O cenário no Brasil\nBrasil é um dos países com mais pessoas em terapia\nCFP = Conselho Federal de Psicologia\nCVV = Centro de Valorização da Vida (crise: 188)\nCAPSI = saúde mental infantojuvenil\nSUS tem serviços de saúde mental (CAPS)\n\n## Condições e termos\nburnout = síndrome do esgotamento profissional\nansiedade = ansiedad · depressão = depresión\ntranstorno de pânico = trastorno de pánico\nfobia = fobia · TOC = TOC\ntrauma = trauma · TEPT = TEPT\nautoestima = autoestima · resiliência = resiliencia\n\n## Práticas de bem-estar\nterapia (psicoterapia) · psicólogo vs. psiquiatra\nmeditação = meditación · mindfulness\nexercício físico · sono de qualidade\nalimentação equilibrada · conexões sociais\ndiário de gratidão · tempo na natureza\n\n## Vocabulário emocional avançado\nesgotamento = agotamiento · exaustão = exhaustion\noverwhelm = sobrecarga · crise de ansiedade\nataques de pânico · pensamentos intrusivos\nautocuidado = autocuidado · autocompaixão\n\n## Frases de apoio\nVocê não está sozinho/a.\nBuscar ajuda é sinal de força, não de fraqueza.\nEstá tudo bem não estar bem.",
        exercises: [
          {id:"B1-U7-L4-E1",type:"multiple_choice",skill:"culture",question:"¿Cuál es el número de crisis de salud mental en Brasil similar al 911?",options:["190","192","188","197"],answer:2,explanation:"188 = CVV (Centro de Valorização da Vida). Apoio emocional e prevenção do suicídio 24h.",hint:"O número do CVV para situações de crise emocional"},
          {id:"B1-U7-L4-E2",type:"fill_blank",skill:"vocabulary",question:"'O ___ é o esgotamento profissional causado por excesso de trabalho e estresse crônico.'",answer:["burnout"],hint:"A síndrome do esgotamento profissional",explanation:"Burnout = síndrome de esgotamento profissional. Muito comum no Brasil, especialmente pós-pandemia."},
          {id:"B1-U7-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase es un buen mensaje de apoyo para alguien en dificultad emocional?",options:["Você precisa se esforçar mais.","Isso é frescura sua.","Você não está sozinho/a. Buscar ajuda é sinal de força.","Todo mundo passa por isso, não é nada."],answer:2,explanation:"'Você não está sozinho/a. Buscar ajuda é sinal de força' = mensagem de apoio real, sin minimizar.",hint:"Mensagem de apoio genuína, sem minimizar o sofrimento"},
          {id:"B1-U7-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'El burnout es un problema serio en Brasil. Muchas personas buscan terapia hoy. Es fundamental que las empresas cuiden la salud mental de sus empleados.'",answer:["o burnout é um problema sério no brasil","muitas pessoas buscam terapia hoje","é fundamental que as empresas cuidem da saúde mental de seus funcionários"],hint:"burnout · problema sério · buscam terapia · é fundamental que cuidem (subjuntivo)",explanation:"O burnout é um problema sério no Brasil. Muitas pessoas buscam terapia hoje. É fundamental que as empresas cuidem da saúde mental de seus funcionários."},
          {id:"B1-U7-L4-E5",type:"free_writing",skill:"writing",question:"Escreva sobre como você cuida da sua saúde mental e o que você faria diferente se pudesse mudar sua rotina. Inclua práticas, desafios e sua perspectiva sobre o tema no seu país e no Brasil. Mínimo 10 orações.",prompt:"Para cuidar da minha saúde mental... / O que mais me ajuda é... / Se eu pudesse mudar... / No Brasil, as pessoas... / Acredito que é importante que...",hint:"hábitos de autocuidado · condicional se pudesse · comparação com brasil · subjuntivo em recomendações"}
        ]
      },
      {
        id: "B1-U7-L5",
        title: "Tecnologia e inovação no Brasil",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você sabia que o Brasil tem um ecossistema de startups muito forte?\n— Sabia! São Paulo é o principal hub de inovação da América Latina.\n— E como isso se compara com outros países?\n— O Pix é um exemplo incrível. Pagamento instantâneo 24h, gratuito.\n— É mesmo impressionante. Em muitos países ainda não existe nada assim.\n— O Brasil saltou etapas. Passou do dinheiro vivo direto para o digital.\n— E as fintechs? Nubank foi pioneira.\n— Pioneira e hoje é o maior banco digital do mundo fora da Ásia.\n— Incrível! A inovação brasileira surpreende muito.\n— Muito! Quando você alinha necessidade, criatividade e escala, acontece magia.",
        memoryPhrases: [
          "O Brasil é hub de inovação.",
          "O Pix é revolucionário.",
          "Saltamos etapas tecnológicas.",
          "As fintechs cresceram muito.",
          "Criatividade + escala = magia."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique para alguém do seu país como o Pix funciona e por que é revolucionário. Compare com o sistema financeiro do seu país. Mínimo 7 frases.",
        content: "# Tecnologia e Inovação no Brasil\n\n## O ecossistema tech brasileiro\nSão Paulo = Silicon Valley brasileira\nABStartups = maior ecossistema da América Latina\nNubank = maior fintech do mundo fora da Ásia\nifood = líder em delivery de comida\n99/Uber = ride sharing\nTotvs · CI&T · Movile = tech companies\n\n## O Pix\nLançado em novembro de 2020 pelo Banco Central\nTransferência instantânea 24h, 7 dias, gratuita\nChave Pix = CPF, email, telefone, chave aleatória\nQR Code para pagamentos\nRevolucionou pagamentos e inclusão financeira\n\n## Fintech revolution\nNubank, Inter, C6 Bank = bancos digitais\nMercado Pago, PicPay = carteiras digitais\nSem agência física · Sem anuidade de cartão\nInicio processo: abrir conta pelo celular em minutos\n\n## Agro-tech\nBrasil = líder mundial em agrotecnologia\nEmbrapa = pesquisa agropecuária de ponta\nDrones · Satélites · IA na agricultura\n\n## Vocabulário de tecnologia\nEcossistema = ecosistema · Hub = hub\nStartup · Unicórnio = startup valuada em +1 bilhão\nInvestidor anjo = ángel investor\nIPO · Venture capital · Escalar = escalar",
        exercises: [
          {id:"B1-U7-L5-E1",type:"multiple_choice",skill:"culture",question:"¿Qué es el 'Pix' en Brasil?",options:["Una red social","Una marca de cerveza","Un sistema de pago instantáneo 24h creado por el Banco Central","Un programa de televisión"],answer:2,explanation:"Pix = sistema de pagamento instantâneo 24/7, gratuito, criado pelo Banco Central em 2020. Revolucionou o Brasil.",hint:"El sistema de pago instantáneo que revolucionó el Brasil"},
          {id:"B1-U7-L5-E2",type:"fill_blank",skill:"culture",question:"O Nubank é considerado a maior ___ do mundo fora da Ásia.",answer:["fintech","banco digital"],hint:"O tipo de empresa financeira digital que o Nubank representa",explanation:"Nubank = maior fintech (empresa tecnológica financeira) do mundo fora da Ásia."},
          {id:"B1-U7-L5-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es el significado de 'unicórnio' en el contexto tech?",options:["Una empresa de fantasía","Una startup valuada em más de 1 billón de dólares","Un inversor ángel","Una empresa que quebró"],answer:1,explanation:"Unicórnio tech = startup valuada em +1 bilhão de dólares. Rara como un unicórnio.",hint:"Una startup muy valiosa — rara como el animal mítico"},
          {id:"B1-U7-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'Brasil tiene uno de los ecosistemas de startups más dinámicos de América Latina. El Pix democratizó el acceso a pagamentos digitales para millones de brasileños.'",answer:["o brasil tem um dos ecossistemas de startups mais dinâmicos da américa latina","o pix democratizou o acesso a pagamentos digitais para milhões de brasileiros"],hint:"ecossistema de startups · mais dinâmicos · o pix democratizou · acesso a pagamentos digitais · milhões",explanation:"O Brasil tem um dos ecossistemas de startups mais dinâmicos da América Latina. O Pix democratizou o acesso a pagamentos digitais para milhões de brasileiros."},
          {id:"B1-U7-L5-E5",type:"free_writing",skill:"writing",question:"Escreva sobre como a tecnologia mudou sua vida cotidiana e como você vê o futuro da inovação no Brasil e no seu país. Use vocabulário tech e estruturas do B1. Mínimo 10 orações.",prompt:"A tecnologia mudou minha vida quando... / Atualmente uso... / No Brasil, inovações como... / No meu país... / Acredito que no futuro...",hint:"apps · pix · fintechs · startups · inteligência artificial · mudança · inovação · futuro"}
        ]
      }
    ]
  },
  {
    id: "B1-U8",
    title: "Consolidação B1 e preparação para o B2",
    description: "Avaliação completa e transição para comunicação avançada",
    lessons: [
      {
        id: "B1-U8-L1",
        title: "Revisão gramatical completa do B1",
        shadowing: "Lê 3 vezes em voz alta, com velocidade e fluidez:\n\n— Se eu soubesse falar português fluente, trabalharia no Brasil.\n— É esse o seu sonho?\n— É! Quando chegar lá, quero mergulhar de cabeça na cultura.\n— Você já entende tudo quando assiste a séries brasileiras?\n— Quase tudo! Há alguns sotaques que ainda me confundem.\n— É natural. Mesmo que seja difícil, continue exposta.\n— Tenho me exposto bastante. Está sendo muito eficaz.\n— Fico feliz que você esteja progredindo tanto.\n— O segredo é que cada dia aprendo algo que ainda não sabia.",
        memoryPhrases: [
          "Se eu soubesse...",
          "Quando chegar lá...",
          "Mesmo que seja difícil...",
          "Tenho me exposto bastante.",
          "Cada dia aprendo algo novo."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique as diferenças entre os três tipos de subjuntivo (presente, imperfeito, futuro) com exemplos de cada um na sua própria vida. Mínimo 9 frases (3 por tipo).",
        content: "# Revisão Gramatical B1 — Todos os Recursos\n\n## Subjuntivo — resumo final\nPRESENTE: emoção, pedido, dúvida, impessoal\nEspero que VENHA. / É importante que SAIBA.\n\nIMPERFEITO: hipótese irreal, como se, mesmo que\nSe eu SOUBESSE... / Como se FOSSE...\n\nFUTURO: quando, se, assim que, onde quer que\nQuando CHEGAR... / Se PRECISAR...\n\n## Voz passiva — todos os tempos\nPresente: é feito / está sendo feito\nPassado: foi feito / tinha sido feito / estava sendo feito\nFuturo: será feito / vai ser feito\n\n## Discurso indireto — mudanças\nPresente → Imperfeito · Perfeito → Mais-que-perfeito\nFuturo → Condicional · Imperativo → Pedido subj imperf\n\n## Conectivos de alto nível\nOutrossim = además · Conquanto = aunque\nMalgrado = a pesar de · Porquanto = porque\nNão obstante = sin embargo · Contudo = no obstante\n\n## Estruturas complexas\nComo quer que = como sea que\nPor mais que = por más que\nSeja como for = sea como sea\nHaja o que houver = pase lo que pase",
        exercises: [
          {id:"B1-U8-L1-E1",type:"multiple_choice",skill:"grammar",question:"REVISÃO TOTAL — ¿Cuál usa los tres tiempos del subjuntivo correctamente?",options:["Espero que você venha. Se viesse, ficaria feliz. Quando vier, avisa.","Espero que você vem. Se viesse, ficaria. Quando vir, avisa.","Espero que você venha. Se visse, ficaria. Quando chegou, avisa.","Espero que você vim. Se viesse, ficou. Quando vier, avisaria."],answer:0,explanation:"VENHA (pres), VIESSE (imperf), VIER (futuro). Los tres subjuntivos correctos en una sola frase.",hint:"Presente: VENHA · Imperfeito: VIESSE · Futuro: VIER"},
          {id:"B1-U8-L1-E2",type:"fill_blank",skill:"grammar",question:"'___ o que houver, estarei do seu lado.' (pase lo que pase — estrutura fixa)",answer:["haja"],hint:"Estrutura fixa: HAJA O QUE HOUVER = pase lo que pase",explanation:"HAJA O QUE HOUVER = pase lo que pase. Estrutura fixa com subjuntivo presente de HAVER."},
          {id:"B1-U8-L1-E3",type:"multiple_choice",skill:"grammar",question:"¿Cuál es la versión formal de 'Mas' en un texto académico?",options:["E também","Outrossim / Contudo / Não obstante","Porém só","Mesmo assim só"],answer:1,explanation:"OUTROSSIM (=además), CONTUDO/NÃO OBSTANTE (=sin embargo) = conectivos formais equivalentes a mas/porém.",hint:"Conectivos formais de nível C1/académico para MAS"},
          {id:"B1-U8-L1-E4",type:"translation",skill:"writing",question:"Traduce usando estructuras B1 avanzadas: 'Por más que lo intente, no logro entender los subjuntivos. Sin embargo, sé que cuando practique más, todo va a tener sentido.'",answer:["por mais que eu tente não consigo entender os subjuntivos","contudo sei que quando praticar mais tudo vai fazer sentido"],hint:"por mais que · não consigo · contudo · quando praticar (subj futuro) · tudo vai fazer sentido",explanation:"Por mais que eu tente, não consigo entender os subjuntivos. Contudo, sei que quando praticar mais, tudo vai fazer sentido."},
          {id:"B1-U8-L1-E5",type:"free_writing",skill:"writing",question:"Escreva um texto demonstrando todo o domínio gramatical do B1: use os 3 tipos de subjuntivo, voz passiva, discurso indireto, verbos com preposição, gerúndio e conectivos formais. Mínimo 12 orações.",prompt:"Se eu soubesse... / Quando chegar... / Espero que... / O projeto foi... / Ela disse que... / Insisto em... / Chegou correndo... / Não obstante...",hint:"subj pres+imperf+futuro · voz passiva · disc indireto · verbo+prep · gerúndio · conectivos formais"}
        ]
      },
      {
        id: "B1-U8-L2",
        title: "Vocabulário de alto nível — precisão e elegância",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você percebe a diferença entre um falante de B1 e um de C1?\n— Percebo! O C1 tem mais precisão lexical.\n— Como assim?\n— Ele não diz só 'bom'. Diz 'impecável', 'primoroso', 'louvável'.\n— Exatamente! E as construções também são mais elaboradas.\n— E a fluência. O C1 fala sem pausas para traduzir mentalmente.\n— Isso é o maior salto.\n— Como se desenvolve isso?\n— Lendo muito. A leitura expande o léxico de forma orgânica.\n— E escrevendo todo dia.\n— Sem dúvida. Escrever força você a escolher as palavras certas.",
        memoryPhrases: [
          "Precisão lexical é fundamental.",
          "Escolha palavras mais específicas.",
          "A leitura expande o léxico.",
          "Escrever força boas escolhas.",
          "Fluência = pensar em português."
        ],
        oralProduction: "SITUAÇÃO ORAL: Substitua as palavras sublinhadas por sinônimos mais precisos e elegantes. Depois use 5 novas palavras em frases originais. Mínimo 8 frases.",
        content: "# Vocabulário de Alto Nível\n\n## Adjetivos precisos (substituir 'bom/bonito/ruim')\nBom → excelente · primoroso · impecável · louvável · notável\nBonito → esplêndido · deslumbrante · encantador · majestoso\nRuim → deplorável · lamentável · precário · insatisfatório\nImportante → crucial · fundamental · imprescindível · basilar\nGrande → monumental · vasto · colossal · expressivo\nPequeno → ínfimo · diminuto · exíguo · modesto\n\n## Verbos mais precisos\ndizer → afirmar · declarar · asseverar · pontuar\nachar → considerar · defender · sustentar · preconizar\nver → constatar · observar · vislumbrar · perceber\nfazer → executar · implementar · concretizar · realizar\nmudar → transformar · alterar · remodelar · renovar\n\n## Substantivos elegantes\ncoisa → aspecto · elemento · fator · componente\npessoa → indivíduo · sujeito · ser humano · cidadão\njeito → maneira · forma · modo · perspectiva\ntipo → categoria · modalidade · espécie · gênero\n\n## Expressões cultas\nHaja vista... = Dado que / En vista de que\nMalgrado... = A pesar de\nPorquanto... = Puesto que / Porque formal\nCom efeito... = En efecto / De hecho\nEm que pese... = A pesar de que",
        exercises: [
          {id:"B1-U8-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es el sinónimo más preciso y elegante de 'muito importante'?",options:["bem importante","muito relevante","imprescindível / crucial","super importante"],answer:2,explanation:"IMPRESCINDÍVEL / CRUCIAL = sinónimos elegantes y precisos de 'muito importante'.",hint:"La palabra que indica que no puede faltar"},
          {id:"B1-U8-L2-E2",type:"fill_blank",skill:"vocabulary",question:"'O resultado foi ___. Todos ficaram impressionados.' (Sustitui 'muito bom' por adjetivo elegante)",answer:["impecável","primoroso","notável","excelente","louvável"],hint:"Sinônimos elegantes de MUITO BOM",explanation:"Impecável / Primoroso / Notável / Louvável = alternativas elegantes para 'muito bom'."},
          {id:"B1-U8-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál verbo es más preciso y elegante que 'dizer' para afirmar algo con seguridad?",options:["falar","comunicar","asseverar / afirmar categoricamente","avisar"],answer:2,explanation:"ASSEVERAR = afirmar con total seguridad. Más preciso que dizer para afirmaciones enfáticas.",hint:"El verbo que indica afirmación con total certeza"},
          {id:"B1-U8-L2-E4",type:"translation",skill:"writing",question:"Traduce elevando el vocabulario: 'Es muy importante que hagamos algo para cambiar esta mala situación.'",answer:["é imprescindível que implementemos ações para transformar este cenário deplorable","é crucial que tomemos medidas para reverter esta situação precária"],hint:"imprescindível/crucial · implementemos · transformar · cenário · deplorable/precária",explanation:"É imprescindível que implementemos ações para transformar este cenário deplorável. (Alto nível)"},
          {id:"B1-U8-L2-E5",type:"free_writing",skill:"writing",question:"Reescreva este texto simples elevando o vocabulário: 'O Brasil é um país grande e bonito. Tem muitas coisas boas. Mas tem alguns problemas. É importante fazer algo para melhorá-lo.'",prompt:"Reescreva com vocabulário de alto nível: Brasil → ? · grande → ? · bonito → ? · coisas boas → ? · problemas → ? · fazer algo → ? · melhorá-lo → ?",hint:"vasto e esplêndido · aspectos notáveis · desafios estruturais · implementar políticas · aprimorá-lo"}
        ]
      },
      {
        id: "B1-U8-L3",
        title: "Compreensão oral — sotaques e velocidade real",
        shadowing: "DESAFIO AVANÇADO — Lê 3 vezes em voz alta o mais rápido que conseguir:\n\n— Oxente, você entendeu o que ele disse lá?\n— Mais ou menos... Esse sotaque nordestino é pesado demais pra mim.\n— Uai, mas tá ficando melhor né? Lembra quando você não entendia nada?\n— Lembro sim! Hoje pelo menos pego o contexto geral.\n— Isso é muito! Bah, eu levei meses pra entender o gaúcho.\n— Verdade? O gaúcho é pior que o carioca pra mim.\n— Cada um no seu tempo. Vai ficando natural com a exposição.\n— Tenho assistido muita novela e isso tá ajudando demais.\n— Boa estratégia! Novela é o melhor treino que existe.",
        memoryPhrases: [
          "Tô entendendo melhor!",
          "Pego o contexto geral.",
          "Vai ficando natural.",
          "A exposição ajuda demais.",
          "Cada sotaque tem seu ritmo."
        ],
        oralProduction: "SITUAÇÃO ORAL: Imite (da melhor forma que conseguir) 3 sotaques brasileiros diferentes: paulistano, carioca e nordestino. Depois comente as diferenças que percebe. Mínimo 8 frases.",
        content: "# Compreensão Oral Avançada\n\n## Estratégias de compreensão\n1. Pegar o contexto geral primeiro (top-down)\n2. Identificar palavras-chave conhecidas\n3. Inferir pelo tom e contexto\n4. Pedir para repetir: 'Pode repetir?'\n5. Pedir para falar mais devagar: 'Mais devagar, por favor'\n\n## Expressões para dificuldades\nNão entendi direito. = No entendí bien.\nPode falar mais devagar? = ¿Podés hablar más despacio?\nO que significa [palavra]? = ¿Qué significa...?\nComo se fala [coisa] em português?\nComo assim? = ¿Cómo es eso?\n\n## Diferenças de velocidade\nPaulistano: velocidade media, vogais fechadas\nCarioca: mais lento, arrastra as sílabas, R=H\nNordestino: ritmo diferente, vogais abertas\nGaúcho: R forte, ritmo próprio\nMineiro: mais lento, vogais nasais\n\n## Redução de fala rápida\nestou→tô · para→pra · você→cê\nnão é→num é · para mim→pra mim\no que→oque · tem que→temque\nde onde→donde · a gente→agente\n\n## Recursos de imersão\nPodcasts: Podcastalvez, Café Brasil, Jornaleiros\nYouTube: Canal dos EUA, Bruno e Marrone\nSéries: Sintonia, Vai Rir do Quê, Malhação",
        exercises: [
          {id:"B1-U8-L3-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la forma más educada de pedir que alguien repita algo en português?",options:["Não entendi nada.","Fala de novo.","Poderia repetir, por favor? Não entendi direito.","Mais uma vez!"],answer:2,explanation:"PODERIA REPETIR + NÃO ENTENDI DIREITO = forma más educada y natural para pedir repetición.",hint:"Forma educada y natural para pedir repetição"},
          {id:"B1-U8-L3-E2",type:"fill_blank",skill:"vocabulary",question:"A redução informal de 'você' no PB oral é ___.",answer:["cê"],hint:"La forma reducida de VOCÊ en el habla brasileña informal",explanation:"CÊ = você en el habla informal. Muy común en PB, especialmente en SP."},
          {id:"B1-U8-L3-E3",type:"multiple_choice",skill:"culture",question:"¿Cuál característica es del SOTAQUE CARIOCA (Rio de Janeiro)?",options:["El R muy fuerte","Vogais fechadas e rápido","El R pronunciado como H y ritmo más arrastrado","Uai! como expresión característica"],answer:2,explanation:"Carioca: R pronunciado como H (porta=poh-ta) y ritmo mais lento e arrastado. Muy musical.",hint:"El sotaque más 'musical' de Brasil"},
          {id:"B1-U8-L3-E4",type:"translation",skill:"writing",question:"Traduce de forma informal y con contracciones: '¿Vos estás bien? ¿A dónde vas? No entiendo por qué no me avisaste antes.'",answer:["cê tá bem","pra onde cê vai","num entendo porque você não me avisou antes"],hint:"cê tá · pra onde · num entendo · não me avisou",explanation:"Cê tá bem? Pra onde cê vai? Num entendo porque você não me avisou antes."},
          {id:"B1-U8-L3-E5",type:"free_writing",skill:"writing",question:"Escreva um guia prático para quem está com dificuldade de entender o português falado no Brasil. Inclua: estratégias, expressões para pedir repetição, sotaques e recursos de imersão. Mínimo 10 orações.",prompt:"Para entender melhor o português falado, recomendo... / Quando não entender... / Os sotaques mais difíceis são... / A estratégia que mais funciona é... / Para praticar...",hint:"estratégias · pedir repetição educadamente · sotaques · redução de fala · recursos de imersão"}
        ]
      },
      {
        id: "B1-U8-L4",
        title: "Produção integrada — escrita e fala avançadas",
        shadowing: "DESAFIO FINAL — Lê 3 vezes com expressão e velocidade:\n\n— Vamos fazer um exercício de produção integrada?\n— Claro! Do que se trata?\n— Você vai receber um tema e tem 3 minutos para falar sobre ele sem parar.\n— Sem parar? Isso é difícil.\n— É o objetivo! A ideia é que o pensamento flua sem traduzir.\n— Tudo bem. Pode dar o tema.\n— O tema é: 'O que o Brasil tem a ensinar ao mundo?'\n— Perfeito! O Brasil tem muito a ensinar em termos de biodiversidade...\n— Continue! Não pare. Desenvolva cada aspecto...\n— ...de música, de mistura cultural, de resiliência do povo...",
        memoryPhrases: [
          "O pensamento deve fluir.",
          "Sem parar para traduzir.",
          "Desenvolva cada aspecto.",
          "O Brasil tem muito a ensinar.",
          "A fluência é o objetivo final."
        ],
        oralProduction: "DESAFIO ORAL: Fale por 3 minutos sem parar sobre: 'O que o Brasil tem a ensinar ao mundo?' Use tudo que aprendeu: cultura, biodiversidade, música, diversidade, inovação. Sem roteiro!",
        content: "# Produção Integrada — Escrita e Fala\n\n## O que é fluência\nFluência ≠ perfeição gramatical\nFluência = comunicar sem pausas longas para traduzir\nFluência = ajustar o registro ao contexto\nFluência = recuperar-se de erros naturalmente\n\n## Estratégias para falar com fluência\n1. Pensar em português desde o início\n2. Usar conectores para ganhar tempo: bem... · veja... · olha...\n3. Parafrasear quando não sabe a palavra\n4. Não se corrigir o tempo todo\n5. Simular monólogos de 1-3 minutos diariamente\n\n## Estratégias para escrever com fluência\n1. Fazer outline antes de escrever\n2. Primeira versão sem revisar\n3. Revisão depois: gramática, vocabulário, coesão\n4. Leitura em voz alta para detectar erros\n5. Ter um parceiro que corrija\n\n## Técnicas de expansão\nDar exemplos: Por exemplo... · Como no caso de...\nComparar: Assim como... · Da mesma forma...\nContrastar: Por outro lado... · Em contrapartida...\nAprofundar: Isso significa que... · O que implica...\nConcluir: Portanto... · Em suma...\n\n## O que você conquistou no B1\n✅ Subjetivo em 3 tempos\n✅ Voz passiva completa\n✅ Discurso indireto\n✅ Registro formal e informal\n✅ Argumentação e debate\n✅ Escrita literária e profissional\n✅ Oralidade natural",
        exercises: [
          {id:"B1-U8-L4-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál define mejor la FLUÊNCIA lingüística?",options:["Hablar sin ningún error gramatical","Comunicarse sin pausas largas para traducir, ajustando el registro al contexto","Saber todas las palabras del diccionario","Hablar igual que un nativo de cuna"],answer:1,explanation:"Fluência = comunicar sem pausas para traduzir e ajustar o registro. Não é perfeição gramatical.",hint:"Fluência é comunicação eficaz, não perfeição"},
          {id:"B1-U8-L4-E2",type:"fill_blank",skill:"vocabulary",question:"'Não sei a palavra exata, mas ___ o que quero dizer...' (parafrasear para continuar)",answer:["posso explicar","deixa eu explicar","vou tentar explicar"],hint:"Estratégia para continuar quando não sabe uma palavra",explanation:"DEIXA EU EXPLICAR / POSSO EXPLICAR = parafrasear. Estrategia de fluência para cuando no sabes la palabra."},
          {id:"B1-U8-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál conector usás para APROFUNDAR (profundizar) un punto que mencionaste?",options:["Por outro lado...","Isso significa que... / O que implica...","Em primeiro lugar...","Por fim..."],answer:1,explanation:"ISSO SIGNIFICA QUE / O QUE IMPLICA = para profundizar y explicar implicaciones de algo dicho.",hint:"Para explicar o significado ou implicação do que foi dito"},
          {id:"B1-U8-L4-E4",type:"translation",skill:"writing",question:"Traduce este párrafo fluente: 'Brasil tiene mucho para enseñarle al mundo. Desde su biodiversidad incomparable hasta su capacidad de mezclar culturas y crear algo nuevo. Eso es lo que lo hace único.'",answer:["o brasil tem muito a ensinar ao mundo","desde sua biodiversidade incomparável até sua capacidade de misturar culturas e criar algo novo","isso é o que o torna único"],hint:"tem muito a ensinar · desde · biodiversidade incomparável · misturar culturas · criar algo novo · o que o torna único",explanation:"O Brasil tem muito a ensinar ao mundo. Desde sua biodiversidade incomparável até sua capacidade de misturar culturas e criar algo novo. Isso é o que o torna único."},
          {id:"B1-U8-L4-E5",type:"free_writing",skill:"writing",question:"PRODUÇÃO FINAL B1: Escreva um texto de opinião completo e sofisticado sobre 'O que o Brasil tem a ensinar ao mundo'. Use: estrutura dissertativa, vocabulário de alto nível, subjuntivo, voz passiva, conectivos formais. Mínimo 15 orações.",prompt:"INTRO: Poucos países... / ARG1: Em primeiro lugar, a biodiversidade... / ARG2: Outrossim, a diversidade cultural... / ARG3: Por fim, a inovação... / CONC: É imperativo que o mundo...",hint:"intro impactante · 3 argumentos sólidos · vocabulário de alto nível · subjuntivo + passiva + formais"}
        ]
      },
      {
        id: "B1-U8-L5",
        title: "Avaliação final B1 e próximos passos",
        shadowing: "AVALIAÇÃO — Lê com máxima expressividade e velocidade:\n\n— Parabéns! Você completou o nível B1!\n— Mal posso acreditar. Foi uma jornada incrível.\n— O que você diria que foi a maior conquista?\n— A fluência. Agora penso em português sem traduzir.\n— E o que ainda quer melhorar antes do B2?\n— A precisão lexical e a escrita formal mais elaborada.\n— Muito bem! No B2 você vai dominar registros ainda mais complexos.\n— Mal posso esperar! A língua vai se tornando parte de mim.\n— É exatamente isso. Quando o idioma entra em você, não sai mais.\n— Que forma linda de dizer. Obrigada por tudo!",
        memoryPhrases: [
          "Penso em português!",
          "A língua entrou em mim.",
          "A jornada foi incrível.",
          "Quero melhorar cada vez mais.",
          "Pronto para o B2!"
        ],
        oralProduction: "AVALIAÇÃO ORAL FINAL B1: Responda sem preparação:\n1. Apresente-se e fale sobre suas conquistas (2 min)\n2. Debata: 'O Brasil tem mais vantagens ou desafios?' (2 min)\n3. Conte uma história marcante com técnicas literárias (2 min)\n4. Faça uma apresentação profissional de 1 min\n5. Simule uma negociação (1 min)\nTotal: 8 minutos de fluência B1 real.",
        content: "# Avaliação Final B1 — Conquistas Completas\n\n## Gramática dominada\n✅ Subjuntivo presente (emoção, pedido, dúvida)\n✅ Subjuntivo imperfeito (hipótese irreal, como se)\n✅ Subjuntivo futuro (quando, se, assim que)\n✅ Voz passiva em todos os tempos\n✅ Discurso indireto com mudanças\n✅ Verbos com preposição precisos\n✅ Gerúndio e infinitivo pessoal\n✅ Conectivos formais avançados\n\n## Habilidades comunicativas\n✅ Debate estruturado com argumentação\n✅ Registros formal e informal adequados\n✅ Texto dissertativo completo\n✅ Apresentação oral profissional\n✅ Feedback com modelo SBI\n✅ Negociação profissional\n✅ LinkedIn e networking\n✅ Narrativa avançada com storytelling\n✅ Análise literária básica\n✅ Entrevista de emprego\n\n## Cultura e mundo brasileiro\n✅ Sistema político completo\n✅ Desigualdade social e causas\n✅ Cultura pop: novela, música, streaming\n✅ Mercado de trabalho (CLT, PJ, startups)\n✅ Biomas brasileiros (6 biomas)\n✅ Gastronomia regional avançada\n✅ Festividades e celebrações\n✅ Saúde mental no contexto brasileiro\n✅ Tecnologia e inovação (Pix, fintechs)\n\n## O que espera no B2\n→ Voz passiva sintética avançada\n→ Períodos hipotéticos complexos\n→ Figuras de linguagem\n→ Registro acadêmico e científico\n→ Literatura brasileira aprofundada\n→ Argumentação sofisticada",
        exercises: [
          {id:"B1-U8-L5-E1",type:"multiple_choice",skill:"grammar",question:"AVALIAÇÃO FINAL — ¿Cuál es 100% correcto gramaticalmente?",options:["Embora seja difícil, mas continuo tentando.","Embora seja difícil, continuo tentando.","Embora fosse difícil, continuo tentando.","Embora é difícil, continuo tentando."],answer:1,explanation:"EMBORA + subjuntivo + oração principal (sem MAS). Embora SEJA (pres subj) + continuo (presente).",hint:"EMBORA + subjuntivo SEM MAS na mesma frase"},
          {id:"B1-U8-L5-E2",type:"fill_blank",skill:"grammar",question:"'O relatório ___ pela diretoria e ___ publicado amanhã.' (foi aprovado / será — voz passiva)",answer:["foi aprovado","será"],hint:"Passiva passado: FOI + particípio · Passiva futuro: SERÁ + particípio",explanation:"FOI APROVADO (passado) + SERÁ PUBLICADO (futuro). Voz passiva nos dois tempos."},
          {id:"B1-U8-L5-E3",type:"multiple_choice",skill:"grammar",question:"DISCURSO INDIRETO: 'Eu fiz tudo que você pediu.' → Ela disse que ___",options:["fez tudo que eu tinha pedido","fazia tudo que eu pedia","fez tudo que eu peço","faria tudo que pedisse"],answer:0,explanation:"FIZA (perfeito→mais-que-perfeito: tinha feito) + PEDIU (perfeito→tinha pedido). Ela disse que TINHA FEITO tudo que eu TINHA PEDIDO.",hint:"Perfeito → Mais-que-perfeito no discurso indireto"},
          {id:"B1-U8-L5-E4",type:"translation",skill:"writing",question:"AVALIAÇÃO TOTAL: Traduce con todos los recursos B1: 'Aunque sea difícil, es fundamental que todos practiquen el idioma diariamente. El proyecto fue aprobado, pero todavía está siendo implementado.'",answer:["embora seja difícil é fundamental que todos pratiquem o idioma diariamente","o projeto foi aprovado mas ainda está sendo implementado"],hint:"embora seja (subj) · é fundamental que pratiquem (subj) · foi aprovado (passiva) · está sendo implementado (passiva progr)",explanation:"Embora seja difícil, é fundamental que todos pratiquem o idioma diariamente. O projeto foi aprovado, mas ainda está sendo implementado."},
          {id:"B1-U8-L5-E5",type:"free_writing",skill:"writing",question:"TEXTO FINAL MAESTRO B1: Escreva o texto mais completo que você já produziu em português. Deve incluir: narrativa pessoal, argumentação, vocabulário de alto nível, estruturas gramaticais B1 e referências culturais brasileiras. Mínimo 16 orações.",prompt:"Quando comecei a estudar português (narrativa)... / Em primeiro lugar, o que me fascina é... / Outrossim... / Embora seja difícil... / É imprescindível que... / O projeto que tenho... / Se eu soubesse antes... / Quando chegar ao Brasil...",hint:"narrativa + argumentação + vocab alto nível + 3 subjuntivos + voz passiva + disc indireto + cultura BR"}
        ]
      }
    ]
  }
];
