// B1 — Unidades 3 y 4
export const B1_U3_U4 = [
  {
    id: "B1-U3",
    title: "Comunicação avançada — debate, argumentação e persuasão",
    description: "Expressar-se com precisão, defender ideias e convencer",
    lessons: [
      {
        id: "B1-U3-L1",
        title: "Debatendo — estrutura e vocabulário",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Vou defender que a educação pública deve ser prioridade nacional.\n— Interessante. Qual é o seu principal argumento?\n— O principal é que a educação é um direito fundamental. Sem ela, nenhum outro direito é garantido.\n— Entendo seu ponto, no entanto, discordo da solução proposta.\n— Por quê? Pode elaborar?\n— Porque investir apenas em educação pública sem reformar o sistema é insuficiente.\n— Você tem um ponto válido. Porém, o debate não é só sobre investimento, é sobre acesso.\n— Concordo em parte. Mas precisamos de dados concretos para essa discussão.",
        memoryPhrases: [
          "Qual é o seu argumento principal?",
          "Você tem um ponto válido.",
          "Discordo da solução proposta.",
          "Pode elaborar?",
          "Concordo em parte, mas..."
        ],
        oralProduction: "SITUAÇÃO ORAL: Debata com um parceiro imaginário sobre educação pública vs. privada no Brasil. Apresente 3 argumentos, rebata 2 contra-argumentos e conclua. Mínimo 10 frases com vocabulário de debate.",
        content: "# Debatendo — Estrutura e Vocabulário\n\n## Estrutura de um debate\n1. TESE: Defendo que...\n2. ARGUMENTO 1: Em primeiro lugar...\n3. ARGUMENTO 2: Além disso / Em segundo lugar...\n4. ARGUMENTO 3: Por fim / Finalmente...\n5. CONTRA-ARGUMENTO: No entanto / Porém...\n6. REFUTAÇÃO: Apesar disso / Ainda assim...\n7. CONCLUSÃO: Portanto / Em suma...\n\n## Apresentar sua posição\nDefendo que... · Sou a favor de...\nSou contra... · Na minha perspectiva...\nDo meu ponto de vista... · Acredito firmemente que...\n\n## Argumentar\nEm primeiro lugar... · Além disso...\nNão só... como também... · Sem contar que...\nO fato é que... · Os dados mostram que...\nÉ comprovado que... · Vale lembrar que...\n\n## Rebater argumentos\nNo entanto... · Porém... · Todavia...\nAinda assim... · Apesar disso...\nEm contrapartida... · Por outro lado...\nSeu argumento seria válido se...\nPermita-me discordar... · Respeitosamente, creio que...\n\n## Conceder e manter posição\nVocê tem razão em parte, mas...\nReconheço que... porém...\nÉ verdade que... no entanto...",
        exercises: [
          {id:"B1-U3-L1-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál expresión introduce el argumento principal de un debate?",options:["Em contrapartida...","Em primeiro lugar...","Apesar disso...","Por outro lado..."],answer:1,explanation:"Em primeiro lugar = En primer lugar. Introduce el argumento principal de la tesis.",hint:"Para introducir el primer argumento"},
          {id:"B1-U3-L1-E2",type:"fill_blank",skill:"vocabulary",question:"'Você tem razão em parte, ___ precisamos considerar outros fatores.' (conceder y mantener posición)",answer:["mas","porém","no entanto","todavia"],hint:"Concessão seguida de contraposição",explanation:"Mas/Porém/No entanto = Pero/Sin embargo. Para conceder e manter posição."},
          {id:"B1-U3-L1-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase introduce una refutación educada?",options:["Você está completamente errado.","Permita-me discordar respeitosamente.","Isso não faz sentido.","Seu argumento é inválido."],answer:1,explanation:"Permita-me discordar respeitosamente = Permítame discrepar respetuosamente. Educada y formal.",hint:"Refutação educada y formal"},
          {id:"B1-U3-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Defiendo que la educación pública es un derecho fundamental. En primer lugar, sin educación ningún otro derecho es posible. Además, los datos muestran que los países más desarrollados invierten más en educación.'",answer:["defendo que a educação pública é um direito fundamental","em primeiro lugar sem educação nenhum outro direito é possível","além disso os dados mostram que os países mais desenvolvidos investem mais em educação"],hint:"defendo que · em primeiro lugar · além disso · os dados mostram",explanation:"Defendo que a educação pública é um direito fundamental. Em primeiro lugar, sem educação nenhum outro direito é possível. Além disso, os dados mostram que os países mais desenvolvidos investem mais em educação."},
          {id:"B1-U3-L1-E5",type:"free_writing",skill:"writing",question:"Escreva um parágrafo argumentativo completo sobre um tema que você defende: tese, 3 argumentos, reconhecimento do contra-argumento e conclusão. Mínimo 10 orações.",prompt:"Defendo que... / Em primeiro lugar... / Além disso... / Por fim... / É verdade que... porém... / Portanto...",hint:"tese clara · 3 argumentos com conectivos · concessão + refutação · conclusão forte"}
        ]
      },
      {
        id: "B1-U3-L2",
        title: "Linguagem formal e informal — registro preciso",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Tô muito na correria hoje, sabe?\n— É, a semana tá pesada pra todo mundo.\n— É isso. Mas falando sério, você conseguiu aquela reunião com o cliente?\n— Consegui sim. Agendei para a próxima quarta.\n— Boa! Como você vai apresentar a proposta?\n— Vou ser bem direto. Apresentar os dados, os benefícios e o custo.\n— Mas lembra que ele é bem formal. Vai ter que adaptar o tom.\n— Boa observação. Com ele, preciso ser mais cuidadoso no vocabulário.\n— Exatamente. Deixa de ser informal e vai na formalidade.",
        memoryPhrases: [
          "Tô na correria. (informal)",
          "Estou muito ocupado. (formal)",
          "Que foi? (informal)",
          "O que ocorreu? (formal)",
          "Precisamos adequar o registro."
        ],
        oralProduction: "SITUAÇÃO ORAL: Conte a mesma situação duas vezes — primeiro de forma informal (para um amigo) e depois de forma formal (para o chefe). Mínimo 6 frases em cada registro.",
        content: "# Linguagem Formal e Informal — Registros\n\n## Vocabulário comparado\nInformal → Formal\ntô = estou · tá = está · pra = para\ngente = pessoas/nós · a gente = nós\nnego/negão = pessoa · cara = senhor\ntrem (MG) = coisa · troço = objeto\npô / poxa = expressão de espanto → ah\ncaramba = caramba → nossa\n\n## Construções diferentes\nInformal: A gente foi lá.\nFormal: Nós fomos ao local.\n\nInformal: Me dá uma ideia.\nFormal: Poderia me dar uma sugestão?\n\nInformal: Tô precisando de ajuda.\nFormal: Necessito de assistência.\n\nInformal: O projeto tá show.\nFormal: O projeto está excelente.\n\n## Emails: informal vs. formal\nInformal: Oi João, tudo bem?\nFormal: Prezado Sr. João,\n\nInformal: Obrigado! Beijos.\nFormal: Agradeço antecipadamente. Atenciosamente,\n\n## Situações e registros\nAmigos/família → informal\nChefe/cliente → formal\nReunião de trabalho → semi-formal a formal\nWhatsApp profissional → semi-formal\nDocumentos/emails → formal\n\n## Verbos formais mais usados\nNecessitar (precisar) · Solicitar (pedir)\nInformar (avisar) · Comunicar (falar)\nAguardar (esperar) · Encaminhar (mandar)",
        exercises: [
          {id:"B1-U3-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la versión formal de 'Tô precisando de ajuda'?",options:["Preciso de ajuda urgente.","Necessito de assistência.","Me ajuda aí.","Pode me dar uma força?"],answer:1,explanation:"NECESSITO DE ASSISTÊNCIA = forma más formal. PRECISAR → NECESSITAR. AJUDA → ASSISTÊNCIA.",hint:"PRECISAR → NECESSITAR · AJUDA → ASSISTÊNCIA"},
          {id:"B1-U3-L2-E2",type:"fill_blank",skill:"vocabulary",question:"'___ pela atenção dispensada.' (agradecer formal — fórmula de encerramento)",answer:["agradeço antecipadamente","agradeço"],hint:"Fórmula formal de agradecimento em emails",explanation:"Agradeço antecipadamente pela atenção dispensada = Agradezco de antemano la atención prestada."},
          {id:"B1-U3-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la forma más formal de 'Manda isso pra mim'?",options:["Manda esse negócio.","Me encaminha isso.","Poderia encaminhar-me o documento?","Me passa isso por favor."],answer:2,explanation:"PODERIA ENCAMINHAR-ME O DOCUMENTO? = muy formal. MANDAR → ENCAMINHAR. ISSO → O DOCUMENTO.",hint:"La más formal: condicional + verbo formal + objeto específico"},
          {id:"B1-U3-L2-E4",type:"translation",skill:"writing",question:"Traduce en registro formal: 'Hola, te escribo porque necesito que me mandes el informe cuanto antes. Gracias!'",answer:["prezado fulano venho por meio desta solicitar o envio do relatório com urgência","agradeço antecipadamente"],hint:"Prezado · venho solicitar · o envio do relatório · com urgência · agradeço antecipadamente",explanation:"Prezado [nome], Venho por meio desta solicitar o envio do relatório com urgência. Agradeço antecipadamente."},
          {id:"B1-U3-L2-E5",type:"free_writing",skill:"writing",question:"Escreva a mesma mensagem em dois registros: 1) informal para um amigo e 2) formal para um cliente. O tema: você precisou adiar uma reunião. Mínimo 6 frases em cada versão.",prompt:"INFORMAL: Ei [amigo], tudo bem? Olha, sobre aquela reunião... / FORMAL: Prezado Sr./Sra. [nome], Venho por meio desta...",hint:"informal: tô, tá, a gente, gírias. formal: necessito, solicito, venho informar, agradeço antecipadamente"}
        ]
      },
      {
        id: "B1-U3-L3",
        title: "Texto dissertativo — escrevendo com impacto",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Como você estrutura seus textos em português?\n— Começo sempre pela tese. Depois desenvolvo os argumentos.\n— E a conclusão?\n— A conclusão retoma a tese e fecha com uma reflexão ou proposta.\n— Você usa muitos conectivos?\n— Uso bastante. São eles que dão fluidez ao texto.\n— Alguma dica para quem está começando?\n— Leia muito em português. A leitura forma a estrutura mental do idioma.\n— Boa dica! E a prática de escrita?\n— Essencial! Escreva todo dia, mesmo que seja pouco. A consistência transforma.",
        memoryPhrases: [
          "A tese é a posição central.",
          "Em primeiro lugar...",
          "Por outro lado...",
          "A conclusão retoma a tese.",
          "A consistência transforma."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique para alguém como escrever um bom texto dissertativo. Dê a estrutura, dicas de conectivos e exemplos. Mínimo 8 frases.",
        content: "# Texto Dissertativo\n\n## Estrutura clássica\nINTRODUÇÃO (1 parágrafo)\n- Contextualização do tema\n- Tese: sua posição clara\n\nDESENVOLVIMENTO (2-3 parágrafos)\n- Cada parágrafo = 1 argumento principal\n- Evidência/exemplo/dado que sustenta\n- Conexão com o próximo parágrafo\n\nCONCLUSÃO (1 parágrafo)\n- Retomada da tese (sem repetir igual)\n- Síntese dos argumentos\n- Reflexão final ou proposta de solução\n\n## Conectivos por função\nIntrodução: Atualmente · No contexto atual · Sabe-se que\nAdição: além disso · não só... como também · outrossim\nContraste: no entanto · por outro lado · em contrapartida\nCausa: pois · uma vez que · tendo em vista que\nConclusão: portanto · dessa forma · em suma · logo\n\n## Linguagem dissertativa\nÉ notório que... · Pode-se afirmar que...\nConforme dados do IBGE... · Segundo especialistas...\nÀ luz desses fatos... · Nesse contexto...\nFaz-se necessário que... · Urge que...\n\n## Erros comuns\n❌ Começar com 'Eu acho que' (muito informal)\n✅ 'É possível observar que' / 'Sabe-se que'\n❌ Parágrafo sem argumento claro\n✅ Cada parágrafo: tópico + desenvolvimento + ligação",
        exercises: [
          {id:"B1-U3-L3-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál conector introduce la conclusión de un texto dissertativo?",options:["Em primeiro lugar","Além disso","Portanto / Dessa forma","Uma vez que"],answer:2,explanation:"PORTANTO / DESSA FORMA = Por lo tanto / De esta forma. Para introducir la conclusión.",hint:"Para introducir la conclusión"},
          {id:"B1-U3-L3-E2",type:"fill_blank",skill:"vocabulary",question:"'___ dados do IBGE, o Brasil tem mais de 210 milhões de habitantes.' (según — citação formal)",answer:["conforme","segundo","de acordo com"],hint:"Para citar fuentes en texto formal",explanation:"Conforme / Segundo / De acordo com = Según. Para citar fuentes en texto académico/dissertativo."},
          {id:"B1-U3-L3-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase es apropiada para INICIAR un texto dissertativo?",options:["Eu acho que a tecnologia é importante.","Atualmente, a tecnologia transformou profundamente a sociedade.","A tecnologia é muito boa para nós.","Vou falar sobre a tecnologia."],answer:1,explanation:"ATUALMENTE + contextualização impersonal = apertura correcta de texto dissertativo.",hint:"Texto dissertativo: contextualização impessoal, sem 'eu acho'"},
          {id:"B1-U3-L3-E4",type:"translation",skill:"writing",question:"Traduce en estilo dissertativo formal: 'Las redes sociales transformaron la manera en que nos comunicamos. Sin embargo, también generaron nuevos problemas sociales.'",answer:["as redes sociais transformaram profundamente a forma como nos comunicamos","no entanto também geraram novos problemas sociais"],hint:"transformaram profundamente · a forma como nos comunicamos · no entanto · também geraram",explanation:"As redes sociais transformaram profundamente a forma como nos comunicamos. No entanto, também geraram novos problemas sociais."},
          {id:"B1-U3-L3-E5",type:"free_writing",skill:"writing",question:"Escreva um texto dissertativo completo (introdução + 2 argumentos + conclusão) sobre: 'O papel das redes sociais na sociedade brasileira contemporânea'. Mínimo 12 orações.",prompt:"INTRO: Atualmente... / Pode-se afirmar que... / DESENVOLVIMENTO: Em primeiro lugar... / Além disso... / CONCLUSÃO: Portanto... / Dessa forma...",hint:"intro com contextualização · 2 parágrafos de argumento · conclusão que retoma a tese"}
        ]
      },
      {
        id: "B1-U3-L4",
        title: "Apresentação oral profissional",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Bom dia a todos. Hoje vou apresentar os resultados do terceiro trimestre.\n— Como referência, no período anterior tivemos um crescimento de 12%.\n— Este trimestre, superamos as expectativas com 18% de crescimento.\n— Para ilustrar, vejam o gráfico na tela. Os números falam por si.\n— Em segundo lugar, gostaria de destacar a expansão para o Nordeste.\n— Essa foi uma decisão estratégica que já mostrou resultados expressivos.\n— Por fim, proponho que no próximo trimestre foquemos na retenção de clientes.\n— Estou à disposição para perguntas. Muito obrigado pela atenção.",
        memoryPhrases: [
          "Hoje vou apresentar...",
          "Como referência...",
          "Para ilustrar...",
          "Gostaria de destacar...",
          "Estou à disposição."
        ],
        oralProduction: "SITUAÇÃO ORAL: Faça uma apresentação profissional de 3 minutos sobre um projeto, produto ou resultado. Use a estrutura completa: abertura, desenvolvimento (3 pontos), dados e conclusão com proposta. Mínimo 10 frases.",
        content: "# Apresentação Oral Profissional\n\n## Abertura\nBom dia/boa tarde a todos.\nMeu nome é... e hoje apresentarei...\nO objetivo desta apresentação é...\nVou dividir a apresentação em X partes.\n\n## Referências e contexto\nComo referência... · Como ponto de partida...\nPara contextualizar... · Vale lembrar que...\nNo período anterior... · Historicamente...\n\n## Apresentar dados\nOs números mostram que... · Segundo os dados...\nO gráfico ilustra... · Como podemos ver...\nO resultado foi... · Atingimos...\nSuperamos / Ficamos abaixo de...\n\n## Transições\nEm primeiro lugar... · Em segundo lugar...\nAlém disso... · Gostaria de destacar...\nPassando para o próximo ponto...\nNo que se refere a... · Com relação a...\n\n## Proposta e conclusão\nProponho que... · Sugiro que...\nO próximo passo é... · A estratégia para...\nEm resumo... · Para concluir...\nFico à disposição para perguntas.\n\n## Vocabulário de negócios\ncrescimento = crecimiento · meta = meta/objetivo\nresultados = resultados · desempenho = desempeño\nexecutar = ejecutar · implementar · estratégia",
        exercises: [
          {id:"B1-U3-L4-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase se usa para hacer la TRANSICIÓN entre puntos de una presentación?",options:["Estou à disposição.","Passando para o próximo ponto...","Para contextualizar...","Em resumo..."],answer:1,explanation:"PASSANDO PARA O PRÓXIMO PONTO = Pasando al siguiente punto. Transición entre secciones.",hint:"Para pasar de un punto al siguiente"},
          {id:"B1-U3-L4-E2",type:"fill_blank",skill:"vocabulary",question:"'___ os dados, o crescimento foi de 18% este trimestre.' (según los datos — citación formal)",answer:["segundo","conforme","de acordo com"],hint:"Según los datos = Segundo/Conforme/De acordo com os dados",explanation:"Segundo os dados = Según los datos. Para citar fuentes en presentaciones."},
          {id:"B1-U3-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo terminás formalmente una presentación antes de abrir el debate?",options:["Fim da apresentação!","Tchau e obrigado!","Fico à disposição para perguntas.","É isso aí, pessoal."],answer:2,explanation:"FICO À DISPOSIÇÃO PARA PERGUNTAS = Quedo a disposición para preguntas. Fórmula formal de cierre.",hint:"Fórmula formal para abrir espaço para perguntas"},
          {id:"B1-U3-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'Buenos días a todos. Hoy voy a presentar los resultados del proyecto. Para contextualizar, en el trimestre anterior tuvimos un crecimiento del 12%.'",answer:["bom dia a todos","hoje vou apresentar os resultados do projeto","para contextualizar no trimestre anterior tivemos um crescimento de doze por cento"],hint:"bom dia a todos · hoje vou apresentar · para contextualizar · no trimestre anterior · crescimento",explanation:"Bom dia a todos. Hoje vou apresentar os resultados do projeto. Para contextualizar, no trimestre anterior tivemos um crescimento de 12%."},
          {id:"B1-U3-L4-E5",type:"free_writing",skill:"writing",question:"Escreva o roteiro completo de uma apresentação profissional sobre um tema que você domina. Inclua: abertura, 3 pontos com dados/exemplos, transições e conclusão com proposta. Mínimo 12 orações.",prompt:"Bom dia! Hoje vou apresentar... / Para contextualizar... / Em primeiro lugar... / Passando para... / Gostaria de destacar... / Por fim, proponho que...",hint:"abertura formal · referências · 3 pontos com transições · dados · conclusão + proposta · disponível para perguntas"}
        ]
      },
      {
        id: "B1-U3-L5",
        title: "Comunicação não violenta e resolução de conflitos",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Precisamos conversar sobre o que aconteceu na reunião.\n— Claro. Me sinto um pouco desconfortável com o que foi dito.\n— Entendo. Quando você disse aquilo, me senti desrespeitado.\n— Não era minha intenção. Lamento se soou assim.\n— Agradeço por isso. O que me incomoda é quando...\n— Entendo sua perspectiva. O que você precisa é que eu...\n— Isso ajudaria muito. Você consegue fazer isso?\n— Posso tentar. E o que eu precisaria de você é...\n— Com certeza. Vamos chegar a um acordo?",
        memoryPhrases: [
          "Me sinto desconfortável com...",
          "Quando você disse isso, eu senti...",
          "Não era minha intenção.",
          "O que eu preciso é...",
          "Vamos chegar a um acordo."
        ],
        oralProduction: "SITUAÇÃO ORAL: Simule uma conversa de resolução de conflito usando linguagem não violenta. Expresse seus sentimentos, necessidades e faça um pedido claro. Mínimo 8 frases.",
        content: "# Comunicação Não Violenta — CNV\n\n## Os 4 componentes da CNV\n1. OBSERVAÇÃO: O que aconteceu (sem julgamento)\n2. SENTIMENTO: Como você se sentiu\n3. NECESSIDADE: O que você precisa\n4. PEDIDO: O que você pede concretamente\n\n## Observações sem julgamento\nQuando você [ação concreta]...\nNa reunião de ontem, quando...\nAo receber seu email, percebi que...\n\n## Expressar sentimentos\nMe sinto... (triste/frustrado/desconfortável)\nFiquei... (surpreso/chateado/preocupado)\nEssa situação me deixa...\n\n## Expressar necessidades\nO que eu preciso é...\nPara mim é importante...\nNecessito que...\n\n## Fazer pedidos\nVocê poderia...?\nO que eu te peço é...\nSeria possível...?\nPoderíamos combinar que...?\n\n## Receber críticas\nEntendo o que você está dizendo.\nLamento se soou assim.\nNão era minha intenção.\nO que eu quis dizer foi...\n\n## Vocabulário de resolução\nchegar a um acordo = llegar a un acuerdo\nentrar em consenso = llegar a un consenso\ndisponível para conversar · aberto a feedback\npedir desculpas = disculparse",
        exercises: [
          {id:"B1-U3-L5-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál frase expresa un SENTIMENTO en comunicación no violenta?",options:["Você sempre chega atrasado!","Você é muito descuidado.","Quando você chega tarde, me sinto desrespeitado.","O problema é você."],answer:2,explanation:"CNV: observação (quando você chega tarde) + sentimento (me sinto desrespeitado). Sin juicio.",hint:"CNV: observação concreta + sentimento (eu), sem julgamento do outro"},
          {id:"B1-U3-L5-E2",type:"fill_blank",skill:"vocabulary",question:"'O que eu ___ de você é mais comunicação sobre os prazos.' (necesito — CNV)",answer:["preciso","necessito"],hint:"PRECISAR/NECESSITAR DE = necesitar (necessidade na CNV)",explanation:"O que eu PRECISO de você = Lo que necesito de vos. Expresión de necesidad en CNV."},
          {id:"B1-U3-L5-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál respuesta usa comunicación no violenta al recibir una crítica?",options:["Isso não é verdade!","Você está exagerando.","Entendo o que você está dizendo. Lamento se soou assim.","A culpa não é minha."],answer:2,explanation:"Entendo + Lamento se soou assim = CNV para recibir crítica. Sin defensiva, reconociendo el impacto.",hint:"CNV: receber crítica = entender + reconhecer o impacto"},
          {id:"B1-U3-L5-E4",type:"translation",skill:"writing",question:"Traduce en estilo CNV: 'Cuando no recibo respuesta a mis emails, me siento ignorado. Necesito que respondas dentro de 24 horas. ¿Podés hacer eso?'",answer:["quando não recebo resposta aos meus emails me sinto ignorado","preciso que você responda dentro de vinte e quatro horas","você consegue fazer isso"],hint:"quando não recebo · me sinto ignorado · preciso que responda · dentro de 24 horas · você consegue",explanation:"Quando não recebo resposta aos meus emails, me sinto ignorado. Preciso que você responda dentro de 24 horas. Você consegue fazer isso?"},
          {id:"B1-U3-L5-E5",type:"free_writing",skill:"writing",question:"Escreva um diálogo de resolução de conflito usando os 4 componentes da CNV: observação, sentimento, necessidade e pedido. Mínimo 10 falas entre duas pessoas.",prompt:"A: Precisamos conversar sobre... / B: Claro. / A: Quando você... me sinto... / B: Não era minha intenção... / A: O que eu preciso é... / B: Podemos combinar que...",hint:"observação sem julgamento · sentimento (eu) · necessidade · pedido concreto · resposta empática"}
        ]
      }
    ]
  },
  {
    id: "B1-U4",
    title: "Brasil contemporâneo — sociedade e política",
    description: "Entender e falar sobre o Brasil atual com profundidade",
    lessons: [
      {
        id: "B1-U4-L1",
        title: "Sistema político e governança brasileira",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você entende bem o sistema político brasileiro?\n— Razoavelmente. É uma república presidencialista com três poderes.\n— Exatamente. E o Congresso? Sabe como funciona?\n— Sei que tem o Senado e a Câmara dos Deputados.\n— Isso. E o processo eleitoral? O voto é obrigatório aqui.\n— Sim! É diferente do meu país. Todos os maiores de 18 anos devem votar.\n— E o que você acha disso?\n— Acho interessante. Garante maior participação, mas também pode gerar votos sem reflexão.\n— É um debate importante. Democracia exige participação consciente.",
        memoryPhrases: [
          "É uma república presidencialista.",
          "O voto é obrigatório.",
          "O Congresso é bicameral.",
          "Os três poderes são...",
          "A democracia exige participação."
        ],
        oralProduction: "SITUAÇÃO ORAL: Explique o sistema político do Brasil para um estrangeiro. Compare com o sistema do seu país. Dê sua opinião sobre voto obrigatório. Mínimo 8 frases.",
        content: "# Sistema Político Brasileiro\n\n## Forma de governo\nRepública Federativa do Brasil\nPresidencialismo = el presidente es jefe de estado y gobierno\nFederalismo = União + 26 estados + DF + 5.570 municípios\n\n## Os três poderes\nExecutivo: Presidente + governadores + prefeitos\nLegislativo: Congresso Nacional = Senado + Câmara\nJudiciário: STF · STJ · TRF · TSE (eleitoral)\n\n## O Congresso\nSenado Federal: 81 senadores (3 por estado)\nCâmara dos Deputados: 513 deputados (proporcional)\n\n## Sistema eleitoral\nVoto obrigatório = 18-70 anos\nVoto facultativo = 16-17 e maiores de 70\nEleições a cada 4 anos (presidente e governadores)\nPrefeitos e vereadores: a cada 4 anos (anos pares)\n\n## Partidos políticos\nBrasil tem mais de 30 partidos registrados!\nSistema multipartidário e de coalizão\nPT, PL, MDB, PSDB, PP, PDT, PSB = principais\n\n## Vocabulário político\neleitores = electores · candidato = candidato\ncampanha = campaña · urna eletrônica = urna electrónica\nmandato = mandato · reeleição = reelección\nimpeachment · coalização = coalición",
        exercises: [
          {id:"B1-U4-L1-E1",type:"multiple_choice",skill:"culture",question:"¿Cuántos senadores tiene el Senado Federal del Brasil?",options:["513","81","26","100"],answer:1,explanation:"O Senado Federal tem 81 senadores (3 por cada estado + DF).",hint:"3 senadores por estado × 27 unidades federativas"},
          {id:"B1-U4-L1-E2",type:"fill_blank",skill:"culture",question:"No Brasil, o voto é ___ para pessoas entre 18 e 70 anos.",answer:["obrigatório"],hint:"No Brasil o voto não é opcional para essa faixa etária",explanation:"Voto obrigatório para 18-70 anos. Facultativo para 16-17 e maiores de 70."},
          {id:"B1-U4-L1-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo se llama el sistema donde el presidente es simultáneamente jefe de estado y de gobierno?",options:["Parlamentarismo","Presidencialismo","Monarquia constitucional","Federalismo"],answer:1,explanation:"PRESIDENCIALISMO = el presidente es jefe de estado Y de gobierno al mismo tiempo.",hint:"El sistema político donde el presidente concentra el poder ejecutivo"},
          {id:"B1-U4-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Brasil es una república presidencialista y federal. El Congreso Nacional está compuesto por el Senado y la Cámara de Diputados. El voto es obligatorio para los adultos.'",answer:["o brasil é uma república presidencialista e federativa","o congresso nacional é composto pelo senado e pela câmara dos deputados","o voto é obrigatório para os adultos"],hint:"república presidencialista e federativa · composto pelo senado e pela câmara · voto obrigatório",explanation:"O Brasil é uma república presidencialista e federativa. O Congresso Nacional é composto pelo Senado e pela Câmara dos Deputados. O voto é obrigatório para os adultos."},
          {id:"B1-U4-L1-E5",type:"free_writing",skill:"writing",question:"Escreva um texto comparando o sistema político do seu país com o do Brasil. Mencione: forma de governo, poder legislativo, sistema eleitoral e participação cidadã. Mínimo 10 orações.",prompt:"No Brasil... / No meu país... / Uma diferença importante é... / Em ambos os países... / Na minha opinião...",hint:"república/monarquia · presidencialismo/parlamentarismo · voto obrigatório/facultativo · congresso/parlamento"}
        ]
      },
      {
        id: "B1-U4-L2",
        title: "Desigualdade social e mobilidade no Brasil",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Como você enxerga a desigualdade no Brasil?\n— É muito gritante. O Brasil é um dos países mais desiguais do mundo.\n— Por que você acha que isso acontece?\n— São vários fatores: histórico escravagista, concentração de renda, acesso desigual à educação.\n— E o que tem melhorado?\n— Programas como o Bolsa Família ajudaram muito a reduzir a pobreza extrema.\n— Mas ainda há muito a fazer, né?\n— Muito. A mobilidade social existe, mas é difícil. O ponto de partida importa demais.\n— É um tema que merece atenção constante da sociedade e do governo.",
        memoryPhrases: [
          "É um dos mais desiguais.",
          "O histórico pesa muito.",
          "A mobilidade existe, mas...",
          "O ponto de partida importa.",
          "Merece atenção constante."
        ],
        oralProduction: "SITUAÇÃO ORAL: Dê sua opinião sobre desigualdade social no Brasil ou no seu país. Use dados e argumentos. Apresente causas, consequências e possíveis soluções. Mínimo 8 frases.",
        content: "# Desigualdade Social e Mobilidade\n\n## O contexto brasileiro\nCoeficiente de Gini = medida de desigualdade (Brasil ≈ 0.52)\nConcentração de renda = concentración de ingresos\n1% mais rico tem mais que 50% do total\nPobreza extrema = pobreza extrema\nFome ainda afeta milhões de brasileiros\n\n## Causas históricas\nEscravidão (1500-1888) = 388 anos de trabalho forçado\nConcentração de terras = latifúndio\nFalta de acesso à educação de qualidade\nCorrupção e má gestão de recursos públicos\nRacismo estrutural que limita oportunidades\n\n## Programas sociais\nBolsa Família / Bolsa Família = transferência de renda\nMinha Casa Minha Vida = habitação popular\nProUni = bolsas universitárias\nCREI/CRAS = assistência social\nSUS = saúde universal gratuita\n\n## Mobilidade social\nAscensão social = ascenso social\nClasse C = classe média brasileira emergente\nCota = cuota (racial, social, escolar)\nCotas raciais nas universidades = política afirmativa\n\n## Vocabulário\ngritante = flagrante · gritante\nabismo social = abismo social\nfavelado = persona de favela\nperiferia = periferia · vulnerável = vulnerable",
        exercises: [
          {id:"B1-U4-L2-E1",type:"multiple_choice",skill:"culture",question:"¿Cuántos años duró la esclavitud en Brasil?",options:["188 años","288 años","388 años","488 años"],answer:2,explanation:"La esclavitud en Brasil duró 388 años (1500-1888), la más larga de las Américas.",hint:"Desde el año 1500 hasta 1888"},
          {id:"B1-U4-L2-E2",type:"fill_blank",skill:"vocabulary",question:"O ___ Família é o principal programa de transferência de renda do Brasil para famílias em situação de pobreza.",answer:["bolsa","Bolsa"],hint:"O nome completo do programa social mais conhecido do Brasil",explanation:"Bolsa Família = programa de transferencia de renda condicional para familias en pobreza."},
          {id:"B1-U4-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Qué son las 'cotas raciais' en las universidades brasileñas?",options:["Límite de estudiantes por raza","Becas solo para blancos","Cuotas afirmativas para negros, pardos e indígenas","Requisito de hablar lengua indígena"],answer:2,explanation:"Cotas raciais = cuotas afirmativas para negros, pardos e indígenas en universidades públicas. Política de reparación histórica.",hint:"Política afirmativa de reparação histórica"},
          {id:"B1-U4-L2-E4",type:"translation",skill:"writing",question:"Traduce: 'La desigualdad social en Brasil es muy notoria. Tiene causas históricas profundas, como la esclavitud. Los programas sociales han ayudado, pero queda mucho por hacer.'",answer:["a desigualdade social no brasil é muito gritante","tem causas históricas profundas como a escravidão","os programas sociais ajudaram mas ainda há muito a fazer"],hint:"desigualdade · gritante · causas históricas · escravidão · programas sociais · ainda há muito",explanation:"A desigualdade social no Brasil é muito gritante. Tem causas históricas profundas, como a escravidão. Os programas sociais ajudaram, mas ainda há muito a fazer."},
          {id:"B1-U4-L2-E5",type:"free_writing",skill:"writing",question:"Escreva um texto argumentativo sobre desigualdade social no Brasil ou no seu país. Inclua: causas históricas, situação atual, programas existentes e propostas de melhoria. Mínimo 12 orações.",prompt:"A desigualdade social no Brasil/meu país é... / Historicamente... / Atualmente... / Os programas como... / Para resolver isso, seria necessário que...",hint:"desigualdade · causas históricas · situação atual · programas sociais · propostas com subjuntivo"}
        ]
      },
      {
        id: "B1-U4-L3",
        title: "Cultura pop e entretenimento brasileiro",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você acompanha alguma novela brasileira?\n— Acompanho! Comecei a assistir para praticar o português.\n— Qual você está vendo?\n— Uma da Globo. Estou viciada! A história é muito bem feita.\n— Novela é uma ótima forma de aprender o português coloquial.\n— Com certeza! Aprendo gírias, expressões, entonação...\n— E música? Ouve algum artista brasileiro?\n— Ouço muito sertanejo e MPB. Mas estou descobrindo o pagode também.\n— O pagode é muito rico em vocabulário e sentimento.\n— É verdade! Cada música é uma lição de português e de vida.",
        memoryPhrases: [
          "Estou viciado/a na novela!",
          "A Globo domina a TV.",
          "Ouço MPB para praticar.",
          "O pagode tem muito sentimento.",
          "Cada música é uma lição."
        ],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre como você usa a cultura pop brasileira para aprender português. O que assiste, ouve e lê. Qual é o mais útil para o aprendizado? Mínimo 7 frases.",
        content: "# Cultura Pop e Entretenimento Brasileiro\n\n## Televisão\nRede Globo = a maior emissora, domina audiência\nNovela = soap opera, fenômeno cultural único no Brasil\nHorário nobre = prime time (às 21h na Globo)\nJornal Nacional = noticiário mais assistido\nMultishow, GNT, GloboNews = canais a cabo da Globo\nRecord, SBT, Band = outras grandes emissoras\n\n## Streaming\nNetflix Brasil produz séries originais incríveis\nDisney+ · Amazon Prime · Globoplay\nGloboplay = streaming da Globo com arquivo de novelas\n\n## Música brasileira\nMPB (Música Popular Brasileira) = Chico Buarque, Milton Nascimento\nSamba = Zeca Pagodinho, Beth Carvalho\nPagode = Thiaguinho, Ferrugem\nSertanejo = Marília Mendonça, Gusttavo Lima (enorme!)\nFunk carioca = Anitta, MC Kevinho\nForró = muito popular no Nordeste\nBossa Nova = João Gilberto, Tom Jobim\nAxé = axé music da Bahia · Reggaeton brasileiro\n\n## Cinema e séries\nGloboplay, Netflix Brasil produzem muito\nO Mecanismo, Sintonia, Vai Rir do Quê?\nLinneu, Chaves no Brasil (adaptação)\n\n## Dica de aprendizado\nNovela da Globo: português coloquial real\nJornal Nacional: português formal/neutro\nPagode/MPB: vocabulário emocional rico",
        exercises: [
          {id:"B1-U4-L3-E1",type:"multiple_choice",skill:"culture",question:"¿Qué es el 'horário nobre' en la TV brasileña?",options:["El horario de la mañana","El prime time nocturno (alrededor de las 21h)","El horario de los domingos","Los programas de noticias"],answer:1,explanation:"Horário nobre = prime time. En Brasil, alrededor de las 21h, cuando la Globo pasa su novela principal.",hint:"El horario de mayor audiencia en la TV brasileña"},
          {id:"B1-U4-L3-E2",type:"fill_blank",skill:"culture",question:"O gênero musical mais popular do Brasil atualmente é o ___, representado por artistas como Gusttavo Lima e Marília Mendonça.",answer:["sertanejo"],hint:"El género que domina las paradas musicales brasileñas",explanation:"Sertanejo = el género más popular en Brasil. Una mezcla de música country brasileña con pop."},
          {id:"B1-U4-L3-E3",type:"multiple_choice",skill:"culture",question:"¿Para qué sirve el Globoplay?",options:["Una app de musica","El streaming de la Globo con novelas y series","Un canal de noticias","Una red social brasileña"],answer:1,explanation:"Globoplay = el servicio de streaming de la Rede Globo. Tiene el archivo completo de novelas.",hint:"El Netflix de la Rede Globo"},
          {id:"B1-U4-L3-E4",type:"translation",skill:"writing",question:"Traduce: 'Empecé a ver novelas brasileñas para practicar el portugués. Es una manera increíble de aprender el habla coloquial y las expresiones del día a día.'",answer:["comecei a assistir novelas brasileiras para praticar o português","é uma maneira incrível de aprender a fala coloquial e as expressões do dia a dia"],hint:"comecei a assistir · para praticar · maneira incrível · fala coloquial · expressões do dia a dia",explanation:"Comecei a assistir novelas brasileiras para praticar o português. É uma maneira incrível de aprender a fala coloquial e as expressões do dia a dia."},
          {id:"B1-U4-L3-E5",type:"free_writing",skill:"writing",question:"Escreva uma recomendação cultural para alguém que quer aprender português através da cultura brasileira. Sugira: novelas, músicas, séries, filmes e podcasts com justificativa para cada. Mínimo 10 orações.",prompt:"Para aprender português, recomendo... / Assista... porque... / Ouça... pois... / Leia... para... / A melhor forma de...",hint:"recomendo que · assista · porque ensina · ouça · pois aprende · subjuntivo nos conselhos"}
        ]
      },
      {
        id: "B1-U4-L4",
        title: "Trabalho e mercado profissional no Brasil",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você trabalha com carteira assinada ou é autônomo?\n— Sou CLT. Tenho todos os direitos trabalhistas garantidos.\n— E o 13º salário? Já recebeu?\n— Recebi em dezembro. É uma das melhores partes de ser CLT!\n— E você pensa em empreender algum dia?\n— Penso! Tenho um projeto de consultoria que quero abrir.\n— Vai ser PJ então.\n— Exatamente. A liberdade é maior, mas tenho que me preocupar com os impostos.\n— Vale a pena pesquisar bem antes de decidir.\n— Com certeza. Cada modelo tem suas vantagens e desvantagens.",
        memoryPhrases: [
          "Trabalho com carteira assinada.",
          "Tenho todos os direitos.",
          "O 13º é em dezembro.",
          "Quero empreender um dia.",
          "Cada modelo tem vantagens."
        ],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre sua experiência profissional: em que área trabalha, que tipo de contrato tem, o que gosta e não gosta do seu trabalho. Compare com o modelo de trabalho brasileiro. Mínimo 8 frases.",
        content: "# Trabalho e Mercado Profissional no Brasil\n\n## Tipos de contrato\nCLT (Consolidação das Leis do Trabalho):\n- Carteira assinada = empleo formal\n- 13º salário = aguinaldo (diciembre)\n- FGTS = fondo de desempleo\n- Férias remuneradas = 30 días al año\n- Licença maternidade/paternidade\n- Plano de saúde (en muchas empresas)\n\nPJ (Pessoa Jurídica) / Autônomo:\n- Maior liberdade e salario más alto\n- Sin derechos laborales directos\n- Responsable de sus impuestos\n- Nota fiscal obligatoria\n\nEstágio = pasantía (estudiantes)\nAprendiz = joven aprendiz\n\n## Vocabulário profissional\nrescisão = rescisión · demissão = despido\npedido de demissão = renuncia voluntaria\nsalário mínimo = salario mínimo\nholerite/contracheque = recibo de sueldo\nPIS/COFINS/IRPF = impuestos del trabajador\nplano de carreira = plan de carrera\npromoção = ascenso · bonificação = bonificación\n\n## O mercado brasileiro\nDesemprego = desempleo (≈10%)\nInformalidade = trabajo informal (≈40%)\nStartups = ecosistema fuerte en SP\nAgronegoócio = agronegocio (pilar económico)",
        exercises: [
          {id:"B1-U4-L4-E1",type:"multiple_choice",skill:"culture",question:"¿Qué es el '13º salário' en Brasil?",options:["Un bono por productividad","Un aguinaldo equivalente a un mes de sueldo pagado en diciembre","Un seguro de desempleo","Un beneficio solo para funcionarios públicos"],answer:1,explanation:"13º salário = aguinaldo de un mes de sueldo. Derecho de todos los trabajadores CLT en diciembre.",hint:"Un sueldo extra que todos los CLT reciben en diciembre"},
          {id:"B1-U4-L4-E2",type:"fill_blank",skill:"vocabulary",question:"'Trabelho com ___ assinada. Tenho todos os direitos trabalhistas.' (registro/carteira)",answer:["carteira"],hint:"O documento que formaliza o trabalho no Brasil",explanation:"Carteira assinada = empleo formal. La carteira de trabalho es el documento que formaliza el vínculo laboral."},
          {id:"B1-U4-L4-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cuál es la diferencia principal entre CLT y PJ en Brasil?",options:["CLT gana más dinero","PJ tiene derechos laborales plenos","CLT tiene derechos laborales garantizados; PJ tiene más libertad pero sin esos derechos","No hay diferencia legal"],answer:2,explanation:"CLT = derechos laborales (13º, FGTS, férias). PJ = libertad y generalmente mayor salario, pero sin esos derechos.",hint:"La diferencia fundamental entre empleo formal e informal"},
          {id:"B1-U4-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'Trabajo en relación de dependencia y tengo todos los derechos garantizados. Mi empresa da plan de salud y vale alimentación. En diciembre recibo el aguinaldo.'",answer:["trabalho com carteira assinada e tenho todos os direitos garantidos","minha empresa dá plano de saúde e vale alimentação","em dezembro recebo o décimo terceiro"],hint:"com carteira assinada · direitos garantidos · plano de saúde · vale alimentação · décimo terceiro",explanation:"Trabalho com carteira assinada e tenho todos os direitos garantidos. Minha empresa dá plano de saúde e vale alimentação. Em dezembro recebo o décimo terceiro."},
          {id:"B1-U4-L4-E5",type:"free_writing",skill:"writing",question:"Escreva sobre o sistema de trabalho ideal na sua opinião: CLT ou PJ? Quais direitos você considera essenciais? Compare com o seu país e dê sua posição argumentada. Mínimo 10 orações.",prompt:"Na minha opinião, o modelo ideal de trabalho é... / Os direitos que considero essenciais são... / No Brasil... / No meu país... / Portanto...",hint:"CLT vs PJ · direitos trabalhistas · 13º · FGTS · férias · liberdade · impostos · argumentação"}
        ]
      },
      {
        id: "B1-U4-L5",
        title: "Revisão B1 — Unidades 3 e 4",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você tem acompanhado as notícias do Brasil?\n— Tenho! É muito importante para aprender a língua no contexto real.\n— O que você achou mais interessante?\n— A questão da desigualdade social me chamou muito a atenção.\n— É um tema central na política brasileira.\n— Sim. E o sistema político é muito complexo. Muitos partidos!\n— É verdade. Mas a democracia funciona, apesar das dificuldades.\n— Defendo que um cidadão informado é fundamental para qualquer democracia.\n— Concordo totalmente. E por isso aprender português importa tanto!",
        memoryPhrases: [
          "Me chamou muito a atenção.",
          "É um tema central.",
          "A democracia funciona, apesar de...",
          "Um cidadão informado é fundamental.",
          "Por isso importa tanto!"
        ],
        oralProduction: "SITUAÇÃO ORAL: Debata sobre um tema brasileiro atual usando tudo que aprendeu: argumentação, registro formal, voz passiva, subjuntivo e vocabulário de política/sociedade. Mínimo 10 frases.",
        content: "# Revisão B1 — Unidades 3 e 4\n\n## Comunicação avançada\n✅ Estrutura de debate: tese + argumentos + refutação + conclusão\n✅ Linguagem formal vs. informal\n✅ Texto dissertativo: introdução + desenvolvimento + conclusão\n✅ Apresentação oral profissional\n✅ Comunicação não violenta\n\n## Brasil contemporâneo\n✅ Sistema político: república federativa, 3 poderes, voto obrigatório\n✅ Desigualdade: causas históricas, programas sociais, mobilidade\n✅ Cultura pop: novela, sertanejo, MPB, funk, Globo\n✅ Mercado de trabalho: CLT vs. PJ, 13º, FGTS, férias\n\n## Integração gramatical\n✅ Subjuntivo em todos os contextos\n✅ Voz passiva: SER + particípio, passiva com SE\n✅ Discurso indireto com mudanças de tempo\n✅ Verbos com preposição corretos\n✅ Gerúndio e infinitivo pessoal",
        exercises: [
          {id:"B1-U4-L5-E1",type:"multiple_choice",skill:"grammar",question:"REVISÃO — ¿Cuál usa subjuntivo futuro correctamente después de SE?",options:["Se você vá, me avisa.","Se você for, me avisa.","Se você foi, me avisa.","Se você iria, me avisa."],answer:1,explanation:"SE + condición futura → subjuntivo futuro. IR → FOR. Se você FOR, me avisa.",hint:"SE + futuro → subjuntivo futuro. IR → FOR"},
          {id:"B1-U4-L5-E2",type:"fill_blank",skill:"grammar",question:"REVISÃO PASSIVA: 'O projeto ___ pela equipe técnica na próxima semana.' (implementar — futuro passiva)",answer:["será implementado"],hint:"Passiva no futuro: SERÁ + particípio",explanation:"SERÁ IMPLEMENTADO = voz passiva no futuro. SER no futuro + particípio."},
          {id:"B1-U4-L5-E3",type:"multiple_choice",skill:"vocabulary",question:"REVISÃO — ¿Cuál connective introduce una concesión (algo verdadero pero que no cambia tu posición)?",options:["Portanto","Além disso","Apesar disso / Ainda assim","Em primeiro lugar"],answer:2,explanation:"APESAR DISSO / AINDA ASSIM = A pesar de eso / Aún así. Introduce concesión manteniendo posición.",hint:"Para introducir una concesión: a pesar de algo, tu posición se mantiene"},
          {id:"B1-U4-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'El sistema político brasileño es complejo. Aunque tenga muchos partidos, la democracia funciona. Es fundamental que los ciudadanos participen activamente.'",answer:["o sistema político brasileiro é complexo","embora tenha muitos partidos a democracia funciona","é fundamental que os cidadãos participem ativamente"],hint:"embora tenha (subj) · a democracia funciona · é fundamental que participem (subj)",explanation:"O sistema político brasileiro é complexo. Embora tenha muitos partidos, a democracia funciona. É fundamental que os cidadãos participem ativamente."},
          {id:"B1-U4-L5-E5",type:"free_writing",skill:"writing",question:"TEXTO FINAL INTEGRADO B1 U3-U4: Escreva um texto argumentativo sobre um tema social do Brasil usando: subjuntivo, voz passiva, conectivos de debate, vocabulário formal e registro adequado. Mínimo 14 orações.",prompt:"TEMA (escolha): desigualdade · sistema político · trabalho · cultura\nINTRO: Atualmente no Brasil... / ARGUMENTOS: Em primeiro lugar... / Além disso... / CONTRA: Embora... / CONCLUSÃO: Portanto...",hint:"todos os recursos B1: subj + passiva + disc indireto + verbos + ger/inf + debate + formal"}
        ]
      }
    ]
  }
];
