// A1 — Unidades 5, 6, 7, 8
export const A1_U5_U8 = [
  {
    id: "A1-U5",
    title: "Verbos no presente — o mundo ao redor",
    description: "Verbos regulares e irregulares, negação e perguntas",
    lessons: [
      {
        id: "A1-U5-L1",
        title: "Verbos -AR: falar, trabalhar, morar",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Onde você mora?\n— Moro em Belo Horizonte, mas trabalho em São Paulo.\n— Você viaja toda semana?\n— Viajo sim. Na segunda vou para SP e na sexta volto para BH.\n— E sua família mora em BH?\n— Minha esposa mora lá. Ela trabalha num hospital.\n— Que vida corrida! Mas você gosta?\n— Adoro! BH é linda e SP é incrível para trabalhar.",
        memoryPhrases: ["Onde você mora?","Moro em...","Trabalho numa empresa.","Viajo toda semana.","Gosto muito daqui."],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre sua rotina usando 6 verbos -AR diferentes. Onde mora, trabalha, o que gosta e não gosta. Conjugue corretamente.",
        content: "# Verbos -AR no Presente\n\nModelo: FALAR\neu falo · você/a gente/ele/ela fala · nós falamos · vocês/eles/elas falam\n\n## Verbos -AR essenciais\nmorar · trabalhar · estudar · gostar (de) · adorar\nviajar · comprar · almoçar · caminhar · pagar\nligar=llamar (tel.) · alugar=alquilar · descansar\n\n## Negação\nNÃO + verbo:\nEu NÃO falo espanhol. · Ela NÃO trabalha aos sábados.\n\n## Perguntas\nInversión de entonación: Você fala inglês? (misma estructura + entonación)\nPalavras interrogativas:\nO que?=¿qué? · Quem?=¿quién? · Onde?=¿dónde?\nQuando?=¿cuándo? · Por que?=¿por qué? · Como?=¿cómo?\nQuantos/as?=¿cuántos? · Qual/Quais?=¿cuál/cuáles?",
        exercises: [
          {id:"A1-U5-L1-E1",type:"multiple_choice",skill:"grammar",question:"'Eles ___ muito português no trabalho.' (falar)",options:["fala","falo","falam","falamos"],answer:2,explanation:"ELES/VOCÊS + -AR → -AM: falam.",hint:"Eles/vocês → terminação -am"},
          {id:"A1-U5-L1-E2",type:"fill_blank",skill:"grammar",question:"'Eu não ___ carne. Sou vegetariana.' (comer)",answer:["como"],hint:"NÃO + verbo normal (sin cambios)",explanation:"Eu não COMO carne. La negación: NÃO antes del verbo."},
          {id:"A1-U5-L1-E3",type:"multiple_choice",skill:"grammar",question:"¿Cuál pregunta es correcta para preguntar dónde vive alguien?",options:["Que você mora?","Onde você mora?","Como você mora?","Quem você mora?"],answer:1,explanation:"ONDE = dónde (lugar).",hint:"ONDE para lugares"},
          {id:"A1-U5-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Ella no trabaja los sábados. Generalmente descansa y camina por el parque.'",answer:["ela não trabalha aos sábados","geralmente descansa e caminha pelo parque"],hint:"não trabalha · aos sábados · caminha pelo",explanation:"Ela não trabalha aos sábados. Geralmente descansa e caminha pelo parque."},
          {id:"A1-U5-L1-E5",type:"free_writing",skill:"writing",question:"Describí tu vida usando 6 verbos -AR diferentes. Incluí positivos y negativos. Mínimo 6 oraciones.",prompt:"Eu moro em... / Trabalho... / Gosto de... / Não gosto de... / Sempre... / Nunca...",hint:"NÃO antes del verbo para negación"}
        ]
      },
      {
        id: "A1-U5-L2",
        title: "Verbos -ER e -IR: comer, beber, abrir",
        shadowing: "Lê 3 vezes em voz alta:\n\n— O que você come no almoço?\n— Como arroz, feijão e salada. Às vezes como carne.\n— Você bebe muito café?\n— Bebo três por dia! Sou brasileiro, né?\n— E seus filhos, o que eles comem?\n— Comem de tudo! Menos verduras.\n— E vocês abrem o comércio que horas?\n— Abrimos às nove.",
        memoryPhrases: ["O que você come?","Como arroz e feijão.","Você bebe café?","Bebo sim, bastante!","Abrimos às nove."],
        oralProduction: "SITUAÇÃO ORAL: Descreva o que você come e bebe em um dia típico. Use verbos -ER e -IR. Mínimo 6 frases.",
        content: "# Verbos -ER e -IR no Presente\n\n## Verbos -ER: modelo COMER\neu como · você/a gente/ele/ela come · nós comemos · vocês/eles/elas comem\n\nOutros -ER: beber · escrever · ler · vender · aprender · entender · responder · receber\n\n## Verbos -IR: modelo PARTIR\neu parto · você/a gente/ele/ela parte · nós partimos · vocês/eles/elas partem\n\nOutros -IR: abrir · assistir · dividir · existir · discutir\n\n## Irregulares -IR importantes\nSAIR: saio · sai · sai · saímos · saem\nVIR: venho · vem · vem · vimos · vêm\nOUVIR: ouço · ouve · ouve · ouvimos · ouvem\nDORMIR: durmo · dorme · dorme · dormimos · dormem",
        exercises: [
          {id:"A1-U5-L2-E1",type:"multiple_choice",skill:"grammar",question:"'Nós ___ juntos todos os dias.' (comer)",options:["come","comem","comemos","como"],answer:2,explanation:"NÓS + -ER → -EMOS: COMEMOS.",hint:"NÓS + -ER → -emos"},
          {id:"A1-U5-L2-E2",type:"fill_blank",skill:"grammar",question:"'Eu ___ música brasileira todo dia.' (ouvir — irregular)",answer:["ouço"],hint:"OUVIR es irregular para EU",explanation:"OUVIR irregular: eu OUÇO."},
          {id:"A1-U5-L2-E3",type:"multiple_choice",skill:"grammar",question:"'Ela ___ cedo todos os dias.' (sair)",options:["saio","sai","saem","saímos"],answer:1,explanation:"SAIR para ela: SAI.",hint:"SAIR para ela/você → SAI"},
          {id:"A1-U5-L2-E4",type:"translation",skill:"writing",question:"Traduce: 'Mis hijos comen mucha fruta pero no beben leche. Leen libros todos los días.'",answer:["meus filhos comem muita fruta","mas não bebem leite","leem livros todos os dias"],hint:"comem · não bebem · leem (LER irregular para eles)",explanation:"Meus filhos comem muita fruta mas não bebem leite. Leem livros todos os dias."},
          {id:"A1-U5-L2-E5",type:"free_writing",skill:"writing",question:"Describí tus hábitos usando verbos -ER e -IR. ¿Qué comés, bebés, leés, ves? Mínimo 6 oraciones.",prompt:"Como... / Bebo... / Leio... / Assisto... / Saio de casa às... / Ouço música...",hint:"Irregulares: ler→leio · ouvir→ouço · sair→saio · vir→venho"}
        ]
      },
      {
        id: "A1-U5-L3",
        title: "Perguntas e respostas — conversação básica",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você fala inglês?\n— Falo um pouco. Por quê?\n— Porque temos um cliente americano amanhã.\n— Entendi. O que ele quer comprar?\n— Não sei ainda. Você pode ajudar na reunião?\n— Claro! A que horas é?\n— Às duas da tarde.\n— Ótimo! Onde vai ser?\n— Na sala de reuniões do quinto andar.",
        memoryPhrases: ["Você fala inglês?","Falo um pouco.","Por quê?","O que você quer?","Claro! Pode contar comigo."],
        oralProduction: "SITUAÇÃO ORAL: Faça e responda 8 perguntas em português sobre sua rotina e preferências. Alterne perguntar e responder.",
        content: "# Perguntas e Respostas\n\n## Palavras interrogativas\nO que? / Que? = ¿qué? → O que você faz?\nQuem? = ¿quién? → Quem é esse?\nOnde? = ¿dónde? → Onde você mora?\nQuando? = ¿cuándo? → Quando você chega?\nPor que? = ¿por qué? → Por que você estuda?\nPorque = porque (resposta)\nComo? = ¿cómo? · Quantos/as? · Qual/Quais?\n\n## Respondendo\nSim · Não · Talvez · Claro! · Com certeza!\nNão sei. · Acho que sim/não.\n\n## Pedindo esclarecimento\nPode repetir? · Pode falar mais devagar?\nNão entendi. · O que significa...?\nComo se diz... em português?",
        exercises: [
          {id:"A1-U5-L3-E1",type:"multiple_choice",skill:"grammar",question:"¿Cuál pregunta para saber dónde vive alguien?",options:["O que você mora?","Quem você mora?","Onde você mora?","Por que você mora?"],answer:2,explanation:"ONDE = dónde (lugar).",hint:"ONDE para lugares"},
          {id:"A1-U5-L3-E2",type:"fill_blank",skill:"grammar",question:"'___ você estuda português?' (¿por qué?)",answer:["por que","por quê"],hint:"La pregunta sobre la razón",explanation:"Por que? = ¿Por qué? (pregunta). Porque = porque (respuesta)."},
          {id:"A1-U5-L3-E3",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo pedís que alguien hable más despacio?",options:["Pode repetir?","Pode falar mais devagar?","Não entendi nada.","Fala mais rápido!"],answer:1,explanation:"Pode falar mais devagar? = ¿Podés hablar más despacio?",hint:"Devagar = despacio"},
          {id:"A1-U5-L3-E4",type:"translation",skill:"writing",question:"Traduce: '¿Por qué estudiás português? — Porque me gusta Brasil y quiero viajar allá.'",answer:["por que você estuda português","porque gosto do brasil e quero viajar para lá"],hint:"por que (pregunta) · porque (respuesta) · gosto do · para lá=para allá",explanation:"Por que você estuda português? — Porque gosto do Brasil e quero viajar para lá."},
          {id:"A1-U5-L3-E5",type:"free_writing",skill:"writing",question:"Escribí 6 preguntas que le harías a un brasileño. Después respondé las 6 como si fueras esa persona.",prompt:"Perguntas: Onde você mora? / ...\nRespostas: Moro em... / ...",hint:"Usá: onde · o que · quando · por que · como · quantos · qual"}
        ]
      },
      {
        id: "A1-U5-L4",
        title: "PODER, DEVER e PRECISAR",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Posso usar seu carregador?\n— Claro, pode sim!\n— Você pode me ajudar com esse formulário?\n— Posso! Mas preciso terminar essa ligação primeiro.\n— Sem problema. Aliás, você deve levar um documento com foto.\n— Devo? Que documento?\n— RG ou passaporte. É obrigatório.\n— Entendi. Tenho aqui na bolsa.",
        memoryPhrases: ["Posso...?","Pode sim! / Não pode.","Você pode me ajudar?","Preciso terminar primeiro.","Você deve trazer..."],
        oralProduction: "SITUAÇÃO ORAL: Você é novo no trabalho. Pergunte ao colega 5 coisas que pode ou não pode fazer. Ele explica o que você deve e precisa fazer.",
        content: "# PODER, DEVER e PRECISAR\n\n## PODER (poder)\neu posso · você/a gente/ele/ela pode · nós podemos · vocês/eles/elas podem\nPermissão: Posso entrar? / Não pode.\nCapacidade: Você pode me ajudar?\n\n## DEVER (deber)\neu devo · você/a gente/ele/ela deve · nós devemos · vocês/eles/elas devem\nObligación moral: Você deve chegar no horário.\nProbabilidad: Ele deve estar em reunião.\n\n## PRECISAR (necesitar)\neu preciso · você/a gente/ele/ela precisa · nós precisamos · vocês/eles/elas precisam\nNecessidad: Preciso de ajuda. / Preciso estudar.\n\n## Comparação\nPODER = posibilidad/permiso: Posso sair? (¿puedo?)\nDEVER = obligación moral: Devo ligar. (debo llamar)\nPRECISAR = necesidad: Preciso dormir. (necesito)\nTER QUE = obligación fuerte: Tenho que pagar. (tengo que)",
        exercises: [
          {id:"A1-U5-L4-E1",type:"multiple_choice",skill:"grammar",question:"'___ usar o banheiro?' (pedir permiso)",options:["Devo","Preciso de","Posso","Tenho que"],answer:2,explanation:"POSSO = ¿Puedo? Para pedir permiso.",hint:"Para permiso = PODER"},
          {id:"A1-U5-L4-E2",type:"fill_blank",skill:"grammar",question:"'Você ___ chegar no horário. É importante.' (deber — obligación moral)",answer:["deve"],hint:"Obligación moral → DEVER",explanation:"DEVER para obligación moral. Você DEVE chegar no horário."},
          {id:"A1-U5-L4-E3",type:"multiple_choice",skill:"grammar",question:"¿Cuál expresa necesidad?",options:["Posso ir embora.","Deve ser fácil.","Preciso de um médico.","Você pode me ajudar?"],answer:2,explanation:"PRECISAR = necesitar. Preciso de um médico.",hint:"PRECISAR = necesitar"},
          {id:"A1-U5-L4-E4",type:"translation",skill:"writing",question:"Traduce: '¿Puedo pagar con tarjeta? — No puede, solo efectivo. Necesitás pagar hoy.'",answer:["posso pagar com cartão","não pode apenas dinheiro","você precisa pagar hoje"],hint:"posso pagar com · apenas=solo · precisa pagar hoje",explanation:"Posso pagar com cartão? — Não pode, apenas dinheiro. Você precisa pagar hoje."},
          {id:"A1-U5-L4-E5",type:"free_writing",skill:"writing",question:"Describí tu situación actual usando PODER, DEVER, PRECISAR e TER QUE. Mínimo 6 oraciones.",prompt:"Posso... / Não posso... / Preciso de... / Preciso... / Devo... / Tenho que...",hint:"Pensá en trabajo, estudio, salud o vida personal"}
        ]
      },
      {
        id: "A1-U5-L5",
        title: "Verbo ESTAR e os estados",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Oi! Como você está?\n— Estou ótima! Um pouco cansada, mas feliz.\n— Por que cansada?\n— Estamos com muito trabalho esta semana. E você?\n— Estou bem, mas preocupado. Meu filho está doente.\n— Que pena! Onde ele está agora?\n— Está no médico com minha esposa.\n— Espero que melhore logo!",
        memoryPhrases: ["Como você está?","Estou ótimo/a!","Estou cansado/a.","Ela está doente.","Espero que melhore!"],
        oralProduction: "SITUAÇÃO ORAL: Descreva como estão as pessoas da sua família ou amigos hoje. Use ESTAR com diferentes adjetivos para cada pessoa. Mínimo 5 frases.",
        content: "# Verbo ESTAR e os Estados\n\n## Conjugação\neu estou · você/a gente/ele/ela está · nós estamos · vocês/eles/elas estão\n\n## Estados físicos\ncansado/a · descansado/a · doente · saudável\ncom febre · com dor · em boa forma · fraco/a\n\n## Estados emocionais\nfeliz · triste · animado/a · preocupado/a\nnervoso/a · bravo/a=enojado · ansioso/a\nentusiasmado/a · estressado/a\n\n## Estados de ânimo\nótimo/a=excelente · bem · mais ou menos\nmal · péssimo/a\n\n## ESTAR + lugar\nEstou em casa / no trabalho / no hospital.\n\n## ESTAR + gerúndio = ação em progresso\nEstou trabalhando. · Ela está estudando.\n\n## SER vs ESTAR resumo\nSER = permanente: Ela é alta. (siempre)\nESTAR = temporal: Ela está cansada. (hoy)",
        exercises: [
          {id:"A1-U5-L5-E1",type:"multiple_choice",skill:"grammar",question:"'Minha mãe ___ doente hoje.' (estar)",options:["é","sou","está","somos"],answer:2,explanation:"ESTAR para estado temporal. Doente hoje = hoy, no siempre.",hint:"Estado temporal → ESTAR"},
          {id:"A1-U5-L5-E2",type:"fill_blank",skill:"grammar",question:"'Nós ___ com muito trabalho esta semana.' (estar)",answer:["estamos"],hint:"ESTAR para nós",explanation:"ESTAR para NÓS = ESTAMOS."},
          {id:"A1-U5-L5-E3",type:"multiple_choice",skill:"grammar",question:"¿Cuál usa ESTAR + gerúndio correctamente?",options:["Ela está feliz.","Estou trabalhando agora.","Ele é cansado.","Estamos doentes."],answer:1,explanation:"ESTAR + gerúndio: Estou trabalhando = Estoy trabajando.",hint:"ESTAR + -ando/-endo = acción en progreso"},
          {id:"A1-U5-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'Estoy muy cansado hoy. Mis hijos están enojados porque están sin internet. Mi esposa está trabajando hasta tarde.'",answer:["estou muito cansado hoje","meus filhos estão bravos porque estão sem internet","minha esposa está trabalhando até tarde"],hint:"cansado · bravos=enojados · sem=sin · trabalhando · até tarde",explanation:"Estou muito cansado hoje. Meus filhos estão bravos porque estão sem internet. Minha esposa está trabalhando até tarde."},
          {id:"A1-U5-L5-E5",type:"free_writing",skill:"writing",question:"Describí cómo estás vos y las personas cercanas ahora mismo. Usá estados físicos, emocionales y de lugar. Mínimo 6 oraciones.",prompt:"Agora eu estou... / Minha família está... / No trabalho... / Hoje em geral...",hint:"Agora=ahora · Hoje=hoy · Recordá: ESTAR para lo temporal"}
        ]
      }
    ]
  },
  {
    id: "A1-U6",
    title: "O passado — memórias e histórias",
    description: "Pretérito Perfeito e Imperfeito para contar histórias",
    lessons: [
      {
        id: "A1-U6-L1",
        title: "Pretérito Perfeito — verbos regulares",
        shadowing: "Lê 3 vezes em voz alta:\n\n— O que você fez ontem à noite?\n— Cozinhei um jantar especial para minha esposa.\n— Que romântico! O que preparou?\n— Preparei um risoto e abrimos uma garrafa de vinho.\n— Ela gostou?\n— Adorou! Depois assistimos a um filme e dormimos cedo.\n— Perfeito! Você é muito romântico!",
        memoryPhrases: ["O que você fez ontem?","Ontem eu fui ao...","Comemos juntos.","Ela adorou!","Foi ótimo!"],
        oralProduction: "SITUAÇÃO ORAL: Conte o que você fez no último fim de semana. Use 6 verbos no Pretérito Perfeito. Fale como contando para um amigo.",
        content: "# Pretérito Perfeito — Regulares\n\n## Quando usar\nAção COMPLETA e PONTUAL no passado:\nOntem fui ao mercado. / Ela comeu pizza na sexta.\n\n## Conjugação\nVerbos -AR (falar):\neu falei · você/a gente/ele/ela falou · nós falamos · vocês/eles/elas falaram\n\nVerbos -ER (comer):\neu comi · você/a gente/ele/ela comeu · nós comemos · vocês/eles/elas comeram\n\nVerbos -IR (partir):\neu parti · você/a gente/ele/ela partiu · nós partimos · vocês/eles/elas partiram\n\n> NÓS no pretérito = NÓS no presente para -AR e -IR\n> Nós falamos (agora) = Nós falamos (ontem) — el contexto define!\n\n## Marcadores de tempo\nontem · anteontem · hoje de manhã · na semana passada\nno mês/ano passado · há dois dias · já · ainda não",
        exercises: [
          {id:"A1-U6-L1-E1",type:"multiple_choice",skill:"grammar",question:"'Ontem ela ___ um jantar delicioso.' (cozinhar)",options:["cozinha","cozinhamos","cozinhou","cozinhei"],answer:2,explanation:"Pretérito de COZINHAR para ELA: COZINHOU. Verbo -AR, 3ª: -ou.",hint:"Verbo -AR, 3ª persona → -ou"},
          {id:"A1-U6-L1-E2",type:"fill_blank",skill:"grammar",question:"'Na semana passada, a gente ___ ao cinema.' (ir)",answer:["foi"],hint:"Pretérito de IR para a gente (= 3ª persona)",explanation:"IR/SER: eu fui · você/a gente/ele/ela foi · nós fomos · eles foram."},
          {id:"A1-U6-L1-E3",type:"multiple_choice",skill:"grammar",question:"'Vocês ___ a festa?' (curtir — gozar la fiesta)",options:["curtiram","curtiu","curtimos","curtei"],answer:0,explanation:"VOCÊS/ELES + -IR → -IRAM: curtiram.",hint:"Vocês/eles + -IR → -iram"},
          {id:"A1-U6-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Ayer trabajé hasta las 8, comí una pizza y vi una serie. Dormí muy bien.'",answer:["ontem trabalhei até as oito","comi uma pizza","assisti a uma série","dormi muito bem"],hint:"trabalhei · comi · assisti (assistir→assisti) · dormi",explanation:"Ontem trabalhei até as oito, comi uma pizza e assisti a uma série. Dormi muito bem."},
          {id:"A1-U6-L1-E5",type:"free_writing",skill:"writing",question:"Contá tu último fin de semana en detalle desde el viernes hasta el domingo. Mínimo 7 oraciones.",prompt:"Na sexta à noite... / No sábado de manhã... / À tarde... / À noite... / No domingo...",hint:"Usa: depois · logo depois · então · antes · mais tarde"}
        ]
      },
      {
        id: "A1-U6-L2",
        title: "Pretérito Perfeito — verbos irregulares",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você viu aquele filme novo?\n— Vi sim! Fui ao cinema sábado com minha namorada.\n— Ela gostou?\n— Amou! Disse que foi o melhor filme do ano.\n— E o que vocês fizeram depois?\n— Fomos jantar num restaurante japonês. Foi incrível!\n— Você teve que pagar tudo?\n— Claro que não! A gente sempre divide a conta.",
        memoryPhrases: ["Você viu...?","Vi sim! Foi ótimo!","Fui ao cinema.","O que você fez?","Eu disse que..."],
        oralProduction: "SITUAÇÃO ORAL: Conte uma experiência memorável usando 5 verbos irregulares no pretérito (ir/ser, ter, fazer, ver, vir, dar). Fale com emoção.",
        content: "# Pretérito Perfeito — Irregulares\n\n## Os mais importantes\n\nSER/IR (mismo pretérito!):\neu fui · você/a gente/ele/ela foi · nós fomos · vocês/eles/elas foram\n\nTER:\neu tive · você/a gente/ele/ela teve · nós tivemos · vocês/eles/elas tiveram\n\nFAZER:\neu fiz · você/a gente/ele/ela fez · nós fizemos · vocês/eles/elas fizeram\n\nVIR:\neu vim · você/a gente/ele/ela veio · nós viemos · vocês/eles/elas vieram\n\nVER:\neu vi · você/a gente/ele/ela viu · nós vimos · vocês/eles/elas viram\n\nDAR:\neu dei · você/a gente/ele/ela deu · nós demos · vocês/eles/elas deram\n\nDIZER:\neu disse · você/a gente/ele/ela disse · nós dissemos · vocês/eles/elas disseram\n\n## Dica\nSER e IR tienen el MISMO pretérito. Solo el contexto diferencia:\nEu fui médico. (SER) vs Eu fui ao hospital. (IR)",
        exercises: [
          {id:"A1-U6-L2-E1",type:"multiple_choice",skill:"grammar",question:"'Ontem ela ___ ao parque correr.' (ir)",options:["vai","foi","iam","vão"],answer:1,explanation:"IR para ELA no pretérito: FOI.",hint:"IR para ela no pretérito → FOI"},
          {id:"A1-U6-L2-E2",type:"fill_blank",skill:"grammar",question:"'O que você ___ no fim de semana?' (fazer — pretérito para você)",answer:["fez"],hint:"FAZER pretérito para você/ela/ele",explanation:"FAZER: eu fiz · você/a gente/ele/ela FEZ · nós fizemos."},
          {id:"A1-U6-L2-E3",type:"multiple_choice",skill:"grammar",question:"'Nós ___ um problema na viagem.' (ter — pretérito)",options:["temos","tivemos","teve","tinham"],answer:1,explanation:"TER para NÓS no pretérito: TIVEMOS.",hint:"TER para nós → TIVEMOS"},
          {id:"A1-U6-L2-E4",type:"translation",skill:"writing",question:"Traduce: 'El año pasado fui a Brasil por primera vez. Vi las cataratas del Iguazú y comí feijoada. Fue increíble.'",answer:["no ano passado fui ao brasil pela primeira vez","vi as cataratas do iguaçu","comi feijoada","foi incrível"],hint:"no ano passado · fui ao · pela primeira vez · vi · comi · foi incrível",explanation:"No ano passado fui ao Brasil pela primeira vez. Vi as cataratas do Iguaçu e comi feijoada. Foi incrível!"},
          {id:"A1-U6-L2-E5",type:"free_writing",skill:"writing",question:"Contá la mejor experiencia de tu vida usando el pretérito. Usa 5 verbos irregulares. Mínimo 6 oraciones.",prompt:"A melhor experiência da minha vida foi quando... / Fui a... / Vi... / Fiz... / Tive...",hint:"fui · foi · fomos · vim · veio · fiz · fez · vi · viu · tive · teve"}
        ]
      },
      {
        id: "A1-U6-L3",
        title: "Pretérito Imperfeito — hábitos e memórias",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Como era sua infância?\n— Era maravilhosa! A gente morava numa cidade pequena.\n— O que você fazia nas férias?\n— Brincava na rua com os amigos o dia todo. Não tinha celular!\n— Que saudade de uma vida mais simples.\n— É verdade. Antes a vida era mais tranquila.\n— E seus pais? O que eles faziam?\n— Meu pai trabalhava numa fábrica e minha mãe ficava em casa.",
        memoryPhrases: ["Quando era criança...","Antes a gente...","Naquela época...","Meu pai/mãe trabalhava...","A vida era mais..."],
        oralProduction: "SITUAÇÃO ORAL: Descreva sua infância: onde morava, o que fazia nas férias, como era sua casa, o que seus pais faziam. Mínimo 6 frases.",
        content: "# Pretérito Imperfeito\n\n## Quando usar\n1. HÁBITO no passado: Quando criança, eu brincava muito.\n2. DESCRIÇÃO no passado: A casa era grande. Ele estava cansado.\n3. AÇÃO EM PROGRESSO quando outra ocorreu: Eu dormia quando o telefone tocou.\n4. CONTEXTO de narrativa: Era uma noite fria...\n\n## Conjugação\nVerbos -AR: falava/falava/falava/falávamos/falavam\nVerbos -ER: comia/comia/comia/comíamos/comiam\nVerbos -IR: partia/partia/partia/partíamos/partiam\n\n## Irregulares (poucos!)\nSER: era/era/era/éramos/eram\nTER: tinha/tinha/tinha/tínhamos/tinham\nIR: ia/ia/ia/íamos/iam\n\n## Perfeito vs Imperfeito\nPerfeito (puntual): Ontem COMI pizza. (una vez)\nImperfeito (hábito): Quando criança, COMIA pizza toda semana.\nCombinados: Eu DORMIA quando o telefone TOCOU.",
        exercises: [
          {id:"A1-U6-L3-E1",type:"multiple_choice",skill:"grammar",question:"'Quando criança, ela ___ muito na rua.' (brincar — hábito)",options:["brincou","brinca","brincava","brincaram"],answer:2,explanation:"Hábito en el pasado → IMPERFEITO: BRINCAVA.",hint:"Hábito pasado → Imperfeito (-ava)"},
          {id:"A1-U6-L3-E2",type:"fill_blank",skill:"grammar",question:"'A casa ___ muito grande e bonita.' (ser — descripción pasada)",answer:["era"],hint:"SER en imperfeito para a casa",explanation:"SER en Imperfeito: ERA."},
          {id:"A1-U6-L3-E3",type:"multiple_choice",skill:"grammar",question:"'Eu ___ (dormir) quando ele ___ (chegar).'",options:["dormia/chegou","dormiu/chegava","dorme/chegou","dormia/chegava"],answer:0,explanation:"DORMIA (fondo/imperfeito) + CHEGOU (acción puntual/perfeito).",hint:"Fondo = imperfeito · Acción puntual = perfeito"},
          {id:"A1-U6-L3-E4",type:"translation",skill:"writing",question:"Traduce: 'Antes vivíamos en el campo. Los niños jugaban afuera y no había internet ni celulares.'",answer:["antes morávamos no campo","as crianças brincavam lá fora","não tinha internet nem celulares"],hint:"antes · morávamos · brincavam · não tinha · nem=ni",explanation:"Antes morávamos no campo. As crianças brincavam lá fora e não tinha internet nem celulares."},
          {id:"A1-U6-L3-E5",type:"free_writing",skill:"writing",question:"Describí cómo era tu vida hace 10 años. Mínimo 6 oraciones.",prompt:"Dez anos atrás, eu morava em... / Estudava... / Todos os dias... / Era... / Tinha...",hint:"era · morava · estudava · trabalhava · ia · tinha · brincava"}
        ]
      },
      {
        id: "A1-U6-L4",
        title: "Contar histórias — narração básica",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você sabia que conheci minha esposa num ônibus?\n— De verdade? Conta!\n— Era uma manhã de segunda-feira. Eu estava no ônibus quando ela entrou.\n— E aí?\n— A gente começou a conversar e não parou mais!\n— Que história linda! Quanto tempo faz isso?\n— Quinze anos! E ainda somos muito apaixonados.",
        memoryPhrases: ["Era uma vez...","De repente...","E então...","No fim...","Que história!"],
        oralProduction: "SITUAÇÃO ORAL: Conte uma história curta mas completa do seu passado. Use Perfeito e Imperfeito. Mínimo 8 frases.",
        content: "# Contar Histórias em Português\n\n## Estrutura da narrativa\n1. CONTEXTO (Imperfeito): Era uma terça-feira. Eu estava no trabalho...\n2. ACONTECIMENTO (Perfeito): De repente, recebi uma ligação...\n3. REAÇÃO (Perfeito): Fiquei surpreso e fui imediatamente...\n4. RESULTADO: No fim tudo deu certo!\n\n## Conectores narrativos\nprimeiro · depois · em seguida · então · aí=entonces (coloquial)\nde repente · logo=pronto · no fim · por fim=finalmente\nporém · mas · enquanto · quando\n\n## Expressões para narrar\nEra uma vez... · Tudo começou quando...\nO mais incrível foi que... · No fim das contas...\n\n## Reações\nQue incrível! · Que lindo! · Que pena! · Que susto!\nNão acredito! · Que coincidência! · Que sorte! · Que azar!",
        exercises: [
          {id:"A1-U6-L4-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Qué conector introducís para un evento inesperado?",options:["Primeiro","De repente","No fim","Enquanto"],answer:1,explanation:"De repente = de repente. Para el evento sorpresivo.",hint:"Para el evento inesperado/sorpresa"},
          {id:"A1-U6-L4-E2",type:"fill_blank",skill:"vocabulary",question:"'___ aconteceu quando eu menos esperava.' (Todo empezó cuando)",answer:["tudo começou quando","tudo aconteceu quando"],hint:"La frase para iniciar una historia",explanation:"Tudo começou quando... = Todo empezó cuando..."},
          {id:"A1-U6-L4-E3",type:"multiple_choice",skill:"grammar",question:"En una narración, ¿qué tiempo para el CONTEXTO/FONDO?",options:["Pretérito Perfeito","Presente","Pretérito Imperfeito","Futuro"],answer:2,explanation:"El Imperfeito para el CONTEXTO: Era, estava, havia...",hint:"El tiempo para describir la situación de fondo"},
          {id:"A1-U6-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'Era un día lluvioso. Yo esperaba el autobús cuando de repente vi a mi ex. Corrí y entré al primer taxi.'",answer:["era um dia chuvoso","eu estava esperando o ônibus","quando de repente vi meu ex","corri e entrei no primeiro táxi"],hint:"chuvoso=lluvioso · esperando · vi (VER) · corri · entrei",explanation:"Era um dia chuvoso. Eu estava esperando o ônibus quando de repente vi meu ex. Corri e entrei no primeiro táxi."},
          {id:"A1-U6-L4-E5",type:"free_writing",skill:"writing",question:"Escribí una historia completa (8-10 oraciones) usando Imperfeito para el contexto y Perfeito para las acciones. Puede ser real o inventada.",prompt:"Era... (contexto) / Eu estava... / De repente... / Então... / No fim...",hint:"Imperfeito: era · estava · havia · tinha · fazia\nPerfeito: fui · vi · disse · fez · chegou"}
        ]
      },
      {
        id: "A1-U6-L5",
        title: "Revisão e integração do nível A1",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Olá! Sou a Maria, sou brasileira de Salvador.\n— Prazer! Quanto tempo você está aqui?\n— Estou aqui há seis meses. Vim estudar português avançado.\n— Mas você já fala muito bem!\n— Obrigada! Estudo todos os dias. Antes não falava nada.\n— E o que você mais gosta aqui?\n— A comida e as pessoas! Todos são muito simpáticos.",
        memoryPhrases: ["Já falo bem!","Estudo todos os dias.","Consigo me comunicar.","O que você mais gosta?","Todos são simpáticos!"],
        oralProduction: "AVALIAÇÃO A1: Fale por 2 minutos sem parar: quem você é, onde mora, sua rotina, família, o que fez no último fim de semana e seus planos futuros. Grave se possível e escute depois.",
        content: "# Revisão Geral — Nível A1\n\n## O que você aprendeu\n\n### Gramática\n✅ SER e ESTAR — usos e diferenças\n✅ Pronomes: eu, você, a gente, ele/ela, nós, vocês, eles/elas\n✅ Verbos -AR, -ER, -IR no presente\n✅ Irregulares: ir, ter, fazer, poder, querer, saber, sair, vir, ouvir\n✅ Pretérito Perfeito — regulares e irregulares\n✅ Pretérito Imperfeito — hábitos e descrições\n✅ Negação com NÃO\n✅ Palavras interrogativas\n✅ PODER, DEVER, PRECISAR, TER QUE\n✅ IR + infinitivo para o futuro\n✅ Preposições e contrações (ao, à, no, na, do, da)\n\n### Vocabulário\n✅ +500 palavras em contexto real\n✅ Saludos, números, colores, familia, casa\n✅ Ropa, comida, rutina, ciudad, transporte\n✅ Profesiones, salud, cultura brasileña\n\n## Metas para o A2\n→ Mais verbos e tempos verbais\n→ Conectivos para argumentar\n→ Vocabulário temático avanzado\n→ Subjuntivo básico",
        exercises: [
          {id:"A1-U6-L5-E1",type:"multiple_choice",skill:"grammar",question:"¿Cuál usa SER y ESTAR correctamente?",options:["Ela é cansada hoje.","Ela está médica.","Ela é médica e está cansada hoje.","Ela tem médica."],answer:2,explanation:"SER (identidade permanente: médica) + ESTAR (estado temporal: cansada hoje).",hint:"SER=permanente · ESTAR=temporal"},
          {id:"A1-U6-L5-E2",type:"fill_blank",skill:"grammar",question:"'Ontem eu ___ ao mercado e ___ muita fruta.' (ir, comprar)",answer:["fui","comprei"],hint:"IR irregular: fui · COMPRAR regular: comprei",explanation:"Fui ao mercado + comprei muita fruta. Ambos Pretérito Perfeito."},
          {id:"A1-U6-L5-E3",type:"multiple_choice",skill:"grammar",question:"'Quando criança, ela ___ muito e ___ muitos amigos.' (brincar/ter — hábito)",options:["brincou/teve","brincava/tinha","brinca/tem","brincava/teve"],answer:1,explanation:"Hábito pasado → todo en Imperfeito: BRINCAVA + TINHA.",hint:"Hábito pasado → todo en Imperfeito"},
          {id:"A1-U6-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'Me llamo Ana, soy argentina y vivo en Buenos Aires. Ayer fui al mercado, hablé con mi profesora y practiqué mucho.'",answer:["me chamo ana","sou argentina e moro em buenos aires","ontem fui ao mercado","falei com minha professora","pratiquei muito"],hint:"me chamo · sou · moro · ontem fui · falei · pratiquei",explanation:"Me chamo Ana, sou argentina e moro em Buenos Aires. Ontem fui ao mercado, falei com minha professora e pratiquei muito."},
          {id:"A1-U6-L5-E5",type:"free_writing",skill:"writing",question:"AVALIAÇÃO: Escribí un texto de 10 oraciones sobre vos. Incluí: presentación, rutina, familia, pasado y planes futuros. Demostrá todo lo del nivel A1.",prompt:"Me chamo... / Sou de... / Tenho... anos / Moro em... / Todos os dias... / Minha família... / No último fim de semana... / No futuro quero...",hint:"SER · ESTAR · presente · perfeito · imperfeito · IR + infinitivo"}
        ]
      }
    ]
  },
  {
    id: "A1-U7",
    title: "Brasil: cultura e expressões",
    description: "Cultura brasileña, gírias y vida cotidiana",
    lessons: [
      {
        id: "A1-U7-L1",
        title: "O Brasil e sua cultura",
        shadowing: "Lê 3 vezes em voz alta:\n\n— O que você sabe sobre o Brasil?\n— Sei que é o maior país da América do Sul e fala português.\n— E sabe qual é a capital?\n— Brasília, né? Mas achei que era Rio de Janeiro!\n— Muita gente pensa isso! A capital foi mudada em 1960.\n— O Rio é a mais famosa?\n— Com certeza! Tem o Cristo Redentor, o Carnaval, as praias...\n— Que país incrível! Quero muito visitar!",
        memoryPhrases: ["O Brasil é um país incrível!","A capital é Brasília.","O Rio tem o Cristo Redentor.","O Brasil fala português.","Quero muito visitar!"],
        oralProduction: "SITUAÇÃO ORAL: Apresente o Brasil para um amigo que nunca ouviu falar do país. Mencione: localização, capital, idioma, 3 cidades e 3 coisas famosas. 2 minutos.",
        content: "# O Brasil e Sua Cultura\n\n## Dados básicos\nNome: República Federativa do Brasil\nCapital: Brasília (desde 1960)\nIdioma: Português (único na América do Sul!)\nPopulação: ~215 milhões (5° mais populoso)\nÁrea: 8,5 milhões km² (5° maior)\nMoeda: Real (R$)\n\n## Cidades famosas\nSão Paulo · Rio de Janeiro · Salvador · Manaus\nRecife · Belo Horizonte · Curitiba · Porto Alegre\n\n## O que o Brasil é famoso\nCarnaval=el más grande del mundo\nFutebol=5 títulos mundiais · Amazônia\nMúsica: samba · bossa nova · forró · funk\nComida: churrasco · feijoada · açaí · caipirinha\n+7.000 km de litoral\n\n## Expressões culturais\nSaudade=nostalgia intraducible\nJeito brasileiro=manera de resolver problemas\nGinga=elegancia, habilidad",
        exercises: [
          {id:"A1-U7-L1-E1",type:"multiple_choice",skill:"culture",question:"¿Cuál es la capital de Brasil?",options:["Rio de Janeiro","São Paulo","Brasília","Salvador"],answer:2,explanation:"Brasília es la capital desde 1960, diseñada por Oscar Niemeyer.",hint:"No es Rio de Janeiro (error muy común)"},
          {id:"A1-U7-L1-E2",type:"fill_blank",skill:"culture",question:"El único país de habla portuguesa en las Américas es ___.",answer:["brasil","o brasil"],hint:"El país más grande de América del Sur",explanation:"Brasil é o único país de língua portuguesa nas Américas."},
          {id:"A1-U7-L1-E3",type:"multiple_choice",skill:"culture",question:"¿Cuántos títulos mundiales de fútbol tiene Brasil?",options:["3","4","5","6"],answer:2,explanation:"Brasil tem 5 títulos mundiais de futebol.",hint:"El más ganador del mundo"},
          {id:"A1-U7-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Brasil es el quinto país más grande del mundo y tiene más de 200 millones de habitantes.'",answer:["o brasil é o quinto maior país do mundo","tem mais de duzentos milhões de habitantes"],hint:"o quinto maior · mais de · duzentos milhões de habitantes",explanation:"O Brasil é o quinto maior país do mundo. Tem mais de duzentos milhões de habitantes."},
          {id:"A1-U7-L1-E5",type:"free_writing",skill:"writing",question:"Comparé tu país con Brasil en 5 aspectos: tamaño, capital, idioma, comida, música. Mínimo 5 oraciones.",prompt:"No meu país... / Já no Brasil... / Em comparação... / O que os dois têm em comum é... / O que é muito diferente é...",hint:"Em comparação · já=pero · em comum · mais diferente"}
        ]
      },
      {
        id: "A1-U7-L2",
        title: "Gírias e expressões coloquiais",
        shadowing: "Lê 3 vezes em voz alta:\n\n— E aí, tá bom?\n— Tô ótimo! Que saudade de você!\n— Também! Faz tempo que a gente não se vê!\n— O que você tá aprontando?\n— Nada não! Trabalhando muito. Tô destruído.\n— Precisa dar uma relaxada, mano.\n— Verdade. Esse fim de semana vou dar um rolê.",
        memoryPhrases: ["Tá bom! / Tô bem!","Que saudade!","Que pena!","Tô destruído/a.","Vou dar um rolê."],
        oralProduction: "SITUAÇÃO ORAL: Use 5 expressões coloquiais numa conversa simulada com um amigo. Fale natural, como no dia a dia.",
        content: "# Gírias e Expressões Coloquiais\n\n## Saudações coloquiais\nE aí! = ¡Qué hay! / ¡Hola!\nTá bom! / Tô bem! · Tá ótimo!\nNada não = nada (enfático)\n\n## Expressões de emoção\nQue saudade! = ¡Cuánto te extrañé!\nQue pena! = ¡Qué lástima!\nQue legal! = ¡Qué bueno! / ¡Genial!\nQue chato! = ¡Qué fastidio!\nNossa! / Minha nossa! = ¡Oh! / ¡Dios mío!\n\n## Expressões de estado\nTô destruído/a = estoy agotado (muy cansado)\nTô na fossa = estoy deprimido\nTô de boa = estoy tranquilo/bien\nTô com saudade = estoy nostálgico\n\n## Expressões de situação\nDar um rolê = salir a dar una vuelta\nDar um jeito = encontrar una solución\nQue mico! = ¡Qué vergüenza!\nTá de sacanagem! = ¡Estás bromeando!\n\n## Tratamentos informales\nmano/mana = tío/tía · cara = tío (SP)\nbrother = amigo · chefe = jefe (cariñoso)",
        exercises: [
          {id:"A1-U7-L2-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Qué significa 'Que legal!' en contexto positivo?",options:["¡Qué legal (jurídico)!","¡Qué bueno! / ¡Genial!","¡Qué problema!","¡Qué aburrido!"],answer:1,explanation:"Que legal! = ¡Qué bueno! / ¡Genial! No tiene nada que ver con legal en español.",hint:"Expresión muy positiva"},
          {id:"A1-U7-L2-E2",type:"fill_blank",skill:"vocabulary",question:"'Preciso ___ um jeito para resolver esse problema.'",answer:["dar"],hint:"DAR um jeito = encontrar solución",explanation:"Dar um jeito = encontrar una solución."},
          {id:"A1-U7-L2-E3",type:"multiple_choice",skill:"vocabulary",question:"Un amigo dice 'Tô destruído hoje'. ¿Qué significa?",options:["Está muy feliz","Está muy enfermo","Está muy cansado/agotado","Está muy ocupado"],answer:2,explanation:"Tô destruído = estoy destruido = muy cansado/agotado.",hint:"Hipérbole para el cansancio extremo"},
          {id:"A1-U7-L2-E4",type:"translation",skill:"writing",question:"Traduce estas expresiones: '¡Cuánto te extrañé! / ¡Qué vergüenza! / Estoy bien / ¿Estás bromeando?'",answer:["que saudade","que mico","tô de boa","tá de sacanagem"],hint:"saudade · mico · de boa · sacanagem",explanation:"Que saudade! / Que mico! / Tô de boa! / Tá de sacanagem!"},
          {id:"A1-U7-L2-E5",type:"free_writing",skill:"writing",question:"Escribí un diálogo informal entre dos amigos que se encuentran después de mucho tiempo. Usá 6 expresiones coloquiales. Mínimo 8 falas.",prompt:"— E aí, [nome]! / — [Expressão]! / — Quanto tempo! / — [estado] / — Que [expressão]!",hint:"E aí · que saudade · tô de boa/destruído · que legal · dar um rolê · mano/cara"}
        ]
      },
      {
        id: "A1-U7-L3",
        title: "Músicas e ritmos brasileiros",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você gosta de música brasileira?\n— Adoro! Ouço samba, bossa nova e MPB.\n— Conhece Caetano Veloso?\n— Claro! É um dos maiores músicos do Brasil. E você?\n— Sou mais de forró. Sou nordestino!\n— Forró é incrível para dançar! Você dança?\n— Danço sim! Forró, samba e um pouco de axé.",
        memoryPhrases: ["Você gosta de música?","Ouço muito samba/MPB.","Você conhece...?","Você dança?","Danço sim/um pouco!"],
        oralProduction: "SITUAÇÃO ORAL: Fale sobre sua relação com a música e com a música brasileira. O que você conhece? Você dança? Mínimo 5 frases.",
        content: "# Músicas e Ritmos Brasileiros\n\n## Os gêneros\nSamba=el más tradicional, corazón del Carnaval\nBossa Nova=samba+jazz, años 50-60, João Gilberto y Tom Jobim\nMPB=Música Popular Brasileira (nombre genérico de calidad)\nForró=ritmo del Nordeste, muy bailable\nAxé=ritmo afrobrasileño de Salvador\nSertanejo=música country brasileño\nFunk carioca=origen en Rio, muy popular\nPagode=variación del samba\n\n## Artistas essenciais\nJoão Gilberto · Tom Jobim · Caetano Veloso · Gilberto Gil\nChico Buarque · Elis Regina · Milton Nascimento\nMarisa Monte · Seu Jorge · Anitta\n\n## Músicas para aprender português\nGarota de Ipanema (Bossa Nova)\nAquarela do Brasil (Samba)\nO Que Será (Chico Buarque)\n\n## Verbos para música\nouvir=escuchar · tocar=tocar (instrumento)\ncantarolar=tararear · dançar=bailar\ngostar de · curtir=disfrutar (coloquial)",
        exercises: [
          {id:"A1-U7-L3-E1",type:"multiple_choice",skill:"culture",question:"¿Qué género es una mezcla de samba con jazz, de los años 50-60?",options:["Forró","Axé","Bossa Nova","Funk"],answer:2,explanation:"Bossa Nova = samba + jazz. João Gilberto y Tom Jobim.",hint:"Samba + Jazz, años 50-60"},
          {id:"A1-U7-L3-E2",type:"fill_blank",skill:"culture",question:"El ritmo típico del Nordeste brasileño se llama ___.",answer:["forró"],hint:"Ritmo nordestino con triângulo, zabumba y sanfona",explanation:"Forró = ritmo del Nordeste. Muy popular en las festas juninas."},
          {id:"A1-U7-L3-E3",type:"multiple_choice",skill:"grammar",question:"'Você ___ tocar algum instrumento?' (saber)",options:["sabes","sabe","sabem","sei"],answer:1,explanation:"SABER para VOCÊ: SABE.",hint:"SABER para você"},
          {id:"A1-U7-L3-E4",type:"translation",skill:"writing",question:"Traduce: 'Me gusta mucho la bossa nova. Escucho João Gilberto todos los días. ¿Conocés algún artista brasileño?'",answer:["gosto muito de bossa nova","ouço joão gilberto todos os dias","você conhece algum artista brasileiro"],hint:"gosto muito de · ouço · todos os dias · você conhece",explanation:"Gosto muito de bossa nova. Ouço João Gilberto todos os dias. Você conhece algum artista brasileiro?"},
          {id:"A1-U7-L3-E5",type:"free_writing",skill:"writing",question:"Describí tu relación con la música: géneros favoritos, si tocás instrumento, qué música brasileña conocés. Mínimo 5 oraciones.",prompt:"Gosto muito de... / Ouço... / Toco... / Da música brasileira, conheço... / Gostaria de conhecer...",hint:"Gostaria de = me gustaría · conhecer=conocer"}
        ]
      },
      {
        id: "A1-U7-L4",
        title: "As festas e tradições brasileiras",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você já foi ao Carnaval?\n— Ainda não, mas quero muito ir!\n— O de Salvador é incrível. Também o do Rio.\n— São muito diferentes?\n— Muito! Salvador é na rua, os trios elétricos passam cantando.\n— E no Rio?\n— No Rio tem o sambódromo com as escolas de samba.\n— Quando acontece?\n— Em fevereiro. Você deveria ir!",
        memoryPhrases: ["Você já foi ao Carnaval?","Ainda não, mas quero ir!","Em fevereiro/junho.","É uma tradição!","Você deveria ir!"],
        oralProduction: "SITUAÇÃO ORAL: Um amigo quer que você vá ao Carnaval. Pergunte: quando é, onde ir, o que levar, quanto custa. Simule a conversa completa.",
        content: "# As Festas e Tradições Brasileiras\n\n## O Carnaval\nO maior evento cultural do mundo!\nQuando: fevereiro ou março (antes da Quaresma)\nOnde é famoso:\n- Rio de Janeiro: Sambódromo + blocos de rua\n- Salvador: Carnaval de rua, trios elétricos\n- Recife/Olinda: Frevo e maracatu\n- São Paulo: Sambódromo de SP\n\n## Festas Juninas\nQuando: junho (o mês MAIS festivo no interior)\nO que: São João, São Pedro, Santo Antônio\nCaracterísticas: forró, fogueira, comida típica\nComidas: milho, canjica, pamonha, quentão\n\n## Outras tradições\nFesta do Peão de Boiadeiro=rodeo mayor\nBumba meu boi (Maranhão)\nFesta da Uva (Caxias do Sul) = italiano en el Sur\nRéveillon em Copacabana (500.000+ personas!)\n\n## Datas importantes\n7 setembro=Independência · Natal=25 dezembro\nRéveillon=31 dezembro · Carnaval=fev/março",
        exercises: [
          {id:"A1-U7-L4-E1",type:"multiple_choice",skill:"culture",question:"¿En qué mes ocurre el Carnaval brasileño generalmente?",options:["Janeiro","Fevereiro/Março","Junho","Dezembro"],answer:1,explanation:"El Carnaval es en febrero o marzo, antes de la Cuaresma.",hint:"Antes de la Cuaresma/Semana Santa"},
          {id:"A1-U7-L4-E2",type:"fill_blank",skill:"culture",question:"Las festividades de ___ son en junio, con forró y comida típica.",answer:["festas juninas","festa junina"],hint:"Las fiestas de junio en Brasil",explanation:"Festas Juninas = fiestas de junio en honor a São João, São Pedro y Santo António."},
          {id:"A1-U7-L4-E3",type:"multiple_choice",skill:"culture",question:"¿Qué caracteriza el Carnaval de Salvador vs el de Rio?",options:["Tiene sambódromo","Es en marzo","Es en las calles con trios elétricos","Es más pequeño"],answer:2,explanation:"Salvador es en las calles con trios elétricos. Rio tiene Sambódromo.",hint:"La diferencia principal entre Salvador y Rio"},
          {id:"A1-U7-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'Quiero ir al Carnaval de Salvador el año que viene. ¿Cuándo exactamente es?'",answer:["quero ir ao carnaval de salvador no próximo ano","quando exatamente é"],hint:"quero ir ao · próximo ano=el año que viene · quando exatamente",explanation:"Quero ir ao Carnaval de Salvador no próximo ano. Quando exatamente é?"},
          {id:"A1-U7-L4-E5",type:"free_writing",skill:"writing",question:"Comparé una festividad de tu país con el Carnaval o las Festas Juninas. ¿En qué se parecen y diferencian? Mínimo 5 oraciones.",prompt:"No meu país temos uma festa chamada... / É em... / Em comparação com o Brasil... / O que parece similar é...",hint:"Em comparação · similar · diferente · parecido"}
        ]
      },
      {
        id: "A1-U7-L5",
        title: "O corpo humano e a saúde",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Não estou me sentindo bem.\n— O que está acontecendo?\n— Estou com dor de cabeça e febre.\n— Desde quando?\n— Desde ontem à noite. Também com dor de garganta.\n— Você precisa ver um médico.\n— Não tenho plano de saúde aqui.\n— Tem o pronto-socorro público. É gratuito no Brasil!\n— Que bom! Onde fica o mais próximo?",
        memoryPhrases: ["Não estou me sentindo bem.","Estou com dor de...","Preciso de um médico.","Tenho febre.","O SUS é gratuito!"],
        oralProduction: "SITUAÇÃO ORAL: Você não está bem. Ligue para um pronto-socorro e explique seus sintomas. Depois pergunte como chegar. Simule a conversa completa.",
        content: "# O Corpo e a Saúde\n\n## O corpo humano\ncabeça · cabelo · rosto=cara · olho/olhos\nouvido=oído · nariz · boca · dente\ngarganta · pescoço=cuello · ombro=hombro\nbraço · mão · dedo · barriga=panza\ncostas=espalda · perna · joelho=rodilla\npé · tornozelo=tobillo\n\n## Sintomas e doenças\nEstou com:\ndor de cabeça · dor de barriga · dor de garganta\ndor nas costas · febre · gripe · resfriado\nnáusea · tontura=mareo · cansaço · alergia\n\n## No consultório\nPreciso de um médico. · Estou me sentindo mal.\nDesde quando? · Tem alergia a medicamentos?\nPrecisa de receita. · Tome... comprimidos de...\n\n## Sistema de saúde\nSUS = Sistema Único de Saúde = GRATUITO para todos\nPlano de saúde=seguro médico privado\nFarmácia=farmacia · Pronto-socorro=urgencias\nUPA = Unidade de Pronto Atendimento",
        exercises: [
          {id:"A1-U7-L5-E1",type:"multiple_choice",skill:"vocabulary",question:"¿Cómo se dice 'dolor de cabeza' en português?",options:["dor de barriga","dor de garganta","dor de cabeça","dor nas costas"],answer:2,explanation:"Dor de cabeça = dolor de cabeza.",hint:"Cabeça = cabeza"},
          {id:"A1-U7-L5-E2",type:"fill_blank",skill:"grammar",question:"'Estou ___ febre e dor de cabeça.' (con — para síntomas)",answer:["com"],hint:"Para síntomas: Estou COM + síntoma",explanation:"ESTAR COM + síntoma = tener (síntoma). Estou com febre = tengo fiebre."},
          {id:"A1-U7-L5-E3",type:"multiple_choice",skill:"culture",question:"¿Qué es el SUS en Brasil?",options:["Un seguro privado","El sistema de salud pública gratuita","Un hospital privado","Una farmacia del gobierno"],answer:1,explanation:"SUS = Sistema Único de Saúde. GRATUITA para todos, incluyendo turistas.",hint:"Sistema de salud pública y gratuita"},
          {id:"A1-U7-L5-E4",type:"translation",skill:"writing",question:"Traduce: 'No me estoy sintiendo bien. Tengo fiebre y dolor de garganta desde ayer. Necesito ir al médico.'",answer:["não estou me sentindo bem","estou com febre e dor de garganta desde ontem","preciso ir ao médico"],hint:"não estou me sentindo bem · com febre · dor de garganta · desde ontem",explanation:"Não estou me sentindo bem. Estou com febre e dor de garganta desde ontem. Preciso ir ao médico."},
          {id:"A1-U7-L5-E5",type:"free_writing",skill:"writing",question:"Describí la última vez que te sentiste mal. ¿Qué síntomas? ¿Fuiste al médico? ¿Qué te recetaron? Mínimo 5 oraciones.",prompt:"A última vez que me senti mal foi... / Estava com... / Fui ao médico que disse... / Tomei... / Depois me senti melhor.",hint:"a última vez · me senti · estava com · melhor=mejor"}
        ]
      }
    ]
  },
  {
    id: "A1-U8",
    title: "Consolidação — Pronto para o A2",
    description: "Repaso integrado y preparación para el nivel A2",
    lessons: [
      {
        id: "A1-U8-L1",
        title: "Revisão: SER, ESTAR e TER",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Deixa eu me apresentar! Sou a Carla, tenho trinta anos e sou de Curitiba.\n— Prazer! Eu sou o Rafael. Também sou do sul, de Florianópolis.\n— Que coincidência! Você está em SP faz quanto tempo?\n— Estou aqui há cinco anos. E você?\n— Tenho dois anos aqui. A gente já tem bastante em comum!\n— Com certeza! São Paulo une muita gente do Brasil inteiro.",
        memoryPhrases: ["Deixa eu me apresentar!","Sou de... / Tenho... anos.","Estou aqui há... anos.","Que coincidência!","A gente tem muito em comum."],
        oralProduction: "SITUAÇÃO ORAL: Apresente-se completamente como se fosse a primeira vez que alguém te conhece. Use SER, ESTAR e TER pelo menos 3 vezes cada. Mínimo 6 frases.",
        content: "# Revisão: SER, ESTAR e TER\n\n## SER — identidade permanente\neu sou · você/ele/ela/a gente é · nós somos · vocês/eles/elas são\n\nQuando usar SER:\n1. Nome/identidade: Sou a Maria.\n2. Origem: Sou de São Paulo.\n3. Profissão: Ela é médica.\n4. Característica permanente: Ele é alto.\n5. Hora: São três horas.\n6. Data: Hoje é segunda.\n7. Preço: Quanto é? É dez reais.\n\n## ESTAR — estado temporário\neu estou · você/ele/ela/a gente está · nós estamos · vocês/eles/elas estão\n\nQuando usar ESTAR:\n1. Estado físico/emocional: Estou cansado/feliz.\n2. Lugar: Estamos em São Paulo.\n3. Progressão: Estou trabalhando.\n4. Situação temporária: Está fechado.\n\n## TER — posesión, existência, obligação\neu tenho · você/ele/ela/a gente tem · nós temos · vocês/eles/elas têm\n\nQuando usar TER:\n1. Posesión: Tenho um carro.\n2. Edad: Tenho 25 anos.\n3. Existência (hay): Tem um problema aqui.\n4. Síntomas: Estou com febre. / Tenho febre.\n5. Obligación: Tenho que estudar.",
        exercises: [
          {id:"A1-U8-L1-E1",type:"multiple_choice",skill:"grammar",question:"¿Cuál usa SER, ESTAR y TER correctamente?",options:["Ela tem médica e está cansada.","Ela é médica, está cansada e tem dois filhos.","Ela é cansada e está médica.","Ela tem alta e é cansada."],answer:1,explanation:"SER (é médica) + ESTAR (está cansada) + TER (tem dois filhos). Combinación perfecta.",hint:"SER=identidade · ESTAR=estado temporal · TER=posesión"},
          {id:"A1-U8-L1-E2",type:"fill_blank",skill:"grammar",question:"'___ três horas da tarde.' (son las 3pm — para hora)",answer:["são"],hint:"Para las horas (plural) se usa SER",explanation:"SÃO três horas = Son las tres."},
          {id:"A1-U8-L1-E3",type:"multiple_choice",skill:"grammar",question:"'Não ___ ninguém aqui.' (hay — existencia)",options:["é","tem","está","sou"],answer:1,explanation:"TEM = hay (existencia). Não tem ninguém = no hay nadie.",hint:"TER = hay (existencia)"},
          {id:"A1-U8-L1-E4",type:"translation",skill:"writing",question:"Traduce: 'Soy profesora, tengo 35 años y estoy muy cansada hoy. Mi marido es médico y tiene mucho trabajo este mes.'",answer:["sou professora","tenho trinta e cinco anos","estou muito cansada hoje","meu marido é médico e tem muito trabalho este mês"],hint:"sou · tenho · estou · meu marido é · tem muito trabalho",explanation:"Sou professora, tenho trinta e cinco anos e estou muito cansada hoje. Meu marido é médico e tem muito trabalho este mês."},
          {id:"A1-U8-L1-E5",type:"free_writing",skill:"writing",question:"Escribí 10 oraciones usando SER, ESTAR y TER al menos 3 veces cada uno.",prompt:"(SER) Sou... / (ESTAR) Estou... / (TER) Tenho... / [continuar]",hint:"SER: identidade, origem, profissão · ESTAR: estado, lugar · TER: posesión, edad, existencia"}
        ]
      },
      {
        id: "A1-U8-L2",
        title: "Revisão: verbos no presente",
        shadowing: "Lê 3 vezes em voz alta:\n\n— O que você faz nas tardes de domingo?\n— Geralmente vou ao parque correr. Depois como algo leve e leio um livro.\n— Que vida saudável! Você nunca sai?\n— Às vezes saio com amigos à noite. Mas prefiro ficar em casa.\n— E no trabalho, o que você faz?\n— Sou designer. Crio identidades visuais para empresas.\n— Que legal! Você gosta?\n— Adoro! Faço o que amo.",
        memoryPhrases: ["O que você faz?","Geralmente vou ao...","Prefiro ficar em casa.","Às vezes saio com amigos.","Faço o que amo!"],
        oralProduction: "SITUAÇÃO ORAL: Descreva um dia típico usando 8 verbos diferentes no presente. Varie entre regulares e irregulares. Fale por 2 minutos.",
        content: "# Revisão: Verbos no Presente\n\n## Os três grupos\n-AR: falar · trabalhar · morar · gostar · precisar · comprar\n-ER: comer · beber · escrever · ler · aprender · entender\n-IR: partir · abrir · assistir · dormir · sair · vir · ouvir\n\n## Conjugação rápida\neu: -o (falo/como/parto) — EXCETO os irregulares\nvocê/ele/ela/a gente: -a/-e/-e\nnós: -amos/-emos/-imos\nvocês/eles/elas: -am/-em/-em\n\n## Irregulares que hay que dominar\nSER: sou/é/somos/são\nESTAR: estou/está/estamos/estão\nTER: tenho/tem/temos/têm\nIR: vou/vai/vamos/vão\nFAZER: faço/faz/fazemos/fazem\nPODER: posso/pode/podemos/podem\nQUERER: quero/quer/queremos/querem\nSABER: sei/sabe/sabemos/sabem\nVIR: venho/vem/vimos/vêm\nSAIR: saio/sai/saímos/saem\nOUVIR: ouço/ouve/ouvimos/ouvem",
        exercises: [
          {id:"A1-U8-L2-E1",type:"multiple_choice",skill:"grammar",question:"'Eu não ___ sair hoje. Estou com muito trabalho.' (poder)",options:["pode","posso","podem","podemos"],answer:1,explanation:"PODER para EU: POSSO. Negativa: não POSSO sair.",hint:"PODER para EU → POSSO"},
          {id:"A1-U8-L2-E2",type:"fill_blank",skill:"grammar",question:"'Eles ___ muito bem inglês.' (saber)",answer:["sabem"],hint:"SABER para eles/vocês",explanation:"SABER para ELES: SABEM."},
          {id:"A1-U8-L2-E3",type:"multiple_choice",skill:"grammar",question:"'A que horas ___ os bancos aqui?' (abrir)",options:["abro","abre","abrem","abrimos"],answer:2,explanation:"OS BANCOS (plural) + ABRIR → ABREM.",hint:"Os bancos = plural → -em"},
          {id:"A1-U8-L2-E4",type:"translation",skill:"writing",question:"Traduce: 'Mis amigos salen todos los viernes. Yo prefiero quedarme en casa, leer y escuchar música brasileña.'",answer:["meus amigos saem todas as sextas","eu prefiro ficar em casa","ler e ouvir música brasileira"],hint:"saem (SAIR irregular) · prefiro · ficar em casa · ler · ouvir",explanation:"Meus amigos saem todas as sextas. Eu prefiro ficar em casa, ler e ouvir música brasileira."},
          {id:"A1-U8-L2-E5",type:"free_writing",skill:"writing",question:"Describí una semana tuya usando 10 verbos en presente. Incluí regulares e irregulares. Mínimo 7 oraciones.",prompt:"Na segunda... / Na terça vou... / A gente sempre... / Nos fins de semana...",hint:"ir · ter · fazer · poder · querer · saber · vir · sair · ouvir"}
        ]
      },
      {
        id: "A1-U8-L3",
        title: "Revisão: pretérito perfeito e imperfeito",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você foi ao Carnaval este ano?\n— Fui sim! Mas antes eu nunca tinha ido.\n— Antes você não gostava de samba?\n— Gostava! Mas quando era criança, morava no interior.\n— E quando você foi a primeira vez?\n— Fui com vinte e dois anos, para Salvador.\n— E adorou?\n— Amei! Dancei, cantei, vi tudo! Foi a melhor experiência da minha vida.",
        memoryPhrases: ["Antes eu nunca tinha...","Quando era criança...","Fui a primeira vez...","Adorei/Amei!","Que inveja boa!"],
        oralProduction: "SITUAÇÃO ORAL: Compte como era sua vida 5 anos atrás vs como é hoje. Use Imperfeito para o passado e Presente para o hoje. Mínimo 8 frases.",
        content: "# Revisão: Perfeito vs Imperfeito\n\n## A diferença fundamental\nPERFEITO = ação COMPLETA e PONTUAL:\nontem · de repente · uma vez · já · ainda não\n→ Para contar o que aconteceu\n\nIMPERFEITO = HÁBITO ou ESTADO:\nquando era criança · antes · sempre · todo dia\n→ Para descrever e explicar hábitos\n\n## Tabela comparativa\nPerfeito: Ontem COMI pizza.\nImperfeito: Antes COMIA pizza toda semana.\n\nPerfeito: Ela CHEGOU às 8.\nImperfeito: Ela sempre CHEGAVA às 8.\n\n## Combinação (narrativa)\nImperfeito (fondo) + Perfeito (acción puntual):\nEu DORMIA quando o telefone TOCOU.\nEla TRABALHAVA quando ele ENTROU.\n\n## Expressões chave\nPerfeito: ontem · de repente · já · logo · na semana passada\nImperfeito: quando era criança · antes · sempre · antigamente",
        exercises: [
          {id:"A1-U8-L3-E1",type:"multiple_choice",skill:"grammar",question:"'Quando era pequena, ela ___ todos os dias na praia.' (nadar — hábito)",options:["nadou","nada","nadava","nadaram"],answer:2,explanation:"Hábito en el pasado → Imperfeito: NADAVA.",hint:"Hábito pasado → Imperfeito"},
          {id:"A1-U8-L3-E2",type:"fill_blank",skill:"grammar",question:"'Ontem ela ___ ao cinema e ___ um filme.' (ir, ver — ações pontuais)",answer:["foi","viu"],hint:"Acciones específicas de ayer → Perfeito",explanation:"PERFEITO: FOI (ir) + VIU (ver). Ontem confirma que son puntuales."},
          {id:"A1-U8-L3-E3",type:"multiple_choice",skill:"grammar",question:"'Eu ___ (estudar) quando meu amigo ___ (ligar).'",options:["estudava/ligou","estudei/ligava","estudo/ligou","estudava/ligava"],answer:0,explanation:"ESTUDAVA (fondo/imperfeito) + LIGOU (acción que interrumpe/perfeito).",hint:"Fondo = Imperfeito · Interrupción = Perfeito"},
          {id:"A1-U8-L3-E4",type:"translation",skill:"writing",question:"Traduce: 'Cuando era niño/a, vivía en una ciudad pequeña. Jugaba con mis amigos todos los días. Un día, mi familia se mudó a São Paulo.'",answer:["quando era criança morava numa cidade pequena","brincava com meus amigos todos os dias","um dia minha família se mudou para são paulo"],hint:"quando era criança · morava · brincava · todos os dias · se mudou (MUDAR-SE)",explanation:"Quando era criança, morava numa cidade pequena. Brincava com meus amigos todos os dias. Um dia, minha família se mudou para São Paulo."},
          {id:"A1-U8-L3-E5",type:"free_writing",skill:"writing",question:"Escribí una historia del pasado mezclando los dos pretéritos. Narrá un evento importante con contexto (Imperfeito) y acciones (Perfeito). Mínimo 8 oraciones.",prompt:"Era... / Eu estava... / De repente... / Então... / Depois... / No fim...",hint:"Imperfeito: era · estava · tinha · fazia · morava\nPerfeito: foi · fiz · vi · disse · chegou"}
        ]
      },
      {
        id: "A1-U8-L4",
        title: "Produção oral e escrita integrada",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Você já pensou em morar no Brasil?\n— Penso nisso bastante! Adoro a cultura brasileira.\n— O que te atrai mais?\n— A alegria das pessoas, a comida, a música... E quero aprender português de verdade.\n— Seu português já está ótimo!\n— Obrigado! Ainda tenho muito para aprender, mas estou melhorando.\n— A prática faz a perfeição.\n— É verdade. Por isso estudo todos os dias!",
        memoryPhrases: ["Penso nisso bastante!","O que te atrai?","Ainda tenho muito para aprender.","Estou melhorando!","A prática faz a perfeição."],
        oralProduction: "PROVA ORAL: Fale por 3 minutos sobre você sem parar. Inclua: quem é, de onde vem, vida atual, passado, futuro e por que estuda português. Esta é sua demonstração do A1.",
        content: "# Integração: Oral e Escrita\n\n## O que você consegue em A1\n\n### Oral\n✅ Apresentar-se e cumprimentar\n✅ Falar sobre família, casa e rotina\n✅ Fazer compras e pedir informações\n✅ Contar o que fez no passado\n✅ Descrever pessoas e lugares\n✅ Entender português devagar e claro\n\n### Escrita\n✅ Escrever apresentação pessoal\n✅ Descrever rotina e família\n✅ Escrever email simples\n✅ Ler textos curtos\n\n## Estratégias para continuar\n1. Fale em voz alta TODOS os dias (5 min mínimo)\n2. Leia os diálogos desta app em voz alta\n3. Assista séries brasileiras com legendas em português\n4. Ouça músicas e tente entender a letra\n\n## Frases de motivação\nA prática faz a perfeição.\nDevagar se vai longe.\nQuerendo, se pode.\nO caminho se faz caminhando.",
        exercises: [
          {id:"A1-U8-L4-E1",type:"multiple_choice",skill:"grammar",question:"¿Cuál párrafo usa mejor el A1?",options:["Eu ser de Brasil e tenho muito anos.","Sou brasileira, tenho 28 anos e moro em SP há dois anos. Ontem fui ao cinema!","Eu estava ser de Brasil e fui jovem.","Sou de Brasil e ontem fui e fui."],answer:1,explanation:"Usa correctamente: SER (sou), TER (tenho), ESTAR (moro), Pretérito Perfeito (fui).",hint:"SER, TER y pretérito correctamente"},
          {id:"A1-U8-L4-E2",type:"fill_blank",skill:"grammar",question:"'Quando era pequeno, ___ (morar) no interior. Hoje ___ (morar) em São Paulo.'",answer:["morava","moro"],hint:"Hábito pasado → Imperfeito · Estado presente → Presente",explanation:"MORAVA (Imperfeito) + MORO (Presente). Contraste temporal."},
          {id:"A1-U8-L4-E3",type:"multiple_choice",skill:"grammar",question:"¿Cuál es el orden natural de una presentación?",options:["Profissão → Nome → Origem","Nome → Origem → Profissão → Estado atual","Estado → Nome → Profissão","Origem → Nome → Estado"],answer:1,explanation:"Nome (Me chamo...) → Origem (Sou de...) → Profissão (Trabalho como...) → Estado atual.",hint:"Lo más básico primero"},
          {id:"A1-U8-L4-E4",type:"translation",skill:"writing",question:"Traduce: 'Me llamo Carlos. Soy de Argentina pero vivo en Brasil hace tres años. Trabajo como ingeniero. Cuando era chico, soñaba con vivir en otro país.'",answer:["me chamo carlos","sou da argentina mas moro no brasil há três anos","trabalho como engenheiro","quando era pequeno sonhava em morar em outro país"],hint:"me chamo · sou da · moro há três anos · trabalho como · quando era pequeno · sonhava",explanation:"Me chamo Carlos. Sou da Argentina mas moro no Brasil há três anos. Trabalho como engenheiro. Quando era pequeno, sonhava em morar em outro país."},
          {id:"A1-U8-L4-E5",type:"free_writing",skill:"writing",question:"TEXTO FINAL A1: Escribí el mejor texto sobre tu vida. Presentación, familia, rutina, pasado y planes futuros. Mínimo 12 oraciones.",prompt:"Me chamo... / Sou de... / Minha família... / Todo dia eu... / Quando era criança... / No futuro quero...",hint:"SER · ESTAR · TER · presente · perfeito · imperfeito · IR + infinitivo"}
        ]
      },
      {
        id: "A1-U8-L5",
        title: "Avaliação final e próximos passos",
        shadowing: "Lê 3 vezes em voz alta:\n\n— Parabéns! Você completou o nível A1!\n— Obrigado! Aprendi muito.\n— Você consegue se apresentar, falar da família e contar histórias do passado.\n— Ainda tenho muito a aprender.\n— No A2 você vai aprender muito mais.\n— Quando começo?\n— Você já pode começar! O importante é não parar.\n— Vou estudar todo dia!\n— Isso! A constância é o segredo.\n— Obrigado por tudo! Até o A2!",
        memoryPhrases: ["Parabéns! Você conseguiu!","Aprendi muito!","Ainda tenho muito para aprender.","Vou continuar estudando!","A constância é o segredo."],
        oralProduction: "AVALIAÇÃO ORAL FINAL A1: Responda estas 5 perguntas em português sem preparação:\n1. Apresente-se completamente (2 min)\n2. Descreva sua família (1 min)\n3. Conte o que você fez ontem (1 min)\n4. Descreva como era sua infância (1 min)\n5. Quais são seus planos para o futuro? (1 min)\nTotal: 6 minutos. Este é o certificado real do seu A1.",
        content: "# Avaliação Final — Nível A1 Completo\n\n## O que você domina agora\n\n### Gramática\n✅ Pronomes: eu · você · a gente · ele/ela · nós · vocês · eles/elas\n✅ SER, ESTAR, TER — usos e diferenças\n✅ Verbos -AR, -ER, -IR no presente\n✅ Irregulares: ir · fazer · poder · querer · saber · sair · vir · ouvir\n✅ Pretérito Perfeito — regulares e irregulares\n✅ Pretérito Imperfeito — hábitos e descrições\n✅ Negação com NÃO\n✅ Palavras interrogativas completas\n✅ PODER, DEVER, PRECISAR, TER QUE\n✅ IR + infinitivo para o futuro\n✅ Preposições e contrações: ao · à · no · na · do · da · pelo · pela\n\n### Vocabulário\n✅ +500 palavras em contexto real\n✅ Saúdos · Números · Cores · Família · Casa\n✅ Roupas · Comida · Rotina · Cidade · Transporte\n✅ Profissões · Saúde · Cultura · Gírias\n\n## Seu caminho à fluência\nA1 ✅ → A2 → B1 → B2 → C1 → C2 → Master\n\nCon 30 min/día llegarás a B1 en 6 meses más.\n\n## O que faz a diferença\n1. Fala em voz alta TODOS OS DIAS\n2. Escuta música e series brasileiras\n3. Não tem medo de errar\n4. Repasa os erros cometidos\n5. Sê consistente — 30 min/dia é melhor que 3 horas no domingo",
        exercises: [
          {id:"A1-U8-L5-E1",type:"multiple_choice",skill:"grammar",question:"AVALIAÇÃO — ¿Cuál es la traducción correcta de 'Ayer fui al banco, saqué dinero y pagué las cuentas'?",options:["Ontem fui ao banco, tirei dinheiro e paguei as contas.","Ontem vou ao banco, tirava dinheiro e pagava as contas.","Ontem ia ao banco, tirei dinheiro e pago as contas.","Ontem fui ao banco, tirava dinheiro e paguei as contas."],answer:0,explanation:"Todo en Perfeito (completadas ayer): fui + tirei + paguei.",hint:"Todo en Pretérito Perfeito — ayer"},
          {id:"A1-U8-L5-E2",type:"fill_blank",skill:"grammar",question:"'Antes eu ___ muito café, mas agora ___ chá.' (beber — hábito pasado vs. presente)",answer:["bebia","bebo"],hint:"Hábito pasado = Imperfeito · Presente = Presente",explanation:"BEBIA (Imperfeito) + BEBO (Presente). Contraste antes/agora."},
          {id:"A1-U8-L5-E3",type:"multiple_choice",skill:"grammar",question:"AVALIAÇÃO — ¿Cuál oración es 100% correcta?",options:["Minha família tem cinco pessoas e moramos em São Paulo há dez anos.","Minha família é cinco pessoas e estamos em SP desde dez anos.","Minha família tem cinco pessoas e somos em SP por dez anos.","Minha família são cinco pessoas e moramos SP dez anos."],answer:0,explanation:"TER (quantidade) + MORAR + HÁ + tempo = llevar. Correcto.",hint:"TER para cantidade · HÁ + tempo = hace/llevar"},
          {id:"A1-U8-L5-E4",type:"translation",skill:"writing",question:"AVALIAÇÃO — Traduce: 'Soy Mariana, tengo 30 años y soy de São Paulo. Estudio português porque quiero hablar bien. Cuando era chica, aprendía inglés en la escuela.'",answer:["sou mariana","tenho trinta anos e sou de são paulo","estudo português porque quero falar bem","quando era pequena aprendia inglês na escola"],hint:"sou · tenho · estou · estudo · quero · quando era pequena · aprendia",explanation:"Sou Mariana, tenho trinta anos e sou de São Paulo. Estudo português porque quero falar bem. Quando era pequena, aprendia inglês na escola."},
          {id:"A1-U8-L5-E5",type:"free_writing",skill:"writing",question:"TEXTO FINAL DEFINITIVO: Escribí el mejor texto de tu vida en português sobre quién sos, quién eras y quién querés ser. Mínimo 15 oraciones. Sé creativo y demostrá que completaste el A1.",prompt:"Sou... / Minha história começa em... / Quando era... / Hoje... / No futuro quero... / O português para mim é...",hint:"SER · ESTAR · TER · presente · perfeito · imperfeito · IR + infinitivo. ¡Ya llegaste al A1!"}
        ]
      }
    ]
  }
];
