// Configuración de idiomas disponibles en Pipa Akd Escola
export const LANGUAGES = {
  // Idiomas que el usuario puede aprender
  learn: [
    {
      id: "es",
      name: "Español",
      nameNative: "Español",
      flag: "🇪🇸",
      color: "#0EA5E9",
      colorDark: "#0369A1",
      bgColor: "#F0F9FF",
      available: true,
      curriculum: "ES",
      voice: "es-MX",
      description: "El idioma más hablado de América Latina",
    },
    {
      id: "pt",
      name: "Português",
      nameNative: "Português do Brasil",
      flag: "🇧🇷",
      color: "#1D9E75",
      colorDark: "#0F6E56",
      bgColor: "#F0FFF4",
      available: true,
      curriculum: "PT",
      voice: "pt-BR",
      description: "La lengua del país más grande de América del Sur",
    },
    {
      id: "en",
      name: "English",
      nameNative: "English",
      flag: "🇺🇸",
      color: "#7C3AED",
      colorDark: "#5B21B6",
      bgColor: "#F5F3FF",
      available: false,
      comingSoon: true,
      curriculum: "EN",
      voice: "en-US",
      description: "O idioma mais importante do mundo dos negócios",
    },
    {
      id: "fr",
      name: "Français",
      nameNative: "Français",
      flag: "🇫🇷",
      color: "#DC2626",
      colorDark: "#991B1B",
      bgColor: "#FFF5F5",
      available: false,
      comingSoon: true,
      curriculum: "FR",
      voice: "fr-FR",
      description: "La langue de la culture et de la diplomatie",
    },
    {
      id: "it",
      name: "Italiano",
      nameNative: "Italiano",
      flag: "🇮🇹",
      color: "#16A34A",
      colorDark: "#15803D",
      bgColor: "#F0FFF4",
      available: false,
      comingSoon: true,
      curriculum: "IT",
      voice: "it-IT",
      description: "La lingua della musica, dell'arte e della cucina",
    },
    {
      id: "de",
      name: "Deutsch",
      nameNative: "Deutsch",
      flag: "🇩🇪",
      color: "#D97706",
      colorDark: "#B45309",
      bgColor: "#FFFBEB",
      available: false,
      comingSoon: true,
      curriculum: "DE",
      voice: "de-DE",
      description: "Die Sprache der Ingenieurskunst und Philosophie",
    },
    {
      id: "ja",
      name: "日本語",
      nameNative: "日本語",
      flag: "🇯🇵",
      color: "#E11D48",
      colorDark: "#BE123C",
      bgColor: "#FFF1F2",
      available: false,
      comingSoon: true,
      curriculum: "JA",
      voice: "ja-JP",
      description: "A língua do Japão, da tecnologia e da cultura pop",
    },
    {
      id: "ko",
      name: "한국어",
      nameNative: "한국어",
      flag: "🇰🇷",
      color: "#2563EB",
      colorDark: "#1D4ED8",
      bgColor: "#EFF6FF",
      available: false,
      comingSoon: true,
      curriculum: "KO",
      voice: "ko-KR",
      description: "A língua do K-pop, K-drama e Samsung",
    },
  ],

  // Idiomas nativos del usuario
  native: [
    { id: "pt-BR", name: "Português", flag: "🇧🇷" },
    { id: "es",    name: "Español",   flag: "🇪🇸" },
    { id: "en",    name: "English",   flag: "🇺🇸" },
  ],
};

// Textos de la interfaz según idioma nativo
export const UI_TEXTS = {
  "pt-BR": {
    welcome: "Bem-vindo ao Pipa Akd",
    subtitle: "Escola de idiomas gratuita · Do A1 ao Master",
    chooseLearn: "O que você quer aprender?",
    chooseNative: "Qual é o seu idioma?",
    comingSoon: "Em breve",
    start: "Começar",
    register: "Cadastrar",
    login: "Entrar",
    logout: "Sair",
    email: "Email",
    password: "Senha",
    passwordHint: "(mínimo 6 caracteres)",
    errorFields: "Preencha todos os campos.",
    errorPassword: "A senha deve ter pelo menos 6 caracteres.",
    errorLogin: "Email ou senha incorretos.",
    loading: "Carregando...",
    progress: "Progresso",
    streak: "Sequência",
    level: "Nível",
    lessons: "Lições",
    exercises: "Exercícios",
    reference: "Referência",
    theory: "Aula Teórica",
    back: "Voltar",
    next: "Próximo",
    correct: "Correto!",
    incorrect: "Incorreto",
    check: "Verificar",
    skip: "Pular",
    finish: "Finalizar",
    days: "dias",
    free: "Grátis · Sem anúncios · Do A1 ao Master",
    tagline: "Cansado do Duolingo? Criamos algo melhor ❤️",
  },
  "es": {
    welcome: "Bienvenido a Pipa Akd",
    subtitle: "Escuela de idiomas gratuita · De A1 a Master",
    chooseLearn: "¿Qué querés aprender?",
    chooseNative: "¿Cuál es tu idioma?",
    comingSoon: "Próximamente",
    start: "Empezar",
    register: "Registrarme",
    login: "Entrar",
    logout: "Salir",
    email: "Email",
    password: "Contraseña",
    passwordHint: "(mínimo 6 caracteres)",
    errorFields: "Completá todos los campos.",
    errorPassword: "La contraseña debe tener al menos 6 caracteres.",
    errorLogin: "Email o contraseña incorrectos.",
    loading: "Cargando...",
    progress: "Progreso",
    streak: "Racha",
    level: "Nivel",
    lessons: "Lecciones",
    exercises: "Ejercicios",
    reference: "Referência",
    theory: "Clase Teórica",
    back: "Volver",
    next: "Siguiente",
    correct: "¡Correcto!",
    incorrect: "Incorrecto",
    check: "Verificar",
    skip: "Saltar",
    finish: "Finalizar",
    days: "días",
    free: "Gratis · Sin publicidad · De A1 a Master",
    tagline: "¿Cansado del Duolingo? Creamos algo mejor ❤️",
  },
  "en": {
    welcome: "Welcome to Pipa Akd",
    subtitle: "Free language school · From A1 to Master",
    chooseLearn: "What do you want to learn?",
    chooseNative: "What is your language?",
    comingSoon: "Coming soon",
    start: "Start",
    register: "Sign up",
    login: "Log in",
    logout: "Log out",
    email: "Email",
    password: "Password",
    passwordHint: "(minimum 6 characters)",
    errorFields: "Please fill in all fields.",
    errorPassword: "Password must be at least 6 characters.",
    errorLogin: "Incorrect email or password.",
    loading: "Loading...",
    progress: "Progress",
    streak: "Streak",
    level: "Level",
    lessons: "Lessons",
    exercises: "Exercises",
    reference: "Reference",
    theory: "Theory Class",
    back: "Back",
    next: "Next",
    correct: "Correct!",
    incorrect: "Incorrect",
    check: "Check",
    skip: "Skip",
    finish: "Finish",
    days: "days",
    free: "Free · No ads · From A1 to Master",
    tagline: "Tired of Duolingo? We built something better ❤️",
  },
};
